# Libraries

In [1]:
import os
import math
import requests
import pandas as pd
import json, ast
from datetime import datetime, timedelta
import time
import paho.mqtt.client as mqtt

# 1. DATA RETRIEVAL

## 1.1. Declaring Constants

In [47]:
# ADD API KEY HERE
API_KEY="oe_3ZSXpKzAEksXKrKt9BKzZDzW" # API Key please use mindfully

In [48]:
#Configs
BASE_URL = "https://api.openelectricity.org.au/v4"
HEADERS = {"Authorization": f"Bearer {API_KEY}"}
OUTPUT_DIR = "./output"
os.makedirs(OUTPUT_DIR, exist_ok=True)
INTERVAL = "5m"

# Date range for 1st week of October 2025, End date is not inclusive.
START_DATE = datetime(2025, 10, 1)
END_DATE = datetime(2025, 10, 8)
REQUEST_DELAY = 60  # seconds between requests to avoid API limits

## 1.2. Fetching the list of Facilities

Fetch the list of all facilities for a given electricity network (default=NEM),  
Returns: pd.DataFrame: Facility metadata including name, region, code, location, and units.

In [49]:
def fetch_all_facilities(network: str = "NEM") -> pd.DataFrame:
    
    url = f"{BASE_URL}/facilities/"
    params = {
        "network_code": "NEM",
    }

    print("IN PROGRESS Fetching all facilities...")
    r = requests.get(url, headers=HEADERS, params=params)
    if r.status_code >= 400:
        print("API Error:")
        try:
            print(r.json())
        except Exception:
            print(r.text)
        r.raise_for_status()

    data = r.json().get("data", [])
    rows = []
    for entry in data:
        rows.append({
            "name": entry.get("name"),
      "network_id": entry.get("network_id"),
      "network_region": entry.get("network_region"),
      "description": entry.get("description"),
      "location": entry.get("location"),
       "code": entry.get("code"),

            "units": entry.get("units"),
        
          "created_at": entry.get("created_at"),
          "updated_at": entry.get("updated_at"),
       
       
        })

    df = pd.DataFrame(rows)
    print(f"SUCCESS Retrieved {len(df)} facilities")
    return df

facilities_df = fetch_all_facilities()

IN PROGRESS Fetching all facilities...
SUCCESS Retrieved 580 facilities

### 1.2.1. PER-FACILITY POWER GENERATED (5 min interval)

fetches 5-minute interval power generation data for every facility in the NEM network.

In [50]:
#fetches 5-minute interval power generation data for every facility in the NEM network.  
def fetch_facility_power(facility_id: str, start: datetime, end: datetime) -> pd.DataFrame:
    """Fetch 5-minute power data for a single facility and flatten it."""
    url = f"{BASE_URL}/data/facilities/NEM"
    #setting request parameters 
    params = {
        "metrics": ["power"],
        "interval": INTERVAL,
        "facility_code": facility_id,
        "date_start": START_DATE,
        "date_end": END_DATE,
        
    }

    # Make request and handle API / network issues safely
    try:
        r = requests.get(url, headers=HEADERS, params=params)
        r.raise_for_status()
        json_data = r.json()
    except Exception as e:
        print(f" Failed to fetch power for {facility_id}: {e}")
        return pd.DataFrame()

    # Check if the API returned success
    if not json_data.get("success", False):
        print(f" API returned failure for {facility_id}: {json_data.get('error')}")
        return pd.DataFrame()

    data = json_data.get("data", [])
    rows = []

    # Flatten nested JSON:
    for entry in data:
        unit_code = entry.get("unit", "MW")
        for res in entry.get("results", []):
            for point in res.get("data", []):
                timestamp, value = point
                rows.append({
                    "facility_id": facility_id,
                    "unit_code": unit_code,
                    "timestamp": timestamp,
                    "power_MW": value
                })

    return pd.DataFrame(rows)



# Step 1: Load facilities CSV (if needed)
facility_ids = facilities_df["code"]
print(f"IN PROGRESS Fetching power for {len(facility_ids)} facilities...")

all_power = []
count =1
# Step 2: Iterate over facilities
for facility_id in facility_ids:
    print(f"Fetching power for facility {facility_id}...count no "+ str(count))
    count+=1
    power_df = fetch_facility_power(facility_id, START_DATE, END_DATE)
    if power_df.empty:
        print(f" No data for {facility_id}")
    all_power.append(power_df)
    time.sleep(REQUEST_DELAY)

# Step 3: Combine all facilities
power_df_raw = pd.concat(all_power, ignore_index=True)

IN PROGRESS Fetching power for 580 facilities...
Fetching power for facility ADP...count no 1
Fetching power for facility ALBANY...count no 2
⚠️ Failed to fetch power for ALBANY: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=ALBANY&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for ALBANY
Fetching power for facility ALDGASF...count no 3
Fetching power for facility AMCORGR...count no 4
⚠️ Failed to fetch power for AMCORGR: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=AMCORGR&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for AMCORGR
Fetching power for facility ANGASTON...count no 5
Fetching power for facility APS...count no 6
⚠️ Failed to fetch power for APS: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=APS&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for APS
Fetching power for facility APPIN...count no 7
⚠️ Failed to fetch power for APPIN: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=APPIN&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for APPIN
Fetching power for facility ARWF...count no 8
Fetching power for facility AVLSF...count no 9
Fetching power for facility AWABAREF...count no 10
⚠️ Failed to fetch power for AWABAREF: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=AWABAREF&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for AWABAREF
Fetching power for facility BADGINGARRA...count no 11
⚠️ Failed to fetch power for BADGINGARRA: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=BADGINGARRA&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for BADGINGARRA
Fetching power for facility DEIBDL...count no 12
Fetching power for facility BAKING...count no 13
⚠️ Failed to fetch power for BAKING: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=BAKING&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for BAKING
Fetching power for facility BHWF...count no 14
Fetching power for facility BALBESS...count no 15
Fetching power for facility BBASEHOS...count no 16
⚠️ Failed to fetch power for BBASEHOS: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=BBASEHOS&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for BBASEHOS
Fetching power for facility BANGOWF...count no 17
Fetching power for facility BAPS...count no 18
⚠️ Failed to fetch power for BAPS: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=BAPS&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for BAPS
Fetching power for facility BANKSPT...count no 19
⚠️ Failed to fetch power for BANKSPT: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=BANKSPT&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for BANKSPT
Fetching power for facility BANNSP...count no 20
Fetching power for facility BARCALDN...count no 21
Fetching power for facility BARCSF...count no 22
Fetching power for facility BARKIPS...count no 23
Fetching power for facility BARRON...count no 24
Fetching power for facility BASTYAN...count no 25
Fetching power for facility BAYSW...count no 26
Fetching power for facility BBDISEL1...count no 27
⚠️ Failed to fetch power for BBDISEL1: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=BBDISEL1&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for BBDISEL1
Fetching power for facility BELLBAY...count no 28
⚠️ Failed to fetch power for BELLBAY: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=BELLBAY&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for BELLBAY
Fetching power for facility BBP31...count no 29
Fetching power for facility BLAIRFOX_BEROSRD_WF...count no 30
⚠️ Failed to fetch power for BLAIRFOX_BEROSRD_WF: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=BLAIRFOX_BEROSRD_WF&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for BLAIRFOX_BEROSRD_WF
Fetching power for facility BRYB1WF1...count no 31
Fetching power for facility BERWICK...count no 32
⚠️ Failed to fetch power for BERWICK: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=BERWICK&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for BERWICK
Fetching power for facility BERYLSF...count no 33
Fetching power for facility BIALAWF...count no 34
Fetching power for facility BLAYNEY...count no 35
⚠️ Failed to fetch power for BLAYNEY: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=BLAYNEY&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for BLAYNEY
Fetching power for facility SNOWY6...count no 36
Fetching power for facility BLUEGSF...count no 37
Fetching power for facility BLULAKE...count no 38
⚠️ Failed to fetch power for BLULAKE: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=BLULAKE&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for BLULAKE
Fetching power for facility BLUEWATERS...count no 39
⚠️ Failed to fetch power for BLUEWATERS: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=BLUEWATERS&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for BLUEWATERS
Fetching power for facility BLYTHB...count no 40
Fetching power for facility BOCOROCK...count no 41
Fetching power for facility BODWF...count no 42
Fetching power for facility MCKAY...count no 43
Fetching power for facility BOLIVAR...count no 44
Fetching power for facility BOLIVPS...count no 45
Fetching power for facility BOMENSF...count no 46
Fetching power for facility 0BCWF...count no 47
⚠️ Failed to fetch power for 0BCWF: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=0BCWF&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for 0BCWF
Fetching power for facility BBATTERY...count no 48
Fetching power for facility BRAEMARA...count no 49
Fetching power for facility B2PS...count no 50
Fetching power for facility BREMER_BAY...count no 51
⚠️ Failed to fetch power for BREMER_BAY: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=BREMER_BAY&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for BREMER_BAY
Fetching power for facility BRNDBES...count no 52
Fetching power for facility BROADMDW...count no 53
⚠️ Failed to fetch power for BROADMDW: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=BROADMDW&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for BROADMDW
Fetching power for facility 0BSSF...count no 54

⚠️ Failed to fetch power for 0BSSF: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=0BSSF&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for 0BSSF
Fetching power for facility BWTR1...count no 55
Fetching power for facility BHILLGT...count no 56
Fetching power for facility BROKENH...count no 57
Fetching power for facility BHB...count no 58
Fetching power for facility BROOKLYN...count no 59
⚠️ Failed to fetch power for BROOKLYN: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=BROOKLYN&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for BROOKLYN
Fetching power for facility BROWNMT...count no 60
⚠️ Failed to fetch power for BROWNMT: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=BROWNMT&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for BROWNMT
Fetching power for facility BPLANDF...count no 61
⚠️ Failed to fetch power for BPLANDF: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=BPLANDF&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for BPLANDF
Fetching power for facility 0WELLINGTONBESS...count no 62
⚠️ Failed to fetch power for 0WELLINGTONBESS: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=0WELLINGTONBESS&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for 0WELLINGTONBESS
Fetching power for facility BULGANA...count no 63
Fetching power for facility 0BUNDSF...count no 64
⚠️ Failed to fetch power for 0BUNDSF: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=0BUNDSF&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for 0BUNDSF
Fetching power for facility BNGSF1...count no 65
Fetching power for facility BNGSF2...count no 66
Fetching power for facility 0BUNGAMA...count no 67
⚠️ Failed to fetch power for 0BUNGAMA: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=0BUNGAMA&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for 0BUNGAMA
Fetching power for facility BDONGHYD...count no 68
⚠️ Failed to fetch power for BDONGHYD: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=BDONGHYD&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for BDONGHYD
Fetching power for facility BURRIN...count no 69
⚠️ Failed to fetch power for BURRIN: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=BURRIN&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for BURRIN
Fetching power for facility BUTLERSG...count no 70
Fetching power for facility 0CALBESS1...count no 71
⚠️ Failed to fetch power for 0CALBESS1: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=0CALBESS1&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for 0CALBESS1
Fetching power for facility 0CALBESS2...count no 72
⚠️ Failed to fetch power for 0CALBESS2: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=0CALBESS2&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for 0CALBESS2
Fetching power for facility CALL_A...count no 73
⚠️ Failed to fetch power for CALL_A: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=CALL_A&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for CALL_A
Fetching power for facility CALL_B...count no 74
Fetching power for facility CALLIDEC1...count no 75
Fetching power for facility CANUNDA1...count no 76
Fetching power for facility CAPBES...count no 77
Fetching power for facility CAPTL_WF...count no 78
Fetching power for facility CESF...count no 79
⚠️ Failed to fetch power for CESF: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=CESF&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for CESF
Fetching power for facility LI_WY_CA...count no 80
Fetching power for facility CATHROCK...count no 81
Fetching power for facility CTHLWF...count no 82
Fetching power for facility CETHANA...count no 83
Fetching power for facility CHALLWF...count no 84
Fetching power for facility CHPSTWF...count no 85
⚠️ Failed to fetch power for CHPSTWF: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=CHPSTWF&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for CHPSTWF
Fetching power for facility CHYTWF...count no 86
Fetching power for facility CHILDSF...count no 87
Fetching power for facility CHBESS...count no 88
Fetching power for facility CBWWBA...count no 89
Fetching power for facility CLARESF...count no 90
Fetching power for facility CLRKCWF...count no 91
Fetching power for facility CLAYTON...count no 92
⚠️ Failed to fetch power for CLAYTON: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=CLAYTON&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for CLAYTON
Fetching power for facility CLEMGPWF...count no 93
Fetching power for facility CLERMSF...count no 94
Fetching power for facility CLOVER...count no 95
Fetching power for facility CLUNY...count no 96
Fetching power for facility COCKBURN...count no 97
⚠️ Failed to fetch power for COCKBURN: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=COCKBURN&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for COCKBURN
Fetching power for facility CODRGTON...count no 98
⚠️ Failed to fetch power for CODRGTON: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=CODRGTON&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for CODRGTON
Fetching power for facility COHUNSF1...count no 99
Fetching power for facility COLEASF...count no 100
Fetching power for facility COLWF01...count no 101
Fetching power for facility INVESTEC_COLLGAR...count no 102
⚠️ Failed to fetch power for INVESTEC_COLLGAR: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=INVESTEC_COLLGAR&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for INVESTEC_COLLGAR
Fetching power for facility COLLIE...count no 103
⚠️ Failed to fetch power for COLLIE: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=COLLIE&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for COLLIE
Fetching power for facility COLLIE_ESR4...count no 104
⚠️ Failed to fetch power for COLLIE_ESR4: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=COLLIE_ESR4&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for COLLIE_ESR4
Fetching power for facility COLLIE_ESR...count no 105

⚠️ Failed to fetch power for COLLIE_ESR: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=COLLIE_ESR&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for COLLIE_ESR
Fetching power for facility COLLIE_BESS2...count no 106
⚠️ Failed to fetch power for COLLIE_BESS2: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=COLLIE_BESS2&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for COLLIE_BESS2
Fetching power for facility COLNSV...count no 107
⚠️ Failed to fetch power for COLNSV: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=COLNSV&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for COLNSV
Fetching power for facility CSPVPS...count no 108
Fetching power for facility COLONGRA...count no 109
Fetching power for facility COLUMSF...count no 110
Fetching power for facility CPSA...count no 111
Fetching power for facility CONDONG1...count no 112
Fetching power for facility CBWF...count no 113
⚠️ Failed to fetch power for CBWF: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=CBWF&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for CBWF
Fetching power for facility COOPGWF...count no 114
Fetching power for facility COPTNHYD...count no 115
⚠️ Failed to fetch power for COPTNHYD: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=COPTNHYD&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for COPTNHYD
Fetching power for facility CORIO...count no 116
⚠️ Failed to fetch power for CORIO: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=CORIO&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for CORIO
Fetching power for facility CRWASF1...count no 117
Fetching power for facility CROOKWEL...count no 118
⚠️ Failed to fetch power for CROOKWEL: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=CROOKWEL&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for CROOKWEL
Fetching power for facility CROOKWF2...count no 119
Fetching power for facility CROOKWF3...count no 120
Fetching power for facility CROWLWF...count no 121
Fetching power for facility CRURWF1...count no 122
Fetching power for facility CULCSF...count no 123
Fetching power for facility CULLERIN...count no 124
Fetching power for facility SBSOLAR1_CUNDERDIN_PV...count no 125
⚠️ Failed to fetch power for SBSOLAR1_CUNDERDIN_PV: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=SBSOLAR1_CUNDERDIN_PV&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for SBSOLAR1_CUNDERDIN_PV
Fetching power for facility DAANDINE...count no 126
⚠️ Failed to fetch power for DAANDINE: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=DAANDINE&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for DAANDINE
Fetching power for facility DALNTH...count no 127
Fetching power for facility DDPS1...count no 128
Fetching power for facility DDSF...count no 129
Fetching power for facility DARLSF...count no 130
Fetching power for facility DPNTB...count no 131
Fetching power for facility DARTM...count no 132
Fetching power for facility DAYDSF...count no 133
Fetching power for facility DCWL_DENMARK...count no 134
⚠️ Failed to fetch power for DCWL_DENMARK: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=DCWL_DENMARK&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for DCWL_DENMARK
Fetching power for facility DEVILS_G...count no 135
Fetching power for facility DIAPURWF...count no 136
Fetching power for facility DRYCGT...count no 137
Fetching power for facility DULAWF...count no 138
Fetching power for facility DUNDWF...count no 139
Fetching power for facility PMATTAEP...count no 140
⚠️ Failed to fetch power for PMATTAEP: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=PMATTAEP&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for PMATTAEP
Fetching power for facility EASTCRK...count no 141
⚠️ Failed to fetch power for EASTCRK: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=EASTCRK&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for EASTCRK
Fetching power for facility EASTCRK2...count no 142
⚠️ Failed to fetch power for EASTCRK2: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=EASTCRK2&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for EASTCRK2
Fetching power for facility EDENVSF...count no 143
Fetching power for facility EILDON...count no 144
Fetching power for facility EILDONPD...count no 145
⚠️ Failed to fetch power for EILDONPD: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=EILDONPD&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for EILDONPD
Fetching power for facility ELAINEWF...count no 146
Fetching power for facility EMERASF...count no 147
Fetching power for facility EDWFMAN...count no 148
⚠️ Failed to fetch power for EDWFMAN: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=EDWFMAN&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for EDWFMAN
Fetching power for facility ENERGYB...count no 149
⚠️ Failed to fetch power for ENERGYB: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=ENERGYB&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for ENERGYB
Fetching power for facility ERARING...count no 150
Fetching power for facility ERB...count no 151
Fetching power for facility ERGT01...count no 152
Fetching power for facility 0ERB2...count no 153
⚠️ Failed to fetch power for 0ERB2: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=0ERB2&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for 0ERB2
Fetching power for facility FWF...count no 154
⚠️ Failed to fetch power for FWF: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=FWF&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for FWF
Fetching power for facility FINLEYSF...count no 155
Fetching power for facility FISHER...count no 156
Fetching power for facility FLATROCKS...count no 157
⚠️ Failed to fetch power for FLATROCKS: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=FLATROCKS&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for FLATROCKS
Fetching power for facility FLYCRKWF...count no 158
Fetching power for facility 0FULHAMSF...count no 159

⚠️ Failed to fetch power for 0FULHAMSF: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=0FULHAMSF&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for 0FULHAMSF
Fetching power for facility GANGARR...count no 160
Fetching power for facility GANNBESS...count no 161
Fetching power for facility GANNSF...count no 162
Fetching power for facility GEORGTWN...count no 163
⚠️ Failed to fetch power for GEORGTWN: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=GEORGTWN&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for GEORGTWN
Fetching power for facility TESLA_GERALDTON...count no 164
⚠️ Failed to fetch power for TESLA_GERALDTON: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=TESLA_GERALDTON&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for TESLA_GERALDTON
Fetching power for facility GERMCRK...count no 165
Fetching power for facility GIRGSF...count no 166
Fetching power for facility GSTONE...count no 167
Fetching power for facility GLBWNHYD...count no 168
⚠️ Failed to fetch power for GLBWNHYD: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=GLBWNHYD&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for GLBWNHYD
Fetching power for facility 0GLENELLEN...count no 169
⚠️ Failed to fetch power for 0GLENELLEN: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=0GLENELLEN&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for 0GLENELLEN
Fetching power for facility GLENMAGG...count no 170
⚠️ Failed to fetch power for GLENMAGG: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=GLENMAGG&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for GLENMAGG
Fetching power for facility GLENNCRK...count no 171
⚠️ Failed to fetch power for GLENNCRK: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=GLENNCRK&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for GLENNCRK
Fetching power for facility GLENSF...count no 172
Fetching power for facility GLRWNSF...count no 173
Fetching power for facility 0GNARWARREBESS...count no 174
⚠️ Failed to fetch power for 0GNARWARREBESS: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=0GNARWARREBESS&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for 0GNARWARREBESS
Fetching power for facility GPWFEST...count no 175
Fetching power for facility 0GPWFWST...count no 176
⚠️ Failed to fetch power for 0GPWFWST: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=0GPWFWST&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for 0GPWFWST
Fetching power for facility GOONUMSF...count no 177
Fetching power for facility 0GOORESF...count no 178
⚠️ Failed to fetch power for 0GOORESF: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=0GOORESF&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for 0GOORESF
Fetching power for facility GORDON...count no 179
Fetching power for facility GOSNELLS...count no 180
⚠️ Failed to fetch power for GOSNELLS: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=GOSNELLS&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for GOSNELLS
Fetching power for facility 0GRIVSF...count no 181
⚠️ Failed to fetch power for 0GRIVSF: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=0GRIVSF&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for 0GRIVSF
Fetching power for facility GSWF...count no 182
Fetching power for facility GRANGEAV...count no 183
⚠️ Failed to fetch power for GRANGEAV: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=GRANGEAV&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for GRANGEAV
Fetching power for facility GRANWF...count no 184
Fetching power for facility GRASMERE...count no 185
⚠️ Failed to fetch power for GRASMERE: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=GRASMERE&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for GRASMERE
Fetching power for facility GREENB...count no 186
Fetching power for facility GREENOUGH_RIVER...count no 187
⚠️ Failed to fetch power for GREENOUGH_RIVER: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=GREENOUGH_RIVER&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for GREENOUGH_RIVER
Fetching power for facility GRIFSF...count no 188
Fetching power for facility GROSV1...count no 189
⚠️ Failed to fetch power for GROSV1: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=GROSV1&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for GROSV1
Fetching power for facility GROSV2...count no 190
⚠️ Failed to fetch power for GROSV2: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=GROSV2&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for GROSV2
Fetching power for facility GULLRGWF...count no 191
Fetching power for facility GNNDHSF...count no 192
Fetching power for facility GUNNING...count no 193
Fetching power for facility 0GUNSYNDSF...count no 194
⚠️ Failed to fetch power for 0GUNSYNDSF: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=0GUNSYNDSF&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for 0GUNSYNDSF
Fetching power for facility SNOWY3...count no 195
Fetching power for facility HLMSEW01...count no 196
⚠️ Failed to fetch power for HLMSEW01: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=HLMSEW01&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for HLMSEW01
Fetching power for facility HALAMRD...count no 197
⚠️ Failed to fetch power for HALAMRD: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=HALAMRD&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for HALAMRD
Fetching power for facility AGLHAL...count no 198
Fetching power for facility HALLWF...count no 199
Fetching power for facility HALLWF2...count no 200
Fetching power for facility HAMISF...count no 201
Fetching power for facility HAMPTON...count no 202
⚠️ Failed to fetch power for HAMPTON: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=HAMPTON&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for HAMPTON
Fetching power for facility HVWW...count no 203

Fetching power for facility HASTING...count no 204
⚠️ Failed to fetch power for HASTING: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=HASTING&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for HASTING
Fetching power for facility HAUGHT1...count no 205
Fetching power for facility HD1WF...count no 206
Fetching power for facility HAYMSF...count no 207
Fetching power for facility HAZEL...count no 208
⚠️ Failed to fetch power for HAZEL: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=HAZEL&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for HAZEL
Fetching power for facility HBESS...count no 209
Fetching power for facility HENDERSON_RENEWABLE...count no 210
⚠️ Failed to fetch power for HENDERSON_RENEWABLE: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=HENDERSON_RENEWABLE&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for HENDERSON_RENEWABLE
Fetching power for facility HEPWIND...count no 211
⚠️ Failed to fetch power for HEPWIND: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=HEPWIND&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for HEPWIND
Fetching power for facility HIGHBRY...count no 212
⚠️ Failed to fetch power for HIGHBRY: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=HIGHBRY&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for HIGHBRY
Fetching power for facility HILLSTN...count no 213
Fetching power for facility HORNSDAL...count no 214
Fetching power for facility HORNSDAL2...count no 215
Fetching power for facility HORNSDAL3...count no 216
Fetching power for facility HORNSDPR...count no 217
Fetching power for facility 0HORSHAMSF...count no 218
⚠️ Failed to fetch power for 0HORSHAMSF: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=0HORSHAMSF&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for 0HORSHAMSF
Fetching power for facility HUGSF...count no 219
Fetching power for facility HUMENSW...count no 220
Fetching power for facility HUMEV...count no 221
Fetching power for facility HUNTER...count no 222
Fetching power for facility HEZ...count no 223
Fetching power for facility HUNTVGT...count no 224
⚠️ Failed to fetch power for HUNTVGT: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=HUNTVGT&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for HUNTVGT
Fetching power for facility INVICTA...count no 225
⚠️ Failed to fetch power for INVICTA: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=INVICTA&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for INVICTA
Fetching power for facility ICSM...count no 226
⚠️ Failed to fetch power for ICSM: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=ICSM&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for ICSM
Fetching power for facility JACKSGUL...count no 227
⚠️ Failed to fetch power for JACKSGUL: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=JACKSGUL&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for JACKSGUL
Fetching power for facility JEERA...count no 228
Fetching power for facility JEERB...count no 229
Fetching power for facility JEMALNG1...count no 230
Fetching power for facility JNDSHPS...count no 231
⚠️ Failed to fetch power for JNDSHPS: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=JNDSHPS&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for JNDSHPS
Fetching power for facility SNWYGJP2...count no 232
Fetching power for facility JBUTTERS...count no 233
Fetching power for facility JOUNAMA...count no 234
⚠️ Failed to fetch power for JOUNAMA: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=JOUNAMA&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for JOUNAMA
Fetching power for facility JUNEESF...count no 235
Fetching power for facility KABANWF...count no 236
Fetching power for facility KALAMUNDA_SG...count no 237
⚠️ Failed to fetch power for KALAMUNDA_SG: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=KALAMUNDA_SG&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for KALAMUNDA_SG
Fetching power for facility KALBARRI...count no 238
⚠️ Failed to fetch power for KALBARRI: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=KALBARRI&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for KALBARRI
Fetching power for facility STHRNCRS...count no 239
⚠️ Failed to fetch power for STHRNCRS: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=STHRNCRS&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for STHRNCRS
Fetching power for facility KARSF...count no 240
Fetching power for facility BLAIRFOX_KARAKIN...count no 241
⚠️ Failed to fetch power for BLAIRFOX_KARAKIN: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=BLAIRFOX_KARAKIN&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for BLAIRFOX_KARAKIN
Fetching power for facility KAREEYA...count no 242
Fetching power for facility KEEPIT...count no 243
⚠️ Failed to fetch power for KEEPIT: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=KEEPIT&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for KEEPIT
Fetching power for facility KEMERTON...count no 244
⚠️ Failed to fetch power for KEMERTON: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=KEMERTON&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for KEMERTON
Fetching power for facility TESLA_KEMERTON...count no 245
⚠️ Failed to fetch power for TESLA_KEMERTON: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=TESLA_KEMERTON&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for TESLA_KEMERTON
Fetching power for facility AGLSITA...count no 246
⚠️ Failed to fetch power for AGLSITA: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=AGLSITA&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for AGLSITA
Fetching power for facility KENNEDY...count no 247
Fetching power for facility KERNGSP...count no 248
Fetching power for facility KIAMSF1...count no 249
Fetching power for facility KIATAWF...count no 250

Fetching power for facility 0KIDSTON...count no 251
⚠️ Failed to fetch power for 0KIDSTON: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=0KIDSTON&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for 0KIDSTON
Fetching power for facility KSP1...count no 252
Fetching power for facility KINCUMB...count no 253
⚠️ Failed to fetch power for KINCUMB: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=KINCUMB&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for KINCUMB
Fetching power for facility KINGASF...count no 254
Fetching power for facility 0KINGS_ROCK_WF...count no 255
⚠️ Failed to fetch power for 0KINGS_ROCK_WF: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=0KINGS_ROCK_WF&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for 0KINGS_ROCK_WF
Fetching power for facility KOGANCK...count no 256
Fetching power for facility KOOLKHAN...count no 257
⚠️ Failed to fetch power for KOOLKHAN: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=KOOLKHAN&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for KOOLKHAN
Fetching power for facility KESS1...count no 258
Fetching power for facility KRCCOGEN...count no 259
⚠️ Failed to fetch power for KRCCOGEN: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=KRCCOGEN&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for KRCCOGEN
Fetching power for facility KWINANA...count no 260
⚠️ Failed to fetch power for KWINANA: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=KWINANA&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for KWINANA
Fetching power for facility KWINANA_ESR...count no 261
⚠️ Failed to fetch power for KWINANA_ESR: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=KWINANA_ESR&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for KWINANA_ESR
Fetching power for facility KWINANA_ESR2...count no 262
⚠️ Failed to fetch power for KWINANA_ESR2: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=KWINANA_ESR2&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for KWINANA_ESR2
Fetching power for facility TIWEST_COG1...count no 263
⚠️ Failed to fetch power for TIWEST_COG1: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=TIWEST_COG1&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for TIWEST_COG1
Fetching power for facility PERTHENERGY_KWINANA...count no 264
⚠️ Failed to fetch power for PERTHENERGY_KWINANA: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=PERTHENERGY_KWINANA&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for PERTHENERGY_KWINANA
Fetching power for facility LADBROKE...count no 265
Fetching power for facility LBBESS...count no 266
Fetching power for facility LKBONNY1...count no 267
Fetching power for facility LKBONNY_2...count no 268
Fetching power for facility LKBONNY3...count no 269
Fetching power for facility LK_ECHO...count no 270
Fetching power for facility 0LANCSF...count no 271
⚠️ Failed to fetch power for 0LANCSF: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=0LANCSF&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for 0LANCSF
Fetching power for facility LVES...count no 272
Fetching power for facility LNGS...count no 273
Fetching power for facility LEM_WIL...count no 274
Fetching power for facility 0LIDDELLBESS...count no 275
⚠️ Failed to fetch power for 0LIDDELLBESS: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=0LIDDELLBESS&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for 0LIDDELLBESS
Fetching power for facility LIDDELL...count no 276
⚠️ Failed to fetch power for LIDDELL: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=LIDDELL&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for LIDDELL
Fetching power for facility LILYVASF...count no 277
Fetching power for facility 0LCNBESS...count no 278
⚠️ Failed to fetch power for 0LCNBESS: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=0LCNBESS&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for 0LCNBESS
Fetching power for facility LIMBESS...count no 279
⚠️ Failed to fetch power for LIMBESS: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=LIMBESS&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for LIMBESS
Fetching power for facility LIMOSF1...count no 280
Fetching power for facility LIMOSF2...count no 281
Fetching power for facility LGAPWF1...count no 282
Fetching power for facility 0LOCKHART...count no 283
⚠️ Failed to fetch power for 0LOCKHART: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=0LOCKHART&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for 0LOCKHART
Fetching power for facility LONGFORD...count no 284
⚠️ Failed to fetch power for LONGFORD: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=LONGFORD&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for LONGFORD
Fetching power for facility LRSF...count no 285
Fetching power for facility LONSDALE...count no 286
Fetching power for facility 0LOTUSCRKWF...count no 287
⚠️ Failed to fetch power for 0LOTUSCRKWF: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=0LOTUSCRKWF&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for 0LOTUSCRKWF
Fetching power for facility LOYYANGA...count no 288
Fetching power for facility LOYYB...count no 289
Fetching power for facility LUCASHGT...count no 290
⚠️ Failed to fetch power for LUCASHGT: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=LUCASHGT&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for LUCASHGT
Fetching power for facility LUCAS2S2...count no 291
⚠️ Failed to fetch power for LUCAS2S2: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=LUCAS2S2&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for LUCAS2S2
Fetching power for facility MACARTH...count no 292
Fetching power for facility MCINTYR...count no 293
Fetching power for facility MACKAY...count no 294
⚠️ Failed to fetch power for MACKAY: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=MACKAY&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for MACKAY
Fetching power for facility MACKNTSH...count no 295

Fetching power for facility MANSLR...count no 296
Fetching power for facility BRIDGETOWN_BIOMASS_PLANT...count no 297
⚠️ Failed to fetch power for BRIDGETOWN_BIOMASS_PLANT: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=BRIDGETOWN_BIOMASS_PLANT&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for BRIDGETOWN_BIOMASS_PLANT
Fetching power for facility MANNUMB...count no 298
Fetching power for facility MANNSF...count no 299
Fetching power for facility MAPS2...count no 300
Fetching power for facility MAROOWF1...count no 301
⚠️ Failed to fetch power for MAROOWF1: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=MAROOWF1&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for MAROOWF1
Fetching power for facility MARYRSF...count no 302
Fetching power for facility 0MARYVALE...count no 303
⚠️ Failed to fetch power for 0MARYVALE: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=0MARYVALE&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for 0MARYVALE
Fetching power for facility MEADOWBK...count no 304
Fetching power for facility 0MREH...count no 305
Fetching power for facility 0MREHA2...count no 306
Fetching power for facility MREHA3...count no 307
Fetching power for facility 0MERREDINBESS...count no 308
⚠️ Failed to fetch power for 0MERREDINBESS: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=0MERREDINBESS&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for 0MERREDINBESS
Fetching power for facility MERSOLAR...count no 309
⚠️ Failed to fetch power for MERSOLAR: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=MERSOLAR&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for MERSOLAR
Fetching power for facility NAMKKN_MERR...count no 310
⚠️ Failed to fetch power for NAMKKN_MERR: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=NAMKKN_MERR&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for NAMKKN_MERR
Fetching power for facility AMBRISOLAR...count no 311
⚠️ Failed to fetch power for AMBRISOLAR: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=AMBRISOLAR&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for AMBRISOLAR
Fetching power for facility METZSF...count no 312
Fetching power for facility MIDDLSF1...count no 313
Fetching power for facility MIDLDPS...count no 314
⚠️ Failed to fetch power for MIDLDPS: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=MIDLDPS&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for MIDLDPS
Fetching power for facility MILLMERN...count no 315
Fetching power for facility MINTARO...count no 316
Fetching power for facility ATLAS...count no 317
⚠️ Failed to fetch power for ATLAS: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=ATLAS&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for ATLAS
Fetching power for facility MOKOSF...count no 318
Fetching power for facility MOLNGSF1...count no 319
Fetching power for facility MOORAWF1...count no 320
Fetching power for facility MORANBAH...count no 321
⚠️ Failed to fetch power for MORANBAH: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=MORANBAH&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for MORANBAH
Fetching power for facility MBAHNTH...count no 322
Fetching power for facility MOREESF...count no 323
Fetching power for facility MWPS...count no 324
Fetching power for facility 0MORNBESS...count no 325
⚠️ Failed to fetch power for 0MORNBESS: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=0MORNBESS&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for 0MORNBESS
Fetching power for facility MORNW...count no 326
⚠️ Failed to fetch power for MORNW: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=MORNW&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for MORNW
Fetching power for facility 0MRTLKBESS...count no 327
⚠️ Failed to fetch power for 0MRTLKBESS: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=0MRTLKBESS&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for 0MRTLKBESS
Fetching power for facility MORTLK...count no 328
Fetching power for facility MRTLSWF...count no 329
Fetching power for facility MLWF...count no 330
Fetching power for facility SKYFRM_MTBARKER...count no 331
⚠️ Failed to fetch power for SKYFRM_MTBARKER: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=SKYFRM_MTBARKER&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for SKYFRM_MTBARKER
Fetching power for facility MOUSF...count no 332
Fetching power for facility MEWF...count no 333
Fetching power for facility MTGELWF...count no 334
Fetching power for facility MTMERCER...count no 335
Fetching power for facility MTMILLAR...count no 336
Fetching power for facility MP...count no 337
Fetching power for facility MSTUART...count no 338
Fetching power for facility 0MUCHEABESS...count no 339
⚠️ Failed to fetch power for 0MUCHEABESS: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=0MUCHEABESS&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for 0MUCHEABESS
Fetching power for facility MLLFGEF...count no 340
⚠️ Failed to fetch power for MLLFGEF: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=MLLFGEF&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for MLLFGEF
Fetching power for facility MLSP...count no 341
Fetching power for facility MUJA_AB...count no 342
⚠️ Failed to fetch power for MUJA_AB: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=MUJA_AB&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for MUJA_AB
Fetching power for facility MUJA...count no 343
⚠️ Failed to fetch power for MUJA: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=MUJA&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for MUJA
Fetching power for facility MWF_MUMBIDA...count no 344
⚠️ Failed to fetch power for MWF_MUMBIDA: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=MWF_MUMBIDA&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for MWF_MUMBIDA
Fetching power for facility MUNGARRA...count no 345
⚠️ Failed to fetch power for MUNGARRA: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=MUNGARRA&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for MUNGARRA
Fetching power for facility MM...count no 346

⚠️ Failed to fetch power for MM: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=MM&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for MM
Fetching power for facility MUCRKSF...count no 347
Fetching power for facility MUWAWF...count no 348
Fetching power for facility MURRAY...count no 349
Fetching power for facility MBPS2...count no 350
Fetching power for facility MUSSELRO...count no 351
Fetching power for facility NASF...count no 352
⚠️ Failed to fetch power for NASF: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=NASF&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for NASF
Fetching power for facility NEWGEN_NEERABUP...count no 353
⚠️ Failed to fetch power for NEWGEN_NEERABUP: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=NEWGEN_NEERABUP&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for NEWGEN_NEERABUP
Fetching power for facility NEVERSF...count no 354
Fetching power for facility NEWENSF...count no 355
Fetching power for facility NEWGEN_KWINANA...count no 356
⚠️ Failed to fetch power for NEWGEN_KWINANA: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=NEWGEN_KWINANA&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for NEWGEN_KWINANA
Fetching power for facility NEWPORT...count no 357
Fetching power for facility NBHWF...count no 358
Fetching power for facility NORTHAM_SF...count no 359
⚠️ Failed to fetch power for NORTHAM_SF: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=NORTHAM_SF&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for NORTHAM_SF
Fetching power for facility TESLA_NORTHAM...count no 360
⚠️ Failed to fetch power for TESLA_NORTHAM: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=TESLA_NORTHAM&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for TESLA_NORTHAM
Fetching power for facility NORTHGT...count no 361
⚠️ Failed to fetch power for NORTHGT: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=NORTHGT&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for NORTHGT
Fetching power for facility NORTHP...count no 362
⚠️ Failed to fetch power for NORTHP: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=NORTHP&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for NORTHP
Fetching power for facility NUMURKSF...count no 363
Fetching power for facility NYNGAN...count no 364
Fetching power for facility OAKEY...count no 365
Fetching power for facility OAKEY2SF...count no 366
Fetching power for facility OAKEY1SF...count no 367
Fetching power for facility OAKLAND...count no 368
Fetching power for facility OCPS...count no 369
⚠️ Failed to fetch power for OCPS: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=OCPS&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for OCPS
Fetching power for facility OAKY2...count no 370
⚠️ Failed to fetch power for OAKY2: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=OAKY2&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for OAKY2
Fetching power for facility 0ORANABESS...count no 371
⚠️ Failed to fetch power for 0ORANABESS: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=0ORANABESS&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for 0ORANABESS
Fetching power for facility OSBORNE...count no 372
Fetching power for facility PALOONA...count no 373
Fetching power for facility PSF...count no 374
Fetching power for facility PRK_AG...count no 375
⚠️ Failed to fetch power for PRK_AG: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=PRK_AG&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for PRK_AG
Fetching power for facility PEDLER...count no 376
⚠️ Failed to fetch power for PEDLER: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=PEDLER&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for PEDLER
Fetching power for facility NPPPPS...count no 377
Fetching power for facility PIBESS...count no 378
Fetching power for facility PHOENIX_KWINANA_WTE...count no 379
⚠️ Failed to fetch power for PHOENIX_KWINANA_WTE: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=PHOENIX_KWINANA_WTE&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for PHOENIX_KWINANA_WTE
Fetching power for facility TESLA_PICTON...count no 380
⚠️ Failed to fetch power for TESLA_PICTON: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=TESLA_PICTON&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for TESLA_PICTON
Fetching power for facility PINDARI...count no 381
⚠️ Failed to fetch power for PINDARI: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=PINDARI&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for PINDARI
Fetching power for facility PINJAR...count no 382
⚠️ Failed to fetch power for PINJAR: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=PINJAR&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for PINJAR
Fetching power for facility ALINTA_PNJ...count no 383
⚠️ Failed to fetch power for ALINTA_PNJ: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=ALINTA_PNJ&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for ALINTA_PNJ
Fetching power for facility PIONEER...count no 384
Fetching power for facility PLAYF...count no 385
⚠️ Failed to fetch power for PLAYF: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=PLAYF&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for PLAYF
Fetching power for facility PTINA...count no 386
Fetching power for facility PAREPW...count no 387
Fetching power for facility 0PLWF...count no 388
⚠️ Failed to fetch power for 0PLWF: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=0PLWF&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for 0PLWF
Fetching power for facility PORTLATT...count no 389
⚠️ Failed to fetch power for PORTLATT: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=PORTLATT&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for PORTLATT
Fetching power for facility PORTLCN...count no 390

Fetching power for facility STANVAC...count no 391
Fetching power for facility PORTWF...count no 392
Fetching power for facility QUARANTN...count no 393
Fetching power for facility QUERIVER...count no 394
⚠️ Failed to fetch power for QUERIVER: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=QUERIVER&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for QUERIVER
Fetching power for facility QBYNB...count no 395
Fetching power for facility QP...count no 396
⚠️ Failed to fetch power for QP: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=QP&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for QP
Fetching power for facility RACOMIL...count no 397
⚠️ Failed to fetch power for RACOMIL: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=RACOMIL&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for RACOMIL
Fetching power for facility RANGEB...count no 398
Fetching power for facility RED_HILL...count no 399
⚠️ Failed to fetch power for RED_HILL: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=RED_HILL&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for RED_HILL
Fetching power for facility REDBANK1...count no 400
⚠️ Failed to fetch power for REDBANK1: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=REDBANK1&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for REDBANK1
Fetching power for facility REECE...count no 401
Fetching power for facility REMOUNT...count no 402
⚠️ Failed to fetch power for REMOUNT: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=REMOUNT&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for REMOUNT
Fetching power for facility REPULSE...count no 403
Fetching power for facility BIOGAS01...count no 404
⚠️ Failed to fetch power for BIOGAS01: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=BIOGAS01&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for BIOGAS01
Fetching power for facility 0RIVERINASF...count no 405
⚠️ Failed to fetch power for 0RIVERINASF: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=0RIVERINASF&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for 0RIVERINASF
Fetching power for facility RESS...count no 406
Fetching power for facility RIVNB...count no 407
Fetching power for facility ROCHEDAL...count no 408
⚠️ Failed to fetch power for ROCHEDAL: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=ROCHEDAL&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for ROCHEDAL
Fetching power for facility ROCKINGHAM...count no 409
⚠️ Failed to fetch power for ROCKINGHAM: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=ROCKINGHAM&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for ROCKINGHAM
Fetching power for facility RPCG...count no 410
Fetching power for facility EDLRGNRD...count no 411
⚠️ Failed to fetch power for EDLRGNRD: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=EDLRGNRD&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for EDLRGNRD
Fetching power for facility ROMA...count no 412
Fetching power for facility RRSF...count no 413
Fetching power for facility ROWALLAN...count no 414
Fetching power for facility ROYALLA...count no 415
Fetching power for facility RUBICON...count no 416
Fetching power for facility RUGBYR...count no 417
Fetching power for facility RYANCWF...count no 418
Fetching power for facility RYEPARK...count no 419
Fetching power for facility SALTCRK...count no 420
Fetching power for facility SAPHWF1...count no 421
Fetching power for facility SEBSF...count no 422
Fetching power for facility SHEP1...count no 423
⚠️ Failed to fetch power for SHEP1: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=SHEP1&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for SHEP1
Fetching power for facility SHOALHAV...count no 424
Fetching power for facility SHOAL...count no 425
Fetching power for facility STWF...count no 426
Fetching power for facility SITHE...count no 427
Fetching power for facility SMTHBES1...count no 428
Fetching power for facility SNAPPER...count no 429
Fetching power for facility SNOWTOWN...count no 430
Fetching power for facility SNOWNTH...count no 431
Fetching power for facility SNOWSTH...count no 432
Fetching power for facility SNOWY4...count no 433
⚠️ Failed to fetch power for SNOWY4: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=SNOWY4&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for SNOWY4
Fetching power for facility SNOWY5...count no 434
⚠️ Failed to fetch power for SNOWY5: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=SNOWY5&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for SNOWY5
Fetching power for facility 0SNOWY20...count no 435
⚠️ Failed to fetch power for 0SNOWY20: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=0SNOWY20&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for 0SNOWY20
Fetching power for facility SNUG...count no 436
Fetching power for facility AGLSOM...count no 437
Fetching power for facility SOUTH_CARDUP...count no 438
⚠️ Failed to fetch power for SOUTH_CARDUP: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=SOUTH_CARDUP&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for SOUTH_CARDUP
Fetching power for facility SKSF...count no 439
⚠️ Failed to fetch power for SKSF: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=SKSF&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for SKSF
Fetching power for facility STHBKTEC...count no 440
⚠️ Failed to fetch power for STHBKTEC: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=STHBKTEC&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for STHBKTEC
Fetching power for facility SVALE...count no 441
⚠️ Failed to fetch power for SVALE: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=SVALE&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for SVALE
Fetching power for facility STGEORGE...count no 442
⚠️ Failed to fetch power for STGEORGE: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=STGEORGE&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for STGEORGE
Fetching power for facility SLDCBLK...count no 443

⚠️ Failed to fetch power for SLDCBLK: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=SLDCBLK&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for SLDCBLK
Fetching power for facility 0STANBESS...count no 444
⚠️ Failed to fetch power for 0STANBESS: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=0STANBESS&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for 0STANBESS
Fetching power for facility STANWELL...count no 445
Fetching power for facility STAPYLTON...count no 446
⚠️ Failed to fetch power for STAPYLTON: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=STAPYLTON&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for STAPYLTON
Fetching power for facility STARFHILL...count no 447
Fetching power for facility STOCKYD...count no 448
Fetching power for facility STUBSF...count no 449
Fetching power for facility 0SUMMFBESS...count no 450
⚠️ Failed to fetch power for 0SUMMFBESS: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=0SUMMFBESS&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for 0SUMMFBESS
Fetching power for facility SMCSF...count no 451
Fetching power for facility SUNCOAST...count no 452
⚠️ Failed to fetch power for SUNCOAST: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=SUNCOAST&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for SUNCOAST
Fetching power for facility SUNRSF1...count no 453
Fetching power for facility VALDORA...count no 454
⚠️ Failed to fetch power for VALDORA: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=VALDORA&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for VALDORA
Fetching power for facility SUNTPSF...count no 455
Fetching power for facility SNB1...count no 456
Fetching power for facility 0SUPERNODE2...count no 457
⚠️ Failed to fetch power for 0SUPERNODE2: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=0SUPERNODE2&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for 0SUPERNODE2
Fetching power for facility SRSF...count no 458
Fetching power for facility 0SWANBBESS...count no 459
⚠️ Failed to fetch power for 0SWANBBESS: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=0SWANBBESS&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for 0SWANBBESS
Fetching power for facility SWAN_B...count no 460
⚠️ Failed to fetch power for SWAN_B: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=SWAN_B&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for SWAN_B
Fetching power for facility SWAN_E...count no 461
Fetching power for facility TABMILL2...count no 462
⚠️ Failed to fetch power for TABMILL2: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=TABMILL2&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for TABMILL2
Fetching power for facility TAHMOOR...count no 463
⚠️ Failed to fetch power for TAHMOOR: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=TAHMOOR&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for TAHMOOR
Fetching power for facility TBSF...count no 464
Fetching power for facility TB2SF...count no 465
Fetching power for facility TALLAWAR...count no 466
Fetching power for facility TALWB...count no 467
Fetching power for facility TAMALA_PARK...count no 468
⚠️ Failed to fetch power for TAMALA_PARK: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=TAMALA_PARK&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for TAMALA_PARK
Fetching power for facility TVCCPS...count no 469
Fetching power for facility TARALGA...count no 470
Fetching power for facility 0TARONGBESS...count no 471
Fetching power for facility TARONG...count no 472
Fetching power for facility TARONGN...count no 473
Fetching power for facility TARRALEA...count no 474
Fetching power for facility TATIARA...count no 475
⚠️ Failed to fetch power for TATIARA: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=TATIARA&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for TATIARA
Fetching power for facility TATURA...count no 476
⚠️ Failed to fetch power for TATURA: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=TATURA&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for TATURA
Fetching power for facility TEATREE...count no 477
⚠️ Failed to fetch power for TEATREE: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=TEATREE&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for TEATREE
Fetching power for facility TEMPB...count no 478
Fetching power for facility SATGN...count no 479
⚠️ Failed to fetch power for SATGN: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=SATGN&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for SATGN
Fetching power for facility SATGS...count no 480
⚠️ Failed to fetch power for SATGS: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=SATGS&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for SATGS
Fetching power for facility TERALBA...count no 481
⚠️ Failed to fetch power for TERALBA: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=TERALBA&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for TERALBA
Fetching power for facility 0TERANGBESS...count no 482
⚠️ Failed to fetch power for 0TERANGBESS: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=0TERANGBESS&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for 0TERANGBESS
Fetching power for facility TERMSTOR...count no 483
⚠️ Failed to fetch power for TERMSTOR: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=TERMSTOR&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for TERMSTOR
Fetching power for facility BLUFF...count no 484
Fetching power for facility THEDROP...count no 485
⚠️ Failed to fetch power for THEDROP: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=THEDROP&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for THEDROP
Fetching power for facility 0TILBSF...count no 486

⚠️ Failed to fetch power for 0TILBSF: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=0TILBSF&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for 0TILBSF
Fetching power for facility TIMWEST...count no 487
⚠️ Failed to fetch power for TIMWEST: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=TIMWEST&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for TIMWEST
Fetching power for facility 0TOMAGOBESS...count no 488
⚠️ Failed to fetch power for 0TOMAGOBESS: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=0TOMAGOBESS&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for 0TOMAGOBESS
Fetching power for facility TOORAWF...count no 489
⚠️ Failed to fetch power for TOORAWF: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=TOORAWF&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for TOORAWF
Fetching power for facility TIB...count no 490
Fetching power for facility TORRIS...count no 491
Fetching power for facility TOWER...count no 492
⚠️ Failed to fetch power for TOWER: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=TOWER&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for TOWER
Fetching power for facility YABULU...count no 493
Fetching power for facility TGNSS...count no 494
⚠️ Failed to fetch power for TGNSS: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=TGNSS&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for TGNSS
Fetching power for facility TREVALLN...count no 495
Fetching power for facility TRIBUTE...count no 496
Fetching power for facility TULLYSM...count no 497
Fetching power for facility SNOWY2...count no 498
Fetching power for facility TUMUT3...count no 499
Fetching power for facility TUNGATIN...count no 500
Fetching power for facility ULBESS...count no 501
Fetching power for facility URANQ...count no 502
Fetching power for facility 0UUNGULAWF...count no 503
⚠️ Failed to fetch power for 0UUNGULAWF: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=0UUNGULAWF&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for 0UUNGULAWF
Fetching power for facility VP...count no 504
Fetching power for facility VPGS...count no 505
Fetching power for facility TITREE...count no 506
⚠️ Failed to fetch power for TITREE: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=TITREE&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for TITREE
Fetching power for facility VICMILL...count no 507
⚠️ Failed to fetch power for VICMILL: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=VICMILL&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for VICMILL
Fetching power for facility VBB...count no 508
Fetching power for facility 0WAGERUP_BESS...count no 509
⚠️ Failed to fetch power for 0WAGERUP_BESS: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=0WAGERUP_BESS&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for 0WAGERUP_BESS
Fetching power for facility ALCOA_WGP...count no 510
⚠️ Failed to fetch power for ALCOA_WGP: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=ALCOA_WGP&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for ALCOA_WGP
Fetching power for facility WAGGNSF...count no 511
Fetching power for facility ALINTA_WWF...count no 512
⚠️ Failed to fetch power for ALINTA_WWF: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=ALINTA_WWF&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for ALINTA_WWF
Fetching power for facility WLWLSF...count no 513
Fetching power for facility WW...count no 514
⚠️ Failed to fetch power for WW: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=WW&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for WW
Fetching power for facility WALGRV...count no 515
Fetching power for facility PRDSO_WALPOLE...count no 516
⚠️ Failed to fetch power for PRDSO_WALPOLE: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=PRDSO_WALPOLE&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for PRDSO_WALPOLE
Fetching power for facility 0WAMBOWF...count no 517
Fetching power for facility WANDSF...count no 518
Fetching power for facility WANDBG...count no 519
Fetching power for facility WNSF...count no 520
Fetching power for facility WTAHB...count no 521
Fetching power for facility WARRADARGE...count no 522
⚠️ Failed to fetch power for WARRADARGE: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=WARRADARGE&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for WARRADARGE
Fetching power for facility WG...count no 523
⚠️ Failed to fetch power for WG: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=WG&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for WG
Fetching power for facility WARWSF...count no 524
Fetching power for facility WATERLWF...count no 525
Fetching power for facility WPWF...count no 526
Fetching power for facility WAUBRAWF...count no 527
Fetching power for facility WELLSF1...count no 528
Fetching power for facility WELNSF...count no 529
Fetching power for facility WEMENSF1...count no 530
Fetching power for facility BLAIRFOX_WESTHILLS...count no 531
⚠️ Failed to fetch power for BLAIRFOX_WESTHILLS: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=BLAIRFOX_WESTHILLS&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for BLAIRFOX_WESTHILLS
Fetching power for facility WESTILLA...count no 532
⚠️ Failed to fetch power for WESTILLA: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=WESTILLA&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for WESTILLA
Fetching power for facility WEST_KALGOORLIE...count no 533
⚠️ Failed to fetch power for WEST_KALGOORLIE: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=WEST_KALGOORLIE&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for WEST_KALGOORLIE
Fetching power for facility WKIEWA...count no 534
Fetching power for facility AGLNOW1...count no 535
⚠️ Failed to fetch power for AGLNOW1: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=AGLNOW1&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for AGLNOW1
Fetching power for facility WSTWYSF...count no 536

Fetching power for facility WDBESS...count no 537
Fetching power for facility WDGPH...count no 538
Fetching power for facility WDBESS2...count no 539
Fetching power for facility WESTCBT...count no 540
⚠️ Failed to fetch power for WESTCBT: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=WESTCBT&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for WESTCBT
Fetching power for facility WRSF1...count no 541
Fetching power for facility WRWF1...count no 542
Fetching power for facility WHITSF...count no 543
Fetching power for facility WHIT1...count no 544
⚠️ Failed to fetch power for WHIT1: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=WHIT1&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for WHIT1
Fetching power for facility WILGAPK...count no 545
⚠️ Failed to fetch power for WILGAPK: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=WILGAPK&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for WILGAPK
Fetching power for facility WILGAPKB...count no 546
⚠️ Failed to fetch power for WILGAPKB: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=WILGAPKB&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for WILGAPKB
Fetching power for facility WILLHOV...count no 547
⚠️ Failed to fetch power for WILLHOV: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=WILLHOV&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for WILLHOV
Fetching power for facility 0WDBESS...count no 548
⚠️ Failed to fetch power for 0WDBESS: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=0WDBESS&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for 0WDBESS
Fetching power for facility WGWF...count no 549
Fetching power for facility NINEWIL...count no 550
⚠️ Failed to fetch power for NINEWIL: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=NINEWIL&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for NINEWIL
Fetching power for facility WINDHILL...count no 551
⚠️ Failed to fetch power for WINDHILL: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=WINDHILL&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for WINDHILL
Fetching power for facility WINGF1...count no 552
⚠️ Failed to fetch power for WINGF1: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=WINGF1&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for WINGF1
Fetching power for facility WINGF2...count no 553
⚠️ Failed to fetch power for WINGF2: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=WINGF2&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for WINGF2
Fetching power for facility WINTSF1...count no 554
Fetching power for facility WIVENHOE...count no 555
Fetching power for facility WIVENSH...count no 556
⚠️ Failed to fetch power for WIVENSH: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=WIVENSH&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for WIVENSH
Fetching power for facility WOLARSF...count no 557
Fetching power for facility WOLLERT...count no 558
⚠️ Failed to fetch power for WOLLERT: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=WOLLERT&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for WOLLERT
Fetching power for facility WONWP...count no 559
⚠️ Failed to fetch power for WONWP: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=WONWP&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for WONWP
Fetching power for facility WDLNGN...count no 560
⚠️ Failed to fetch power for WDLNGN: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=WDLNGN&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for WDLNGN
Fetching power for facility WOODLWN...count no 561
Fetching power for facility WOOLNTH1...count no 562
Fetching power for facility WOOLGSF...count no 563
Fetching power for facility 0WOORBESS...count no 564
⚠️ Failed to fetch power for 0WOORBESS: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=0WOORBESS&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for 0WOORBESS
Fetching power for facility WOYWOY...count no 565
⚠️ Failed to fetch power for WOYWOY: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=WOYWOY&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for WOYWOY
Fetching power for facility WUNUSF...count no 566
Fetching power for facility WYASF...count no 567
Fetching power for facility WYANGALA...count no 568
⚠️ Failed to fetch power for WYANGALA: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=WYANGALA&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for WYANGALA
Fetching power for facility WYANGALB...count no 569
⚠️ Failed to fetch power for WYANGALB: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=WYANGALB&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for WYANGALB
Fetching power for facility WYNDW...count no 570
⚠️ Failed to fetch power for WYNDW: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=WYNDW&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for WYNDW
Fetching power for facility YALLOURN...count no 571
Fetching power for facility YSWF...count no 572
Fetching power for facility YAMBUK...count no 573
Fetching power for facility YANDIN...count no 574
⚠️ Failed to fetch power for YANDIN: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=YANDIN&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for YANDIN
Fetching power for facility YARANSF...count no 575
Fetching power for facility YWNGAHYD...count no 576
⚠️ Failed to fetch power for YWNGAHYD: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=YWNGAHYD&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for YWNGAHYD
Fetching power for facility YARWUN...count no 577
Fetching power for facility YATSF1...count no 578
Fetching power for facility YAWWF...count no 579
⚠️ Failed to fetch power for YAWWF: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=power&interval=5m&facility_code=YAWWF&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for YAWWF
Fetching power for facility YENDONWF...count no 580

### 1.2.2. PER-FACILITY CO2 EMISSIONS (5 min interval)

fetches 5-minute interval emnission data for every facility in the NEM network.

In [51]:
#Fetches 5-minute emissions data for a single facility and returns a flattened DataFrame.
def fetch_facility_emissions(facility_id: str, start: datetime, end: datetime) -> pd.DataFrame:
    """Fetch 5-minute emissions data for a single facility and flatten it."""
    url = f"{BASE_URL}/data/facilities/NEM"
    # Passing Parameters
    params = {
        "metrics": ["emissions"],
        "interval": INTERVAL,
        "facility_code": facility_id,
        "date_start": START_DATE,
        "date_end": END_DATE,
    }

    # Make request and safely handle connection / API issues
    try:
        r = requests.get(url, headers=HEADERS, params=params)
        r.raise_for_status()
        json_data = r.json()
    except Exception as e:
        print(f" Failed to fetch emissions for {facility_id}: {e}")
        return pd.DataFrame()

    # Check API success flag
    if not json_data.get("success", False):
        print(f" API returned failure for {facility_id}: {json_data.get('error')}")
        return pd.DataFrame()

    data = json_data.get("data", [])
    rows = []

    # Flatten nested structure
    for entry in data:
        unit_code = entry.get("unit", "tCO2e")  # adjusted unit label
        for res in entry.get("results", []):
            for point in res.get("data", []):
                timestamp, value = point
                rows.append({
                    "facility_id": facility_id,
                    "unit_code": unit_code,
                    "timestamp": timestamp,
                    "emission": value
                })

    return pd.DataFrame(rows)


print(f"IN PROGRESS Fetching emissions for {len(facility_ids)} facilities...")

all_emissions = []

# Step 2: Iterate over facilities
count = 1
for facility_id in facility_ids:
    print(f"Fetching emissions for facility {facility_id}... count no {count}")
    count += 1
    emissions_df = fetch_facility_emissions(facility_id, START_DATE, END_DATE)
    if emissions_df.empty:
        print(f" No data for {facility_id}")
    all_emissions.append(emissions_df)
    time.sleep(REQUEST_DELAY)

# Step 3: Combine all facilities
emissions_df_raw = pd.concat(all_emissions, ignore_index=True)

IN PROGRESS Fetching emissions for 580 facilities...
Fetching emissions for facility ADP... count no 1
Fetching emissions for facility ALBANY... count no 2
⚠️ Failed to fetch emissions for ALBANY: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=ALBANY&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for ALBANY
Fetching emissions for facility ALDGASF... count no 3
Fetching emissions for facility AMCORGR... count no 4
⚠️ Failed to fetch emissions for AMCORGR: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=AMCORGR&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for AMCORGR
Fetching emissions for facility ANGASTON... count no 5
Fetching emissions for facility APS... count no 6
⚠️ Failed to fetch emissions for APS: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=APS&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for APS
Fetching emissions for facility APPIN... count no 7
⚠️ Failed to fetch emissions for APPIN: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=APPIN&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for APPIN
Fetching emissions for facility ARWF... count no 8
Fetching emissions for facility AVLSF... count no 9
Fetching emissions for facility AWABAREF... count no 10
⚠️ Failed to fetch emissions for AWABAREF: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=AWABAREF&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for AWABAREF
Fetching emissions for facility BADGINGARRA... count no 11
⚠️ Failed to fetch emissions for BADGINGARRA: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=BADGINGARRA&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for BADGINGARRA
Fetching emissions for facility DEIBDL... count no 12
Fetching emissions for facility BAKING... count no 13
⚠️ Failed to fetch emissions for BAKING: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=BAKING&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for BAKING
Fetching emissions for facility BHWF... count no 14
Fetching emissions for facility BALBESS... count no 15
Fetching emissions for facility BBASEHOS... count no 16
⚠️ Failed to fetch emissions for BBASEHOS: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=BBASEHOS&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for BBASEHOS
Fetching emissions for facility BANGOWF... count no 17
Fetching emissions for facility BAPS... count no 18
⚠️ Failed to fetch emissions for BAPS: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=BAPS&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for BAPS
Fetching emissions for facility BANKSPT... count no 19
⚠️ Failed to fetch emissions for BANKSPT: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=BANKSPT&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for BANKSPT
Fetching emissions for facility BANNSP... count no 20
Fetching emissions for facility BARCALDN... count no 21
Fetching emissions for facility BARCSF... count no 22
Fetching emissions for facility BARKIPS... count no 23
Fetching emissions for facility BARRON... count no 24
Fetching emissions for facility BASTYAN... count no 25
Fetching emissions for facility BAYSW... count no 26
Fetching emissions for facility BBDISEL1... count no 27
⚠️ Failed to fetch emissions for BBDISEL1: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=BBDISEL1&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for BBDISEL1
Fetching emissions for facility BELLBAY... count no 28
⚠️ Failed to fetch emissions for BELLBAY: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=BELLBAY&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for BELLBAY
Fetching emissions for facility BBP31... count no 29
Fetching emissions for facility BLAIRFOX_BEROSRD_WF... count no 30
⚠️ Failed to fetch emissions for BLAIRFOX_BEROSRD_WF: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=BLAIRFOX_BEROSRD_WF&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for BLAIRFOX_BEROSRD_WF
Fetching emissions for facility BRYB1WF1... count no 31
Fetching emissions for facility BERWICK... count no 32
⚠️ Failed to fetch emissions for BERWICK: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=BERWICK&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for BERWICK
Fetching emissions for facility BERYLSF... count no 33
Fetching emissions for facility BIALAWF... count no 34
Fetching emissions for facility BLAYNEY... count no 35
⚠️ Failed to fetch emissions for BLAYNEY: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=BLAYNEY&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for BLAYNEY
Fetching emissions for facility SNOWY6... count no 36
Fetching emissions for facility BLUEGSF... count no 37
Fetching emissions for facility BLULAKE... count no 38
⚠️ Failed to fetch emissions for BLULAKE: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=BLULAKE&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for BLULAKE
Fetching emissions for facility BLUEWATERS... count no 39
⚠️ Failed to fetch emissions for BLUEWATERS: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=BLUEWATERS&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for BLUEWATERS
Fetching emissions for facility BLYTHB... count no 40
Fetching emissions for facility BOCOROCK... count no 41
Fetching emissions for facility BODWF... count no 42
Fetching emissions for facility MCKAY... count no 43
Fetching emissions for facility BOLIVAR... count no 44
Fetching emissions for facility BOLIVPS... count no 45
Fetching emissions for facility BOMENSF... count no 46
Fetching emissions for facility 0BCWF... count no 47
⚠️ Failed to fetch emissions for 0BCWF: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=0BCWF&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for 0BCWF
Fetching emissions for facility BBATTERY... count no 48
Fetching emissions for facility BRAEMARA... count no 49
Fetching emissions for facility B2PS... count no 50
Fetching emissions for facility BREMER_BAY... count no 51
⚠️ Failed to fetch emissions for BREMER_BAY: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=BREMER_BAY&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for BREMER_BAY
Fetching emissions for facility BRNDBES... count no 52

Fetching emissions for facility BROADMDW... count no 53
⚠️ Failed to fetch emissions for BROADMDW: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=BROADMDW&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for BROADMDW
Fetching emissions for facility 0BSSF... count no 54
⚠️ Failed to fetch emissions for 0BSSF: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=0BSSF&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for 0BSSF
Fetching emissions for facility BWTR1... count no 55
Fetching emissions for facility BHILLGT... count no 56
Fetching emissions for facility BROKENH... count no 57
Fetching emissions for facility BHB... count no 58
Fetching emissions for facility BROOKLYN... count no 59
⚠️ Failed to fetch emissions for BROOKLYN: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=BROOKLYN&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for BROOKLYN
Fetching emissions for facility BROWNMT... count no 60
⚠️ Failed to fetch emissions for BROWNMT: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=BROWNMT&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for BROWNMT
Fetching emissions for facility BPLANDF... count no 61
⚠️ Failed to fetch emissions for BPLANDF: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=BPLANDF&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for BPLANDF
Fetching emissions for facility 0WELLINGTONBESS... count no 62
⚠️ Failed to fetch emissions for 0WELLINGTONBESS: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=0WELLINGTONBESS&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for 0WELLINGTONBESS
Fetching emissions for facility BULGANA... count no 63
Fetching emissions for facility 0BUNDSF... count no 64
⚠️ Failed to fetch emissions for 0BUNDSF: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=0BUNDSF&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for 0BUNDSF
Fetching emissions for facility BNGSF1... count no 65
Fetching emissions for facility BNGSF2... count no 66
Fetching emissions for facility 0BUNGAMA... count no 67
⚠️ Failed to fetch emissions for 0BUNGAMA: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=0BUNGAMA&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for 0BUNGAMA
Fetching emissions for facility BDONGHYD... count no 68
⚠️ Failed to fetch emissions for BDONGHYD: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=BDONGHYD&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for BDONGHYD
Fetching emissions for facility BURRIN... count no 69
⚠️ Failed to fetch emissions for BURRIN: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=BURRIN&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for BURRIN
Fetching emissions for facility BUTLERSG... count no 70
Fetching emissions for facility 0CALBESS1... count no 71
⚠️ Failed to fetch emissions for 0CALBESS1: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=0CALBESS1&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for 0CALBESS1
Fetching emissions for facility 0CALBESS2... count no 72
⚠️ Failed to fetch emissions for 0CALBESS2: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=0CALBESS2&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for 0CALBESS2
Fetching emissions for facility CALL_A... count no 73
⚠️ Failed to fetch emissions for CALL_A: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=CALL_A&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for CALL_A
Fetching emissions for facility CALL_B... count no 74
Fetching emissions for facility CALLIDEC1... count no 75
Fetching emissions for facility CANUNDA1... count no 76
⚠️ Failed to fetch emissions for CANUNDA1: 502 Server Error: Bad Gateway for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=CANUNDA1&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for CANUNDA1
Fetching emissions for facility CAPBES... count no 77
Fetching emissions for facility CAPTL_WF... count no 78
Fetching emissions for facility CESF... count no 79
⚠️ Failed to fetch emissions for CESF: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=CESF&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for CESF
Fetching emissions for facility LI_WY_CA... count no 80
Fetching emissions for facility CATHROCK... count no 81
Fetching emissions for facility CTHLWF... count no 82
Fetching emissions for facility CETHANA... count no 83
Fetching emissions for facility CHALLWF... count no 84
Fetching emissions for facility CHPSTWF... count no 85
⚠️ Failed to fetch emissions for CHPSTWF: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=CHPSTWF&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for CHPSTWF
Fetching emissions for facility CHYTWF... count no 86
Fetching emissions for facility CHILDSF... count no 87
Fetching emissions for facility CHBESS... count no 88
Fetching emissions for facility CBWWBA... count no 89
Fetching emissions for facility CLARESF... count no 90
Fetching emissions for facility CLRKCWF... count no 91
Fetching emissions for facility CLAYTON... count no 92
⚠️ Failed to fetch emissions for CLAYTON: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=CLAYTON&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for CLAYTON
Fetching emissions for facility CLEMGPWF... count no 93
Fetching emissions for facility CLERMSF... count no 94
Fetching emissions for facility CLOVER... count no 95
Fetching emissions for facility CLUNY... count no 96
Fetching emissions for facility COCKBURN... count no 97
⚠️ Failed to fetch emissions for COCKBURN: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=COCKBURN&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for COCKBURN
Fetching emissions for facility CODRGTON... count no 98
⚠️ Failed to fetch emissions for CODRGTON: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=CODRGTON&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for CODRGTON
Fetching emissions for facility COHUNSF1... count no 99
Fetching emissions for facility COLEASF... count no 100

Fetching emissions for facility COLWF01... count no 101
Fetching emissions for facility INVESTEC_COLLGAR... count no 102
⚠️ Failed to fetch emissions for INVESTEC_COLLGAR: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=INVESTEC_COLLGAR&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for INVESTEC_COLLGAR
Fetching emissions for facility COLLIE... count no 103
⚠️ Failed to fetch emissions for COLLIE: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=COLLIE&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for COLLIE
Fetching emissions for facility COLLIE_ESR4... count no 104
⚠️ Failed to fetch emissions for COLLIE_ESR4: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=COLLIE_ESR4&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for COLLIE_ESR4
Fetching emissions for facility COLLIE_ESR... count no 105
⚠️ Failed to fetch emissions for COLLIE_ESR: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=COLLIE_ESR&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for COLLIE_ESR
Fetching emissions for facility COLLIE_BESS2... count no 106
⚠️ Failed to fetch emissions for COLLIE_BESS2: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=COLLIE_BESS2&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for COLLIE_BESS2
Fetching emissions for facility COLNSV... count no 107
⚠️ Failed to fetch emissions for COLNSV: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=COLNSV&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for COLNSV
Fetching emissions for facility CSPVPS... count no 108
Fetching emissions for facility COLONGRA... count no 109
Fetching emissions for facility COLUMSF... count no 110
Fetching emissions for facility CPSA... count no 111
Fetching emissions for facility CONDONG1... count no 112
Fetching emissions for facility CBWF... count no 113
⚠️ Failed to fetch emissions for CBWF: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=CBWF&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for CBWF
Fetching emissions for facility COOPGWF... count no 114
Fetching emissions for facility COPTNHYD... count no 115
⚠️ Failed to fetch emissions for COPTNHYD: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=COPTNHYD&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for COPTNHYD
Fetching emissions for facility CORIO... count no 116
⚠️ Failed to fetch emissions for CORIO: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=CORIO&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for CORIO
Fetching emissions for facility CRWASF1... count no 117
Fetching emissions for facility CROOKWEL... count no 118
⚠️ Failed to fetch emissions for CROOKWEL: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=CROOKWEL&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for CROOKWEL
Fetching emissions for facility CROOKWF2... count no 119
Fetching emissions for facility CROOKWF3... count no 120
Fetching emissions for facility CROWLWF... count no 121
Fetching emissions for facility CRURWF1... count no 122
Fetching emissions for facility CULCSF... count no 123
Fetching emissions for facility CULLERIN... count no 124
Fetching emissions for facility SBSOLAR1_CUNDERDIN_PV... count no 125
⚠️ Failed to fetch emissions for SBSOLAR1_CUNDERDIN_PV: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=SBSOLAR1_CUNDERDIN_PV&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for SBSOLAR1_CUNDERDIN_PV
Fetching emissions for facility DAANDINE... count no 126
⚠️ Failed to fetch emissions for DAANDINE: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=DAANDINE&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for DAANDINE
Fetching emissions for facility DALNTH... count no 127
Fetching emissions for facility DDPS1... count no 128
Fetching emissions for facility DDSF... count no 129
Fetching emissions for facility DARLSF... count no 130
Fetching emissions for facility DPNTB... count no 131
Fetching emissions for facility DARTM... count no 132
Fetching emissions for facility DAYDSF... count no 133
Fetching emissions for facility DCWL_DENMARK... count no 134
⚠️ Failed to fetch emissions for DCWL_DENMARK: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=DCWL_DENMARK&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for DCWL_DENMARK
Fetching emissions for facility DEVILS_G... count no 135
Fetching emissions for facility DIAPURWF... count no 136
Fetching emissions for facility DRYCGT... count no 137
Fetching emissions for facility DULAWF... count no 138
Fetching emissions for facility DUNDWF... count no 139
Fetching emissions for facility PMATTAEP... count no 140
⚠️ Failed to fetch emissions for PMATTAEP: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=PMATTAEP&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for PMATTAEP
Fetching emissions for facility EASTCRK... count no 141
⚠️ Failed to fetch emissions for EASTCRK: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=EASTCRK&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for EASTCRK
Fetching emissions for facility EASTCRK2... count no 142
⚠️ Failed to fetch emissions for EASTCRK2: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=EASTCRK2&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for EASTCRK2
Fetching emissions for facility EDENVSF... count no 143
Fetching emissions for facility EILDON... count no 144
Fetching emissions for facility EILDONPD... count no 145
⚠️ Failed to fetch emissions for EILDONPD: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=EILDONPD&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for EILDONPD
Fetching emissions for facility ELAINEWF... count no 146
Fetching emissions for facility EMERASF... count no 147
Fetching emissions for facility EDWFMAN... count no 148
⚠️ Failed to fetch emissions for EDWFMAN: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=EDWFMAN&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for EDWFMAN
Fetching emissions for facility ENERGYB... count no 149
⚠️ Failed to fetch emissions for ENERGYB: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=ENERGYB&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for ENERGYB
Fetching emissions for facility ERARING... count no 150

Fetching emissions for facility ERB... count no 151
Fetching emissions for facility ERGT01... count no 152
Fetching emissions for facility 0ERB2... count no 153
⚠️ Failed to fetch emissions for 0ERB2: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=0ERB2&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for 0ERB2
Fetching emissions for facility FWF... count no 154
⚠️ Failed to fetch emissions for FWF: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=FWF&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for FWF
Fetching emissions for facility FINLEYSF... count no 155
Fetching emissions for facility FISHER... count no 156
Fetching emissions for facility FLATROCKS... count no 157
⚠️ Failed to fetch emissions for FLATROCKS: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=FLATROCKS&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for FLATROCKS
Fetching emissions for facility FLYCRKWF... count no 158
Fetching emissions for facility 0FULHAMSF... count no 159
⚠️ Failed to fetch emissions for 0FULHAMSF: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=0FULHAMSF&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for 0FULHAMSF
Fetching emissions for facility GANGARR... count no 160
Fetching emissions for facility GANNBESS... count no 161
Fetching emissions for facility GANNSF... count no 162
Fetching emissions for facility GEORGTWN... count no 163
⚠️ Failed to fetch emissions for GEORGTWN: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=GEORGTWN&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for GEORGTWN
Fetching emissions for facility TESLA_GERALDTON... count no 164
⚠️ Failed to fetch emissions for TESLA_GERALDTON: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=TESLA_GERALDTON&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for TESLA_GERALDTON
Fetching emissions for facility GERMCRK... count no 165
Fetching emissions for facility GIRGSF... count no 166
Fetching emissions for facility GSTONE... count no 167
Fetching emissions for facility GLBWNHYD... count no 168
⚠️ Failed to fetch emissions for GLBWNHYD: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=GLBWNHYD&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for GLBWNHYD
Fetching emissions for facility 0GLENELLEN... count no 169
⚠️ Failed to fetch emissions for 0GLENELLEN: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=0GLENELLEN&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for 0GLENELLEN
Fetching emissions for facility GLENMAGG... count no 170
⚠️ Failed to fetch emissions for GLENMAGG: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=GLENMAGG&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for GLENMAGG
Fetching emissions for facility GLENNCRK... count no 171
⚠️ Failed to fetch emissions for GLENNCRK: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=GLENNCRK&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for GLENNCRK
Fetching emissions for facility GLENSF... count no 172
Fetching emissions for facility GLRWNSF... count no 173
Fetching emissions for facility 0GNARWARREBESS... count no 174
⚠️ Failed to fetch emissions for 0GNARWARREBESS: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=0GNARWARREBESS&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for 0GNARWARREBESS
Fetching emissions for facility GPWFEST... count no 175
Fetching emissions for facility 0GPWFWST... count no 176
⚠️ Failed to fetch emissions for 0GPWFWST: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=0GPWFWST&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for 0GPWFWST
Fetching emissions for facility GOONUMSF... count no 177
Fetching emissions for facility 0GOORESF... count no 178
⚠️ Failed to fetch emissions for 0GOORESF: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=0GOORESF&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for 0GOORESF
Fetching emissions for facility GORDON... count no 179
Fetching emissions for facility GOSNELLS... count no 180
⚠️ Failed to fetch emissions for GOSNELLS: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=GOSNELLS&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for GOSNELLS
Fetching emissions for facility 0GRIVSF... count no 181
⚠️ Failed to fetch emissions for 0GRIVSF: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=0GRIVSF&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for 0GRIVSF
Fetching emissions for facility GSWF... count no 182
Fetching emissions for facility GRANGEAV... count no 183
⚠️ Failed to fetch emissions for GRANGEAV: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=GRANGEAV&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for GRANGEAV
Fetching emissions for facility GRANWF... count no 184
Fetching emissions for facility GRASMERE... count no 185
⚠️ Failed to fetch emissions for GRASMERE: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=GRASMERE&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for GRASMERE
Fetching emissions for facility GREENB... count no 186
Fetching emissions for facility GREENOUGH_RIVER... count no 187
⚠️ Failed to fetch emissions for GREENOUGH_RIVER: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=GREENOUGH_RIVER&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for GREENOUGH_RIVER
Fetching emissions for facility GRIFSF... count no 188
Fetching emissions for facility GROSV1... count no 189
⚠️ Failed to fetch emissions for GROSV1: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=GROSV1&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for GROSV1
Fetching emissions for facility GROSV2... count no 190
⚠️ Failed to fetch emissions for GROSV2: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=GROSV2&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for GROSV2
Fetching emissions for facility GULLRGWF... count no 191

Fetching emissions for facility GNNDHSF... count no 192
Fetching emissions for facility GUNNING... count no 193
Fetching emissions for facility 0GUNSYNDSF... count no 194
⚠️ Failed to fetch emissions for 0GUNSYNDSF: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=0GUNSYNDSF&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for 0GUNSYNDSF
Fetching emissions for facility SNOWY3... count no 195
Fetching emissions for facility HLMSEW01... count no 196
⚠️ Failed to fetch emissions for HLMSEW01: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=HLMSEW01&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for HLMSEW01
Fetching emissions for facility HALAMRD... count no 197
⚠️ Failed to fetch emissions for HALAMRD: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=HALAMRD&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for HALAMRD
Fetching emissions for facility AGLHAL... count no 198
Fetching emissions for facility HALLWF... count no 199
Fetching emissions for facility HALLWF2... count no 200
Fetching emissions for facility HAMISF... count no 201
Fetching emissions for facility HAMPTON... count no 202
⚠️ Failed to fetch emissions for HAMPTON: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=HAMPTON&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for HAMPTON
Fetching emissions for facility HVWW... count no 203
Fetching emissions for facility HASTING... count no 204
⚠️ Failed to fetch emissions for HASTING: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=HASTING&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for HASTING
Fetching emissions for facility HAUGHT1... count no 205
Fetching emissions for facility HD1WF... count no 206
Fetching emissions for facility HAYMSF... count no 207
Fetching emissions for facility HAZEL... count no 208
⚠️ Failed to fetch emissions for HAZEL: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=HAZEL&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for HAZEL
Fetching emissions for facility HBESS... count no 209
Fetching emissions for facility HENDERSON_RENEWABLE... count no 210
⚠️ Failed to fetch emissions for HENDERSON_RENEWABLE: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=HENDERSON_RENEWABLE&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for HENDERSON_RENEWABLE
Fetching emissions for facility HEPWIND... count no 211
⚠️ Failed to fetch emissions for HEPWIND: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=HEPWIND&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for HEPWIND
Fetching emissions for facility HIGHBRY... count no 212
⚠️ Failed to fetch emissions for HIGHBRY: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=HIGHBRY&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for HIGHBRY
Fetching emissions for facility HILLSTN... count no 213
Fetching emissions for facility HORNSDAL... count no 214
Fetching emissions for facility HORNSDAL2... count no 215
Fetching emissions for facility HORNSDAL3... count no 216
Fetching emissions for facility HORNSDPR... count no 217
Fetching emissions for facility 0HORSHAMSF... count no 218
⚠️ Failed to fetch emissions for 0HORSHAMSF: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=0HORSHAMSF&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for 0HORSHAMSF
Fetching emissions for facility HUGSF... count no 219
Fetching emissions for facility HUMENSW... count no 220
Fetching emissions for facility HUMEV... count no 221
Fetching emissions for facility HUNTER... count no 222
Fetching emissions for facility HEZ... count no 223
Fetching emissions for facility HUNTVGT... count no 224
⚠️ Failed to fetch emissions for HUNTVGT: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=HUNTVGT&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for HUNTVGT
Fetching emissions for facility INVICTA... count no 225
⚠️ Failed to fetch emissions for INVICTA: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=INVICTA&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for INVICTA
Fetching emissions for facility ICSM... count no 226
⚠️ Failed to fetch emissions for ICSM: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=ICSM&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for ICSM
Fetching emissions for facility JACKSGUL... count no 227
⚠️ Failed to fetch emissions for JACKSGUL: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=JACKSGUL&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for JACKSGUL
Fetching emissions for facility JEERA... count no 228
Fetching emissions for facility JEERB... count no 229
Fetching emissions for facility JEMALNG1... count no 230
Fetching emissions for facility JNDSHPS... count no 231
⚠️ Failed to fetch emissions for JNDSHPS: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=JNDSHPS&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for JNDSHPS
Fetching emissions for facility SNWYGJP2... count no 232
Fetching emissions for facility JBUTTERS... count no 233
Fetching emissions for facility JOUNAMA... count no 234
⚠️ Failed to fetch emissions for JOUNAMA: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=JOUNAMA&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for JOUNAMA
Fetching emissions for facility JUNEESF... count no 235
Fetching emissions for facility KABANWF... count no 236
Fetching emissions for facility KALAMUNDA_SG... count no 237
⚠️ Failed to fetch emissions for KALAMUNDA_SG: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=KALAMUNDA_SG&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for KALAMUNDA_SG
Fetching emissions for facility KALBARRI... count no 238
⚠️ Failed to fetch emissions for KALBARRI: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=KALBARRI&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for KALBARRI
Fetching emissions for facility STHRNCRS... count no 239
⚠️ Failed to fetch emissions for STHRNCRS: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=STHRNCRS&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for STHRNCRS
Fetching emissions for facility KARSF... count no 240

Fetching emissions for facility BLAIRFOX_KARAKIN... count no 241
⚠️ Failed to fetch emissions for BLAIRFOX_KARAKIN: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=BLAIRFOX_KARAKIN&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for BLAIRFOX_KARAKIN
Fetching emissions for facility KAREEYA... count no 242
Fetching emissions for facility KEEPIT... count no 243
⚠️ Failed to fetch emissions for KEEPIT: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=KEEPIT&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for KEEPIT
Fetching emissions for facility KEMERTON... count no 244
⚠️ Failed to fetch emissions for KEMERTON: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=KEMERTON&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for KEMERTON
Fetching emissions for facility TESLA_KEMERTON... count no 245
⚠️ Failed to fetch emissions for TESLA_KEMERTON: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=TESLA_KEMERTON&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for TESLA_KEMERTON
Fetching emissions for facility AGLSITA... count no 246
⚠️ Failed to fetch emissions for AGLSITA: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=AGLSITA&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for AGLSITA
Fetching emissions for facility KENNEDY... count no 247
Fetching emissions for facility KERNGSP... count no 248
Fetching emissions for facility KIAMSF1... count no 249
Fetching emissions for facility KIATAWF... count no 250
Fetching emissions for facility 0KIDSTON... count no 251
⚠️ Failed to fetch emissions for 0KIDSTON: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=0KIDSTON&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for 0KIDSTON
Fetching emissions for facility KSP1... count no 252
Fetching emissions for facility KINCUMB... count no 253
⚠️ Failed to fetch emissions for KINCUMB: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=KINCUMB&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for KINCUMB
Fetching emissions for facility KINGASF... count no 254
Fetching emissions for facility 0KINGS_ROCK_WF... count no 255
⚠️ Failed to fetch emissions for 0KINGS_ROCK_WF: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=0KINGS_ROCK_WF&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for 0KINGS_ROCK_WF
Fetching emissions for facility KOGANCK... count no 256
Fetching emissions for facility KOOLKHAN... count no 257
⚠️ Failed to fetch emissions for KOOLKHAN: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=KOOLKHAN&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for KOOLKHAN
Fetching emissions for facility KESS1... count no 258
Fetching emissions for facility KRCCOGEN... count no 259
⚠️ Failed to fetch emissions for KRCCOGEN: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=KRCCOGEN&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for KRCCOGEN
Fetching emissions for facility KWINANA... count no 260
⚠️ Failed to fetch emissions for KWINANA: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=KWINANA&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for KWINANA
Fetching emissions for facility KWINANA_ESR... count no 261
⚠️ Failed to fetch emissions for KWINANA_ESR: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=KWINANA_ESR&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for KWINANA_ESR
Fetching emissions for facility KWINANA_ESR2... count no 262
⚠️ Failed to fetch emissions for KWINANA_ESR2: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=KWINANA_ESR2&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for KWINANA_ESR2
Fetching emissions for facility TIWEST_COG1... count no 263
⚠️ Failed to fetch emissions for TIWEST_COG1: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=TIWEST_COG1&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for TIWEST_COG1
Fetching emissions for facility PERTHENERGY_KWINANA... count no 264
⚠️ Failed to fetch emissions for PERTHENERGY_KWINANA: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=PERTHENERGY_KWINANA&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for PERTHENERGY_KWINANA
Fetching emissions for facility LADBROKE... count no 265
Fetching emissions for facility LBBESS... count no 266
Fetching emissions for facility LKBONNY1... count no 267
Fetching emissions for facility LKBONNY_2... count no 268
Fetching emissions for facility LKBONNY3... count no 269
Fetching emissions for facility LK_ECHO... count no 270
Fetching emissions for facility 0LANCSF... count no 271
⚠️ Failed to fetch emissions for 0LANCSF: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=0LANCSF&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for 0LANCSF
Fetching emissions for facility LVES... count no 272
Fetching emissions for facility LNGS... count no 273
Fetching emissions for facility LEM_WIL... count no 274
Fetching emissions for facility 0LIDDELLBESS... count no 275
⚠️ Failed to fetch emissions for 0LIDDELLBESS: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=0LIDDELLBESS&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for 0LIDDELLBESS
Fetching emissions for facility LIDDELL... count no 276
⚠️ Failed to fetch emissions for LIDDELL: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=LIDDELL&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for LIDDELL
Fetching emissions for facility LILYVASF... count no 277
Fetching emissions for facility 0LCNBESS... count no 278
⚠️ Failed to fetch emissions for 0LCNBESS: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=0LCNBESS&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for 0LCNBESS
Fetching emissions for facility LIMBESS... count no 279
⚠️ Failed to fetch emissions for LIMBESS: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=LIMBESS&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for LIMBESS
Fetching emissions for facility LIMOSF1... count no 280

Fetching emissions for facility LIMOSF2... count no 281
Fetching emissions for facility LGAPWF1... count no 282
Fetching emissions for facility 0LOCKHART... count no 283
⚠️ Failed to fetch emissions for 0LOCKHART: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=0LOCKHART&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for 0LOCKHART
Fetching emissions for facility LONGFORD... count no 284
⚠️ Failed to fetch emissions for LONGFORD: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=LONGFORD&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for LONGFORD
Fetching emissions for facility LRSF... count no 285
Fetching emissions for facility LONSDALE... count no 286
Fetching emissions for facility 0LOTUSCRKWF... count no 287
⚠️ Failed to fetch emissions for 0LOTUSCRKWF: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=0LOTUSCRKWF&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for 0LOTUSCRKWF
Fetching emissions for facility LOYYANGA... count no 288
Fetching emissions for facility LOYYB... count no 289
Fetching emissions for facility LUCASHGT... count no 290
⚠️ Failed to fetch emissions for LUCASHGT: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=LUCASHGT&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for LUCASHGT
Fetching emissions for facility LUCAS2S2... count no 291
⚠️ Failed to fetch emissions for LUCAS2S2: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=LUCAS2S2&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for LUCAS2S2
Fetching emissions for facility MACARTH... count no 292
Fetching emissions for facility MCINTYR... count no 293
Fetching emissions for facility MACKAY... count no 294
⚠️ Failed to fetch emissions for MACKAY: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=MACKAY&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for MACKAY
Fetching emissions for facility MACKNTSH... count no 295
Fetching emissions for facility MANSLR... count no 296
Fetching emissions for facility BRIDGETOWN_BIOMASS_PLANT... count no 297
⚠️ Failed to fetch emissions for BRIDGETOWN_BIOMASS_PLANT: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=BRIDGETOWN_BIOMASS_PLANT&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for BRIDGETOWN_BIOMASS_PLANT
Fetching emissions for facility MANNUMB... count no 298
Fetching emissions for facility MANNSF... count no 299
Fetching emissions for facility MAPS2... count no 300
Fetching emissions for facility MAROOWF1... count no 301
⚠️ Failed to fetch emissions for MAROOWF1: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=MAROOWF1&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for MAROOWF1
Fetching emissions for facility MARYRSF... count no 302
Fetching emissions for facility 0MARYVALE... count no 303
⚠️ Failed to fetch emissions for 0MARYVALE: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=0MARYVALE&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for 0MARYVALE
Fetching emissions for facility MEADOWBK... count no 304
Fetching emissions for facility 0MREH... count no 305
Fetching emissions for facility 0MREHA2... count no 306
Fetching emissions for facility MREHA3... count no 307
Fetching emissions for facility 0MERREDINBESS... count no 308
⚠️ Failed to fetch emissions for 0MERREDINBESS: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=0MERREDINBESS&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for 0MERREDINBESS
Fetching emissions for facility MERSOLAR... count no 309
⚠️ Failed to fetch emissions for MERSOLAR: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=MERSOLAR&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for MERSOLAR
Fetching emissions for facility NAMKKN_MERR... count no 310
⚠️ Failed to fetch emissions for NAMKKN_MERR: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=NAMKKN_MERR&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for NAMKKN_MERR
Fetching emissions for facility AMBRISOLAR... count no 311
⚠️ Failed to fetch emissions for AMBRISOLAR: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=AMBRISOLAR&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for AMBRISOLAR
Fetching emissions for facility METZSF... count no 312
Fetching emissions for facility MIDDLSF1... count no 313
Fetching emissions for facility MIDLDPS... count no 314
⚠️ Failed to fetch emissions for MIDLDPS: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=MIDLDPS&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for MIDLDPS
Fetching emissions for facility MILLMERN... count no 315
Fetching emissions for facility MINTARO... count no 316
Fetching emissions for facility ATLAS... count no 317
⚠️ Failed to fetch emissions for ATLAS: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=ATLAS&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for ATLAS
Fetching emissions for facility MOKOSF... count no 318
Fetching emissions for facility MOLNGSF1... count no 319
Fetching emissions for facility MOORAWF1... count no 320
Fetching emissions for facility MORANBAH... count no 321
⚠️ Failed to fetch emissions for MORANBAH: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=MORANBAH&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for MORANBAH
Fetching emissions for facility MBAHNTH... count no 322
Fetching emissions for facility MOREESF... count no 323
Fetching emissions for facility MWPS... count no 324
Fetching emissions for facility 0MORNBESS... count no 325
⚠️ Failed to fetch emissions for 0MORNBESS: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=0MORNBESS&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for 0MORNBESS
Fetching emissions for facility MORNW... count no 326
⚠️ Failed to fetch emissions for MORNW: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=MORNW&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for MORNW
Fetching emissions for facility 0MRTLKBESS... count no 327
⚠️ Failed to fetch emissions for 0MRTLKBESS: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=0MRTLKBESS&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for 0MRTLKBESS
Fetching emissions for facility MORTLK... count no 328

Fetching emissions for facility MRTLSWF... count no 329
Fetching emissions for facility MLWF... count no 330
Fetching emissions for facility SKYFRM_MTBARKER... count no 331
⚠️ Failed to fetch emissions for SKYFRM_MTBARKER: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=SKYFRM_MTBARKER&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for SKYFRM_MTBARKER
Fetching emissions for facility MOUSF... count no 332
Fetching emissions for facility MEWF... count no 333
Fetching emissions for facility MTGELWF... count no 334
Fetching emissions for facility MTMERCER... count no 335
Fetching emissions for facility MTMILLAR... count no 336
Fetching emissions for facility MP... count no 337
Fetching emissions for facility MSTUART... count no 338
Fetching emissions for facility 0MUCHEABESS... count no 339
⚠️ Failed to fetch emissions for 0MUCHEABESS: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=0MUCHEABESS&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for 0MUCHEABESS
Fetching emissions for facility MLLFGEF... count no 340
⚠️ Failed to fetch emissions for MLLFGEF: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=MLLFGEF&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for MLLFGEF
Fetching emissions for facility MLSP... count no 341
Fetching emissions for facility MUJA_AB... count no 342
⚠️ Failed to fetch emissions for MUJA_AB: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=MUJA_AB&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for MUJA_AB
Fetching emissions for facility MUJA... count no 343
⚠️ Failed to fetch emissions for MUJA: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=MUJA&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for MUJA
Fetching emissions for facility MWF_MUMBIDA... count no 344
⚠️ Failed to fetch emissions for MWF_MUMBIDA: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=MWF_MUMBIDA&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for MWF_MUMBIDA
Fetching emissions for facility MUNGARRA... count no 345
⚠️ Failed to fetch emissions for MUNGARRA: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=MUNGARRA&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for MUNGARRA
Fetching emissions for facility MM... count no 346
⚠️ Failed to fetch emissions for MM: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=MM&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for MM
Fetching emissions for facility MUCRKSF... count no 347
Fetching emissions for facility MUWAWF... count no 348
Fetching emissions for facility MURRAY... count no 349
Fetching emissions for facility MBPS2... count no 350
Fetching emissions for facility MUSSELRO... count no 351
Fetching emissions for facility NASF... count no 352
⚠️ Failed to fetch emissions for NASF: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=NASF&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for NASF
Fetching emissions for facility NEWGEN_NEERABUP... count no 353
⚠️ Failed to fetch emissions for NEWGEN_NEERABUP: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=NEWGEN_NEERABUP&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for NEWGEN_NEERABUP
Fetching emissions for facility NEVERSF... count no 354
Fetching emissions for facility NEWENSF... count no 355
Fetching emissions for facility NEWGEN_KWINANA... count no 356
⚠️ Failed to fetch emissions for NEWGEN_KWINANA: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=NEWGEN_KWINANA&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for NEWGEN_KWINANA
Fetching emissions for facility NEWPORT... count no 357
Fetching emissions for facility NBHWF... count no 358
Fetching emissions for facility NORTHAM_SF... count no 359
⚠️ Failed to fetch emissions for NORTHAM_SF: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=NORTHAM_SF&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for NORTHAM_SF
Fetching emissions for facility TESLA_NORTHAM... count no 360
⚠️ Failed to fetch emissions for TESLA_NORTHAM: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=TESLA_NORTHAM&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for TESLA_NORTHAM
Fetching emissions for facility NORTHGT... count no 361
⚠️ Failed to fetch emissions for NORTHGT: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=NORTHGT&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for NORTHGT
Fetching emissions for facility NORTHP... count no 362
⚠️ Failed to fetch emissions for NORTHP: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=NORTHP&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for NORTHP
Fetching emissions for facility NUMURKSF... count no 363
Fetching emissions for facility NYNGAN... count no 364
Fetching emissions for facility OAKEY... count no 365
Fetching emissions for facility OAKEY2SF... count no 366
Fetching emissions for facility OAKEY1SF... count no 367
Fetching emissions for facility OAKLAND... count no 368
Fetching emissions for facility OCPS... count no 369
⚠️ Failed to fetch emissions for OCPS: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=OCPS&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for OCPS
Fetching emissions for facility OAKY2... count no 370
⚠️ Failed to fetch emissions for OAKY2: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=OAKY2&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for OAKY2
Fetching emissions for facility 0ORANABESS... count no 371
⚠️ Failed to fetch emissions for 0ORANABESS: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=0ORANABESS&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for 0ORANABESS
Fetching emissions for facility OSBORNE... count no 372
Fetching emissions for facility PALOONA... count no 373
Fetching emissions for facility PSF... count no 374
Fetching emissions for facility PRK_AG... count no 375
⚠️ Failed to fetch emissions for PRK_AG: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=PRK_AG&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for PRK_AG
Fetching emissions for facility PEDLER... count no 376

⚠️ Failed to fetch emissions for PEDLER: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=PEDLER&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for PEDLER
Fetching emissions for facility NPPPPS... count no 377
Fetching emissions for facility PIBESS... count no 378
Fetching emissions for facility PHOENIX_KWINANA_WTE... count no 379
⚠️ Failed to fetch emissions for PHOENIX_KWINANA_WTE: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=PHOENIX_KWINANA_WTE&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for PHOENIX_KWINANA_WTE
Fetching emissions for facility TESLA_PICTON... count no 380
⚠️ Failed to fetch emissions for TESLA_PICTON: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=TESLA_PICTON&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for TESLA_PICTON
Fetching emissions for facility PINDARI... count no 381
⚠️ Failed to fetch emissions for PINDARI: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=PINDARI&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for PINDARI
Fetching emissions for facility PINJAR... count no 382
⚠️ Failed to fetch emissions for PINJAR: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=PINJAR&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for PINJAR
Fetching emissions for facility ALINTA_PNJ... count no 383
⚠️ Failed to fetch emissions for ALINTA_PNJ: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=ALINTA_PNJ&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for ALINTA_PNJ
Fetching emissions for facility PIONEER... count no 384
Fetching emissions for facility PLAYF... count no 385
⚠️ Failed to fetch emissions for PLAYF: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=PLAYF&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for PLAYF
Fetching emissions for facility PTINA... count no 386
Fetching emissions for facility PAREPW... count no 387
Fetching emissions for facility 0PLWF... count no 388
⚠️ Failed to fetch emissions for 0PLWF: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=0PLWF&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for 0PLWF
Fetching emissions for facility PORTLATT... count no 389
⚠️ Failed to fetch emissions for PORTLATT: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=PORTLATT&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for PORTLATT
Fetching emissions for facility PORTLCN... count no 390
Fetching emissions for facility STANVAC... count no 391
Fetching emissions for facility PORTWF... count no 392
Fetching emissions for facility QUARANTN... count no 393
Fetching emissions for facility QUERIVER... count no 394
⚠️ Failed to fetch emissions for QUERIVER: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=QUERIVER&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for QUERIVER
Fetching emissions for facility QBYNB... count no 395
Fetching emissions for facility QP... count no 396
⚠️ Failed to fetch emissions for QP: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=QP&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for QP
Fetching emissions for facility RACOMIL... count no 397
⚠️ Failed to fetch emissions for RACOMIL: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=RACOMIL&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for RACOMIL
Fetching emissions for facility RANGEB... count no 398
Fetching emissions for facility RED_HILL... count no 399
⚠️ Failed to fetch emissions for RED_HILL: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=RED_HILL&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for RED_HILL
Fetching emissions for facility REDBANK1... count no 400
⚠️ Failed to fetch emissions for REDBANK1: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=REDBANK1&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for REDBANK1
Fetching emissions for facility REECE... count no 401
Fetching emissions for facility REMOUNT... count no 402
⚠️ Failed to fetch emissions for REMOUNT: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=REMOUNT&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for REMOUNT
Fetching emissions for facility REPULSE... count no 403
Fetching emissions for facility BIOGAS01... count no 404
⚠️ Failed to fetch emissions for BIOGAS01: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=BIOGAS01&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for BIOGAS01
Fetching emissions for facility 0RIVERINASF... count no 405
⚠️ Failed to fetch emissions for 0RIVERINASF: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=0RIVERINASF&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for 0RIVERINASF
Fetching emissions for facility RESS... count no 406
Fetching emissions for facility RIVNB... count no 407
Fetching emissions for facility ROCHEDAL... count no 408
⚠️ Failed to fetch emissions for ROCHEDAL: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=ROCHEDAL&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for ROCHEDAL
Fetching emissions for facility ROCKINGHAM... count no 409
⚠️ Failed to fetch emissions for ROCKINGHAM: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=ROCKINGHAM&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for ROCKINGHAM
Fetching emissions for facility RPCG... count no 410
Fetching emissions for facility EDLRGNRD... count no 411
⚠️ Failed to fetch emissions for EDLRGNRD: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=EDLRGNRD&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for EDLRGNRD
Fetching emissions for facility ROMA... count no 412
Fetching emissions for facility RRSF... count no 413
Fetching emissions for facility ROWALLAN... count no 414
Fetching emissions for facility ROYALLA... count no 415
Fetching emissions for facility RUBICON... count no 416
Fetching emissions for facility RUGBYR... count no 417

Fetching emissions for facility RYANCWF... count no 418
Fetching emissions for facility RYEPARK... count no 419
Fetching emissions for facility SALTCRK... count no 420
Fetching emissions for facility SAPHWF1... count no 421
Fetching emissions for facility SEBSF... count no 422
Fetching emissions for facility SHEP1... count no 423
⚠️ Failed to fetch emissions for SHEP1: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=SHEP1&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for SHEP1
Fetching emissions for facility SHOALHAV... count no 424
Fetching emissions for facility SHOAL... count no 425
Fetching emissions for facility STWF... count no 426
Fetching emissions for facility SITHE... count no 427
Fetching emissions for facility SMTHBES1... count no 428
Fetching emissions for facility SNAPPER... count no 429
Fetching emissions for facility SNOWTOWN... count no 430
Fetching emissions for facility SNOWNTH... count no 431
Fetching emissions for facility SNOWSTH... count no 432
Fetching emissions for facility SNOWY4... count no 433
⚠️ Failed to fetch emissions for SNOWY4: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=SNOWY4&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for SNOWY4
Fetching emissions for facility SNOWY5... count no 434
⚠️ Failed to fetch emissions for SNOWY5: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=SNOWY5&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for SNOWY5
Fetching emissions for facility 0SNOWY20... count no 435
⚠️ Failed to fetch emissions for 0SNOWY20: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=0SNOWY20&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for 0SNOWY20
Fetching emissions for facility SNUG... count no 436
Fetching emissions for facility AGLSOM... count no 437
Fetching emissions for facility SOUTH_CARDUP... count no 438
⚠️ Failed to fetch emissions for SOUTH_CARDUP: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=SOUTH_CARDUP&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for SOUTH_CARDUP
Fetching emissions for facility SKSF... count no 439
⚠️ Failed to fetch emissions for SKSF: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=SKSF&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for SKSF
Fetching emissions for facility STHBKTEC... count no 440
⚠️ Failed to fetch emissions for STHBKTEC: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=STHBKTEC&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for STHBKTEC
Fetching emissions for facility SVALE... count no 441
⚠️ Failed to fetch emissions for SVALE: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=SVALE&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for SVALE
Fetching emissions for facility STGEORGE... count no 442
⚠️ Failed to fetch emissions for STGEORGE: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=STGEORGE&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for STGEORGE
Fetching emissions for facility SLDCBLK... count no 443
⚠️ Failed to fetch emissions for SLDCBLK: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=SLDCBLK&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for SLDCBLK
Fetching emissions for facility 0STANBESS... count no 444
⚠️ Failed to fetch emissions for 0STANBESS: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=0STANBESS&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for 0STANBESS
Fetching emissions for facility STANWELL... count no 445
Fetching emissions for facility STAPYLTON... count no 446
⚠️ Failed to fetch emissions for STAPYLTON: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=STAPYLTON&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for STAPYLTON
Fetching emissions for facility STARFHILL... count no 447
Fetching emissions for facility STOCKYD... count no 448
Fetching emissions for facility STUBSF... count no 449
Fetching emissions for facility 0SUMMFBESS... count no 450
⚠️ Failed to fetch emissions for 0SUMMFBESS: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=0SUMMFBESS&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for 0SUMMFBESS
Fetching emissions for facility SMCSF... count no 451
Fetching emissions for facility SUNCOAST... count no 452
⚠️ Failed to fetch emissions for SUNCOAST: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=SUNCOAST&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for SUNCOAST
Fetching emissions for facility SUNRSF1... count no 453
Fetching emissions for facility VALDORA... count no 454
⚠️ Failed to fetch emissions for VALDORA: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=VALDORA&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for VALDORA
Fetching emissions for facility SUNTPSF... count no 455
Fetching emissions for facility SNB1... count no 456
Fetching emissions for facility 0SUPERNODE2... count no 457
⚠️ Failed to fetch emissions for 0SUPERNODE2: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=0SUPERNODE2&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for 0SUPERNODE2
Fetching emissions for facility SRSF... count no 458
Fetching emissions for facility 0SWANBBESS... count no 459
⚠️ Failed to fetch emissions for 0SWANBBESS: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=0SWANBBESS&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for 0SWANBBESS
Fetching emissions for facility SWAN_B... count no 460
⚠️ Failed to fetch emissions for SWAN_B: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=SWAN_B&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for SWAN_B
Fetching emissions for facility SWAN_E... count no 461
Fetching emissions for facility TABMILL2... count no 462
⚠️ Failed to fetch emissions for TABMILL2: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=TABMILL2&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for TABMILL2
Fetching emissions for facility TAHMOOR... count no 463
⚠️ Failed to fetch emissions for TAHMOOR: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=TAHMOOR&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for TAHMOOR
Fetching emissions for facility TBSF... count no 464

Fetching emissions for facility TB2SF... count no 465
Fetching emissions for facility TALLAWAR... count no 466
Fetching emissions for facility TALWB... count no 467
Fetching emissions for facility TAMALA_PARK... count no 468
⚠️ Failed to fetch emissions for TAMALA_PARK: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=TAMALA_PARK&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for TAMALA_PARK
Fetching emissions for facility TVCCPS... count no 469
Fetching emissions for facility TARALGA... count no 470
Fetching emissions for facility 0TARONGBESS... count no 471
Fetching emissions for facility TARONG... count no 472
Fetching emissions for facility TARONGN... count no 473
Fetching emissions for facility TARRALEA... count no 474
Fetching emissions for facility TATIARA... count no 475
⚠️ Failed to fetch emissions for TATIARA: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=TATIARA&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for TATIARA
Fetching emissions for facility TATURA... count no 476
⚠️ Failed to fetch emissions for TATURA: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=TATURA&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for TATURA
Fetching emissions for facility TEATREE... count no 477
⚠️ Failed to fetch emissions for TEATREE: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=TEATREE&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for TEATREE
Fetching emissions for facility TEMPB... count no 478
Fetching emissions for facility SATGN... count no 479
⚠️ Failed to fetch emissions for SATGN: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=SATGN&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for SATGN
Fetching emissions for facility SATGS... count no 480
⚠️ Failed to fetch emissions for SATGS: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=SATGS&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for SATGS
Fetching emissions for facility TERALBA... count no 481
⚠️ Failed to fetch emissions for TERALBA: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=TERALBA&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for TERALBA
Fetching emissions for facility 0TERANGBESS... count no 482
⚠️ Failed to fetch emissions for 0TERANGBESS: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=0TERANGBESS&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for 0TERANGBESS
Fetching emissions for facility TERMSTOR... count no 483
⚠️ Failed to fetch emissions for TERMSTOR: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=TERMSTOR&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for TERMSTOR
Fetching emissions for facility BLUFF... count no 484
Fetching emissions for facility THEDROP... count no 485
⚠️ Failed to fetch emissions for THEDROP: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=THEDROP&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for THEDROP
Fetching emissions for facility 0TILBSF... count no 486
⚠️ Failed to fetch emissions for 0TILBSF: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=0TILBSF&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for 0TILBSF
Fetching emissions for facility TIMWEST... count no 487
⚠️ Failed to fetch emissions for TIMWEST: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=TIMWEST&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for TIMWEST
Fetching emissions for facility 0TOMAGOBESS... count no 488
⚠️ Failed to fetch emissions for 0TOMAGOBESS: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=0TOMAGOBESS&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for 0TOMAGOBESS
Fetching emissions for facility TOORAWF... count no 489
⚠️ Failed to fetch emissions for TOORAWF: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=TOORAWF&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for TOORAWF
Fetching emissions for facility TIB... count no 490
Fetching emissions for facility TORRIS... count no 491
Fetching emissions for facility TOWER... count no 492
⚠️ Failed to fetch emissions for TOWER: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=TOWER&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for TOWER
Fetching emissions for facility YABULU... count no 493
Fetching emissions for facility TGNSS... count no 494
⚠️ Failed to fetch emissions for TGNSS: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=TGNSS&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for TGNSS
Fetching emissions for facility TREVALLN... count no 495
Fetching emissions for facility TRIBUTE... count no 496
Fetching emissions for facility TULLYSM... count no 497
Fetching emissions for facility SNOWY2... count no 498
Fetching emissions for facility TUMUT3... count no 499
Fetching emissions for facility TUNGATIN... count no 500
Fetching emissions for facility ULBESS... count no 501
Fetching emissions for facility URANQ... count no 502
Fetching emissions for facility 0UUNGULAWF... count no 503
⚠️ Failed to fetch emissions for 0UUNGULAWF: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=0UUNGULAWF&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for 0UUNGULAWF
Fetching emissions for facility VP... count no 504
Fetching emissions for facility VPGS... count no 505
Fetching emissions for facility TITREE... count no 506
⚠️ Failed to fetch emissions for TITREE: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=TITREE&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for TITREE
Fetching emissions for facility VICMILL... count no 507
⚠️ Failed to fetch emissions for VICMILL: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=VICMILL&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for VICMILL
Fetching emissions for facility VBB... count no 508
Fetching emissions for facility 0WAGERUP_BESS... count no 509
⚠️ Failed to fetch emissions for 0WAGERUP_BESS: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=0WAGERUP_BESS&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for 0WAGERUP_BESS
Fetching emissions for facility ALCOA_WGP... count no 510

⚠️ Failed to fetch emissions for ALCOA_WGP: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=ALCOA_WGP&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for ALCOA_WGP
Fetching emissions for facility WAGGNSF... count no 511
Fetching emissions for facility ALINTA_WWF... count no 512
⚠️ Failed to fetch emissions for ALINTA_WWF: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=ALINTA_WWF&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for ALINTA_WWF
Fetching emissions for facility WLWLSF... count no 513
Fetching emissions for facility WW... count no 514
⚠️ Failed to fetch emissions for WW: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=WW&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for WW
Fetching emissions for facility WALGRV... count no 515
Fetching emissions for facility PRDSO_WALPOLE... count no 516
⚠️ Failed to fetch emissions for PRDSO_WALPOLE: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=PRDSO_WALPOLE&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for PRDSO_WALPOLE
Fetching emissions for facility 0WAMBOWF... count no 517
Fetching emissions for facility WANDSF... count no 518
Fetching emissions for facility WANDBG... count no 519
Fetching emissions for facility WNSF... count no 520
Fetching emissions for facility WTAHB... count no 521
Fetching emissions for facility WARRADARGE... count no 522
⚠️ Failed to fetch emissions for WARRADARGE: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=WARRADARGE&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for WARRADARGE
Fetching emissions for facility WG... count no 523
⚠️ Failed to fetch emissions for WG: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=WG&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for WG
Fetching emissions for facility WARWSF... count no 524
Fetching emissions for facility WATERLWF... count no 525
Fetching emissions for facility WPWF... count no 526
Fetching emissions for facility WAUBRAWF... count no 527
Fetching emissions for facility WELLSF1... count no 528
Fetching emissions for facility WELNSF... count no 529
Fetching emissions for facility WEMENSF1... count no 530
Fetching emissions for facility BLAIRFOX_WESTHILLS... count no 531
⚠️ Failed to fetch emissions for BLAIRFOX_WESTHILLS: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=BLAIRFOX_WESTHILLS&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for BLAIRFOX_WESTHILLS
Fetching emissions for facility WESTILLA... count no 532
⚠️ Failed to fetch emissions for WESTILLA: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=WESTILLA&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for WESTILLA
Fetching emissions for facility WEST_KALGOORLIE... count no 533
⚠️ Failed to fetch emissions for WEST_KALGOORLIE: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=WEST_KALGOORLIE&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for WEST_KALGOORLIE
Fetching emissions for facility WKIEWA... count no 534
Fetching emissions for facility AGLNOW1... count no 535
⚠️ Failed to fetch emissions for AGLNOW1: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=AGLNOW1&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for AGLNOW1
Fetching emissions for facility WSTWYSF... count no 536
Fetching emissions for facility WDBESS... count no 537
Fetching emissions for facility WDGPH... count no 538
Fetching emissions for facility WDBESS2... count no 539
Fetching emissions for facility WESTCBT... count no 540
⚠️ Failed to fetch emissions for WESTCBT: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=WESTCBT&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for WESTCBT
Fetching emissions for facility WRSF1... count no 541
Fetching emissions for facility WRWF1... count no 542
Fetching emissions for facility WHITSF... count no 543
Fetching emissions for facility WHIT1... count no 544
⚠️ Failed to fetch emissions for WHIT1: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=WHIT1&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for WHIT1
Fetching emissions for facility WILGAPK... count no 545
⚠️ Failed to fetch emissions for WILGAPK: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=WILGAPK&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for WILGAPK
Fetching emissions for facility WILGAPKB... count no 546
⚠️ Failed to fetch emissions for WILGAPKB: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=WILGAPKB&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for WILGAPKB
Fetching emissions for facility WILLHOV... count no 547
⚠️ Failed to fetch emissions for WILLHOV: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=WILLHOV&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for WILLHOV
Fetching emissions for facility 0WDBESS... count no 548
⚠️ Failed to fetch emissions for 0WDBESS: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=0WDBESS&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for 0WDBESS
Fetching emissions for facility WGWF... count no 549
Fetching emissions for facility NINEWIL... count no 550
⚠️ Failed to fetch emissions for NINEWIL: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=NINEWIL&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for NINEWIL
Fetching emissions for facility WINDHILL... count no 551
⚠️ Failed to fetch emissions for WINDHILL: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=WINDHILL&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for WINDHILL
Fetching emissions for facility WINGF1... count no 552
⚠️ Failed to fetch emissions for WINGF1: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=WINGF1&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for WINGF1
Fetching emissions for facility WINGF2... count no 553
⚠️ Failed to fetch emissions for WINGF2: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=WINGF2&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for WINGF2
Fetching emissions for facility WINTSF1... count no 554

Fetching emissions for facility WIVENHOE... count no 555
Fetching emissions for facility WIVENSH... count no 556
⚠️ Failed to fetch emissions for WIVENSH: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=WIVENSH&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for WIVENSH
Fetching emissions for facility WOLARSF... count no 557
Fetching emissions for facility WOLLERT... count no 558
⚠️ Failed to fetch emissions for WOLLERT: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=WOLLERT&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for WOLLERT
Fetching emissions for facility WONWP... count no 559
⚠️ Failed to fetch emissions for WONWP: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=WONWP&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for WONWP
Fetching emissions for facility WDLNGN... count no 560
⚠️ Failed to fetch emissions for WDLNGN: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=WDLNGN&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for WDLNGN
Fetching emissions for facility WOODLWN... count no 561
Fetching emissions for facility WOOLNTH1... count no 562
Fetching emissions for facility WOOLGSF... count no 563
Fetching emissions for facility 0WOORBESS... count no 564
⚠️ Failed to fetch emissions for 0WOORBESS: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=0WOORBESS&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for 0WOORBESS
Fetching emissions for facility WOYWOY... count no 565
⚠️ Failed to fetch emissions for WOYWOY: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=WOYWOY&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for WOYWOY
Fetching emissions for facility WUNUSF... count no 566
Fetching emissions for facility WYASF... count no 567
Fetching emissions for facility WYANGALA... count no 568
⚠️ Failed to fetch emissions for WYANGALA: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=WYANGALA&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for WYANGALA
Fetching emissions for facility WYANGALB... count no 569
⚠️ Failed to fetch emissions for WYANGALB: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=WYANGALB&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for WYANGALB
Fetching emissions for facility WYNDW... count no 570
⚠️ Failed to fetch emissions for WYNDW: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=WYNDW&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for WYNDW
Fetching emissions for facility YALLOURN... count no 571
Fetching emissions for facility YSWF... count no 572
Fetching emissions for facility YAMBUK... count no 573
Fetching emissions for facility YANDIN... count no 574
⚠️ Failed to fetch emissions for YANDIN: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=YANDIN&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for YANDIN
Fetching emissions for facility YARANSF... count no 575
Fetching emissions for facility YWNGAHYD... count no 576
⚠️ Failed to fetch emissions for YWNGAHYD: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=YWNGAHYD&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for YWNGAHYD
Fetching emissions for facility YARWUN... count no 577
Fetching emissions for facility YATSF1... count no 578
Fetching emissions for facility YAWWF... count no 579
⚠️ Failed to fetch emissions for YAWWF: 416 Client Error: Range Not Satisfiable for url: https://api.openelectricity.org.au/v4/data/facilities/NEM?metrics=emissions&interval=5m&facility_code=YAWWF&date_start=2025-10-01+00%3A00%3A00&date_end=2025-10-08+00%3A00%3A00
⚠️ No data for YAWWF
Fetching emissions for facility YENDONWF... count no 580

### 1.2.3. PER-MARKET POWER PRICE AND DEMAND (5 min interval)

fetches 5-minute market data (spot price and demand) for each network region of the NEM.

In [52]:
NETWORK = "NEM"
NETWORK_REGIONS = ["NSW1", "QLD1", "SA1", "TAS1", "VIC1"]

# SETTINGS
NETWORK_REGIONS = ["NSW1", "QLD1", "SA1", "TAS1", "VIC1"]
METRICS = ["price", "demand"]

def fetch_market_metric(network: str, region: str, metric: str, start: datetime, end: datetime) -> pd.DataFrame:
    
    url = f"{BASE_URL}/market/network/{network}"
    params = {
        "metrics": metric,
        "interval": INTERVAL,
        "network_region": region,
        "date_start": START_DATE,
        "date_end": END_DATE,
    }

    # Request + error handling
    try:
        r = requests.get(url, headers=HEADERS, params=params)
        r.raise_for_status()
        json_data = r.json()
    except Exception as e:
        print(f" Failed {metric.upper()} {region} {start.date()}: {e}")
        return pd.DataFrame()

    # API error response handling
    if not json_data.get("success", False):
        print(f" API returned failure for {metric.upper()} {region}: {json_data.get('error')}")
        return pd.DataFrame()

    # Flatten nested JSON
    rows = []
    for entry in json_data.get("data", []):
        unit = entry.get("unit", "")
        for res in entry.get("results", []):
            for point in res.get("data", []):
                if len(point) == 2:
                    timestamp, value = point
                    rows.append({
                        "timestamp": timestamp,
                        "network": network,
                        "network_region": region,
                        f"value_{metric}": value,
                        f"unit_{metric}": unit,
                    })

    df = pd.DataFrame(rows)
    print(f"SUCCESSFUL {region}: {metric.upper()} {start.date()} → {len(df)} rows")
    return df



# Collect one day at a time to avoid overwhelming API
all_data = []
current_date = START_DATE

while current_date < END_DATE:
    next_date = current_date + timedelta(days=1)

    for region in NETWORK_REGIONS:
        region_data = []
        for metric in METRICS:
            df = fetch_market_metric(NETWORK, region, metric, current_date, next_date)
            if not df.empty:
                region_data.append(df)

        # Merge price + demand for this region/day
        if region_data:
            merged_df = region_data[0]
            for df in region_data[1:]:
                merged_df = pd.merge(
                    merged_df,
                    df,
                    on=["timestamp", "network", "network_region"],
                    how="outer"
                )
            all_data.append(merged_df)

    current_date = next_date
    
# Final concatenation of all data
if not all_data:
    print(" No market data retrieved for any region or day.")
 
market_raw = pd.concat(all_data, ignore_index=True)

SUCCESSFUL NSW1: PRICE 2025-10-01 → 2016 rows
SUCCESSFUL NSW1: DEMAND 2025-10-01 → 2016 rows
SUCCESSFUL QLD1: PRICE 2025-10-01 → 2016 rows
SUCCESSFUL QLD1: DEMAND 2025-10-01 → 2016 rows
SUCCESSFUL SA1: PRICE 2025-10-01 → 2016 rows
SUCCESSFUL SA1: DEMAND 2025-10-01 → 2016 rows
SUCCESSFUL TAS1: PRICE 2025-10-01 → 2016 rows
SUCCESSFUL TAS1: DEMAND 2025-10-01 → 2016 rows
SUCCESSFUL VIC1: PRICE 2025-10-01 → 2016 rows
SUCCESSFUL VIC1: DEMAND 2025-10-01 → 2016 rows
SUCCESSFUL NSW1: PRICE 2025-10-02 → 2016 rows
SUCCESSFUL NSW1: DEMAND 2025-10-02 → 2016 rows
SUCCESSFUL QLD1: PRICE 2025-10-02 → 2016 rows
SUCCESSFUL QLD1: DEMAND 2025-10-02 → 2016 rows
SUCCESSFUL SA1: PRICE 2025-10-02 → 2016 rows
SUCCESSFUL SA1: DEMAND 2025-10-02 → 2016 rows
SUCCESSFUL TAS1: PRICE 2025-10-02 → 2016 rows
SUCCESSFUL TAS1: DEMAND 2025-10-02 → 2016 rows
SUCCESSFUL VIC1: PRICE 2025-10-02 → 2016 rows
SUCCESSFUL VIC1: DEMAND 2025-10-02 → 2016 rows
SUCCESSFUL NSW1: PRICE 2025-10-03 → 2016 rows
SUCCESSFUL NSW1: DEMAND 2025-10-03 → 2016 rows
SUCCESSFUL QLD1: PRICE 2025-10-03 → 2016 rows
SUCCESSFUL QLD1: DEMAND 2025-10-03 → 2016 rows
SUCCESSFUL SA1: PRICE 2025-10-03 → 2016 rows
SUCCESSFUL SA1: DEMAND 2025-10-03 → 2016 rows
SUCCESSFUL TAS1: PRICE 2025-10-03 → 2016 rows
SUCCESSFUL TAS1: DEMAND 2025-10-03 → 2016 rows
SUCCESSFUL VIC1: PRICE 2025-10-03 → 2016 rows
SUCCESSFUL VIC1: DEMAND 2025-10-03 → 2016 rows
SUCCESSFUL NSW1: PRICE 2025-10-04 → 2016 rows
SUCCESSFUL NSW1: DEMAND 2025-10-04 → 2016 rows
SUCCESSFUL QLD1: PRICE 2025-10-04 → 2016 rows
SUCCESSFUL QLD1: DEMAND 2025-10-04 → 2016 rows
SUCCESSFUL SA1: PRICE 2025-10-04 → 2016 rows
SUCCESSFUL SA1: DEMAND 2025-10-04 → 2016 rows
SUCCESSFUL TAS1: PRICE 2025-10-04 → 2016 rows
SUCCESSFUL TAS1: DEMAND 2025-10-04 → 2016 rows
SUCCESSFUL VIC1: PRICE 2025-10-04 → 2016 rows
SUCCESSFUL VIC1: DEMAND 2025-10-04 → 2016 rows
SUCCESSFUL NSW1: PRICE 2025-10-05 → 2016 rows
SUCCESSFUL NSW1: DEMAND 2025-10-05 → 2016 rows
SUCCESSFUL QLD1: PRICE 2025-10-05 → 2016 rows
SUCCESSFUL QLD1: DEMAND 2025-10-05 → 2016 rows
SUCCESSFUL SA1: PRICE 2025-10-05 → 2016 rows
SUCCESSFUL SA1: DEMAND 2025-10-05 → 2016 rows
SUCCESSFUL TAS1: PRICE 2025-10-05 → 2016 rows
SUCCESSFUL TAS1: DEMAND 2025-10-05 → 2016 rows
SUCCESSFUL VIC1: PRICE 2025-10-05 → 2016 rows
SUCCESSFUL VIC1: DEMAND 2025-10-05 → 2016 rows
SUCCESSFUL NSW1: PRICE 2025-10-06 → 2016 rows
SUCCESSFUL NSW1: DEMAND 2025-10-06 → 2016 rows
SUCCESSFUL QLD1: PRICE 2025-10-06 → 2016 rows
SUCCESSFUL QLD1: DEMAND 2025-10-06 → 2016 rows
SUCCESSFUL SA1: PRICE 2025-10-06 → 2016 rows
SUCCESSFUL SA1: DEMAND 2025-10-06 → 2016 rows
SUCCESSFUL TAS1: PRICE 2025-10-06 → 2016 rows
SUCCESSFUL TAS1: DEMAND 2025-10-06 → 2016 rows
SUCCESSFUL VIC1: PRICE 2025-10-06 → 2016 rows
SUCCESSFUL VIC1: DEMAND 2025-10-06 → 2016 rows
SUCCESSFUL NSW1: PRICE 2025-10-07 → 2016 rows
SUCCESSFUL NSW1: DEMAND 2025-10-07 → 2016 rows
SUCCESSFUL QLD1: PRICE 2025-10-07 → 2016 rows
SUCCESSFUL QLD1: DEMAND 2025-10-07 → 2016 rows
SUCCESSFUL SA1: PRICE 2025-10-07 → 2016 rows
SUCCESSFUL SA1: DEMAND 2025-10-07 → 2016 rows
SUCCESSFUL TAS1: PRICE 2025-10-07 → 2016 rows
SUCCESSFUL TAS1: DEMAND 2025-10-07 → 2016 rows
SUCCESSFUL VIC1: PRICE 2025-10-07 → 2016 rows
SUCCESSFUL VIC1: DEMAND 2025-10-07 → 2016 rows

## 1.3. RAW dataframes list

In [53]:
facilities_df

,name,network_id,network_region,description,location,code,units,created_at,updated_at
0,Adelaide Desalination,NEM,SA1,"<p>The Adelaide Desalination plant (ADP), form...","{'lat': -35.096948, 'lng': 138.484061}",ADP,"[{'code': 'ADPPV1', 'fueltech_id': 'solar_util...",2023-10-18T04:34:30Z,2025-08-05T06:08:12Z
1,Albany,WEM,WEM,<p>Albany wind and Grasmere farms are two wind...,"{'lat': -35.065835, 'lng': 117.797506}",ALBANY,"[{'code': 'ALBANY_WF1', 'fueltech_id': 'wind',...",2023-10-18T04:34:30Z,2025-08-11T02:03:13Z
2,Aldoga,NEM,QLD1,<p>The Aldoga Solar Farm will be approximately...,"{'lat': -23.839544, 'lng': 151.0849}",ALDGASF,"[{'code': 'ALDGASF1', 'fueltech_id': 'solar_ut...",2025-01-31T04:19:33Z,2025-03-25T00:52:44Z
3,Amcor Glass,NEM,SA1,<p></p>,"{'lat': -34.882663, 'lng': 138.577975}",AMCORGR,"[{'code': 'AMCORGR', 'fueltech_id': 'distillat...",2023-10-18T04:34:32Z,2023-10-18T04:34:32Z
4,Angaston,NEM,SA1,<p>Angaston Power Station is a diesel-powered ...,"{'lat': -34.503948, 'lng': 139.024296}",ANGASTON,"[{'code': 'ANGAS1', 'fueltech_id': 'distillate...",2023-10-18T04:34:32Z,2025-09-07T01:53:13Z
...,...,...,...,...,...,...,...,...,...
575,Yarrawonga,NEM,VIC1,<p>Yarrawonga Power Station is adjacent to the...,"{'lat': -36.009466, 'lng': 145.999568}",YWNGAHYD,"[{'code': 'YWNGAHYD', 'fueltech_id': 'hydro', ...",2023-10-18T04:35:33Z,2024-10-29T22:19:53Z
576,Yarwun,NEM,QLD1,<p></p>,"{'lat': -23.8302, 'lng': 151.149692}",YARWUN,"[{'code': 'YARWUN_1', 'fueltech_id': 'gas_ccgt...",2023-10-18T04:35:33Z,2025-07-08T04:17:36Z
577,Yatpool,NEM,VIC1,<p>The 258-hectare Yatpool Solar Farm in north...,"{'lat': -34.38073, 'lng': 142.20534}",YATSF1,"[{'code': 'YATSF1', 'fueltech_id': 'solar_util...",2023-10-18T04:35:33Z,2025-07-08T05:20:08Z
578,Yawong,NEM,VIC1,<p>The Yawong Wind Farm was developed and cons...,"{'lat': -36.471022, 'lng': 143.361722}",YAWWF,"[{'code': 'YAWWF1', 'fueltech_id': 'wind', 'st...",2023-10-18T04:35:33Z,2024-10-30T23:59:54Z
579,Yendon,NEM,VIC1,<p></p>,"{'lat': -37.630952, 'lng': 144.022463}",YENDONWF,"[{'code': 'YENDWF1', 'fueltech_id': 'wind', 's...",2023-10-18T04:35:33Z,2025-07-08T04:27:18Z

In [54]:
power_df_raw

       facility_id unit_code                  timestamp  power_MW
0              ADP        MW  2025-10-01T00:00:00+10:00    -0.004
1              ADP        MW  2025-10-01T00:05:00+10:00    -0.046
2              ADP        MW  2025-10-01T00:10:00+10:00     0.000
3              ADP        MW  2025-10-01T00:15:00+10:00     0.003
4              ADP        MW  2025-10-01T00:20:00+10:00    -0.018
...            ...       ...                        ...       ...
979360    YENDONWF        MW  2025-10-07T23:35:00+10:00    88.630
979361    YENDONWF        MW  2025-10-07T23:40:00+10:00    91.890
979362    YENDONWF        MW  2025-10-07T23:45:00+10:00    89.030
979363    YENDONWF        MW  2025-10-07T23:50:00+10:00    85.830
979364    YENDONWF        MW  2025-10-07T23:55:00+10:00    89.870

[979365 rows x 4 columns]

In [55]:
emissions_df_raw

       facility_id unit_code                  timestamp  emission
0              ADP         t  2025-10-01T00:00:00+10:00       0.0
1              ADP         t  2025-10-01T00:05:00+10:00       0.0
2              ADP         t  2025-10-01T00:10:00+10:00       0.0
3              ADP         t  2025-10-01T00:15:00+10:00       0.0
4              ADP         t  2025-10-01T00:20:00+10:00       0.0
...            ...       ...                        ...       ...
977344    YENDONWF         t  2025-10-07T23:35:00+10:00       0.0
977345    YENDONWF         t  2025-10-07T23:40:00+10:00       0.0
977346    YENDONWF         t  2025-10-07T23:45:00+10:00       0.0
977347    YENDONWF         t  2025-10-07T23:50:00+10:00       0.0
977348    YENDONWF         t  2025-10-07T23:55:00+10:00       0.0

[977349 rows x 4 columns]

In [56]:
market_raw

,timestamp,network,network_region,value_price,unit_price,value_demand,unit_demand
0,2025-10-01T00:00:00+10:00,NEM,NSW1,56.98,$/MWh,7105.57,MW
1,2025-10-01T00:05:00+10:00,NEM,NSW1,80.01,$/MWh,7170.68,MW
2,2025-10-01T00:10:00+10:00,NEM,NSW1,58.40,$/MWh,7158.50,MW
3,2025-10-01T00:15:00+10:00,NEM,NSW1,80.01,$/MWh,7177.80,MW
4,2025-10-01T00:20:00+10:00,NEM,NSW1,65.00,$/MWh,7085.54,MW
...,...,...,...,...,...,...,...
70555,2025-10-07T23:35:00+10:00,NEM,VIC1,104.22,$/MWh,4709.39,MW
70556,2025-10-07T23:40:00+10:00,NEM,VIC1,103.68,$/MWh,4696.86,MW
70557,2025-10-07T23:45:00+10:00,NEM,VIC1,95.86,$/MWh,4639.93,MW
70558,2025-10-07T23:50:00+10:00,NEM,VIC1,95.88,$/MWh,4616.01,MW
70559,2025-10-07T23:55:00+10:00,NEM,VIC1,82.83,$/MWh,4576.42,MW

# 2. DATA INTEGRATION/CLEANING

## 2.1. Cleaning and Combining Power-Emission

Merge facility power and emissions data on facility ID and timestamp. Outer join keeps rows even if power or emissions is missing for a time period

In [57]:
power_emission_raw_stage_1 = pd.merge(
    power_df_raw,
    emissions_df_raw,
    on=['facility_id', 'timestamp'],
    how='outer' 
).sort_values(by=['timestamp','facility_id']).reset_index(drop=True)
print(power_emission_raw_stage_1)

        facility_id unit_code_x                  timestamp  power_MW  \
0             0MREH          MW  2025-10-01T00:00:00+10:00      0.00
1             0MREH          MW  2025-10-01T00:00:00+10:00      0.00
2             0MREH          MW  2025-10-01T00:00:00+10:00      0.00
3             0MREH          MW  2025-10-01T00:00:00+10:00      0.00
4           0MREHA2          MW  2025-10-01T00:00:00+10:00      0.00
...             ...         ...                        ...       ...
1930540     YARANSF          MW  2025-10-07T23:55:00+10:00      0.00
1930541      YARWUN          MW  2025-10-07T23:55:00+10:00    138.99
1930542      YATSF1          MW  2025-10-07T23:55:00+10:00      0.00
1930543    YENDONWF          MW  2025-10-07T23:55:00+10:00     89.87
1930544        YSWF          MW  2025-10-07T23:55:00+10:00     11.60

        unit_code_y  emission
0                 t    0.0000
1                 t    0.0000
2                 t    0.0000
3                 t    0.0000
4                 t    0.0000
...             ...       ...
1930540           t    0.0000
1930541           t    7.1024
1930542           t    0.0000
1930543           t    0.0000
1930544           t    0.0000

[1930545 rows x 6 columns]

Here we :
- Take absolute value of Power since some Power is in -ve which cannot be true for a power plant

- drop redundant columns
- drop rows with 0 in both power and emission

In [58]:
power_emission_raw_stage_1['power_in_MW'] = power_emission_raw_stage_1['power_MW'].abs()
power_emission_raw_stage_1 = power_emission_raw_stage_1[~((power_emission_raw_stage_1['power_MW'] == 0) & (power_emission_raw_stage_1['emission'] == 0))]
power_emission_raw_stage_1 = power_emission_raw_stage_1.drop(columns=[col for col in ['unit_code_x', 'unit_code_y','power_MW'] if col in power_emission_raw_stage_1.columns])


print(power_emission_raw_stage_1.reset_index(drop=True))

        facility_id                  timestamp  emission  power_in_MW
0          0WAMBOWF  2025-10-01T00:00:00+10:00    0.0000       65.230
1               ADP  2025-10-01T00:00:00+10:00    0.0000        0.004
2               ADP  2025-10-01T00:00:00+10:00    0.0000        0.004
3               ADP  2025-10-01T00:00:00+10:00    0.0000        0.004
4               ADP  2025-10-01T00:00:00+10:00    0.0000        0.004
...             ...                        ...       ...          ...
1121424    YALLOURN  2025-10-07T23:55:00+10:00   39.0580        0.000
1121425      YAMBUK  2025-10-07T23:55:00+10:00    0.0000       14.600
1121426      YARWUN  2025-10-07T23:55:00+10:00    7.1024      138.990
1121427    YENDONWF  2025-10-07T23:55:00+10:00    0.0000       89.870
1121428        YSWF  2025-10-07T23:55:00+10:00    0.0000       11.600

[1121429 rows x 4 columns]

In [59]:

# Round to 3 decimal places (numeric precision)
power_emission_raw_stage_1["power_in_MW"] = power_emission_raw_stage_1["power_in_MW"].round(3)
power_emission_raw_stage_1["emission"] = power_emission_raw_stage_1["emission"].round(3)

# Format to always show exactly 3 decimal places
power_emission_raw_stage_1["power_in_MW"] = power_emission_raw_stage_1["power_in_MW"].map(lambda x: f"{x:.3f}")
power_emission_raw_stage_1["emission"] = power_emission_raw_stage_1["emission"].map(lambda x: f"{x:.3f}")

# Remove duplicates where timestamp, power, and emission are the same
power_emission_raw_stage_2 = power_emission_raw_stage_1.drop_duplicates(
    subset=["timestamp", "power_in_MW", "emission"]
).reset_index(drop=True)

power_emission_raw_stage_2

       facility_id                  timestamp emission power_in_MW
0         0WAMBOWF  2025-10-01T00:00:00+10:00    0.000      65.230
1              ADP  2025-10-01T00:00:00+10:00    0.000       0.004
2             ARWF  2025-10-01T00:00:00+10:00    0.000      35.400
3             B2PS  2025-10-01T00:00:00+10:00    0.004       0.081
4             B2PS  2025-10-01T00:00:00+10:00    0.000       0.081
...            ...                        ...      ...         ...
691514    YALLOURN  2025-10-07T23:55:00+10:00   39.058     360.562
691515      YAMBUK  2025-10-07T23:55:00+10:00    0.000      14.600
691516      YARWUN  2025-10-07T23:55:00+10:00    7.102     138.990
691517    YENDONWF  2025-10-07T23:55:00+10:00    0.000      89.870
691518        YSWF  2025-10-07T23:55:00+10:00    0.000      11.600

[691519 rows x 4 columns]

## 2.2. Cleaning Facilities

In [60]:
facilities_df

,name,network_id,network_region,description,location,code,units,created_at,updated_at
0,Adelaide Desalination,NEM,SA1,"<p>The Adelaide Desalination plant (ADP), form...","{'lat': -35.096948, 'lng': 138.484061}",ADP,"[{'code': 'ADPPV1', 'fueltech_id': 'solar_util...",2023-10-18T04:34:30Z,2025-08-05T06:08:12Z
1,Albany,WEM,WEM,<p>Albany wind and Grasmere farms are two wind...,"{'lat': -35.065835, 'lng': 117.797506}",ALBANY,"[{'code': 'ALBANY_WF1', 'fueltech_id': 'wind',...",2023-10-18T04:34:30Z,2025-08-11T02:03:13Z
2,Aldoga,NEM,QLD1,<p>The Aldoga Solar Farm will be approximately...,"{'lat': -23.839544, 'lng': 151.0849}",ALDGASF,"[{'code': 'ALDGASF1', 'fueltech_id': 'solar_ut...",2025-01-31T04:19:33Z,2025-03-25T00:52:44Z
3,Amcor Glass,NEM,SA1,<p></p>,"{'lat': -34.882663, 'lng': 138.577975}",AMCORGR,"[{'code': 'AMCORGR', 'fueltech_id': 'distillat...",2023-10-18T04:34:32Z,2023-10-18T04:34:32Z
4,Angaston,NEM,SA1,<p>Angaston Power Station is a diesel-powered ...,"{'lat': -34.503948, 'lng': 139.024296}",ANGASTON,"[{'code': 'ANGAS1', 'fueltech_id': 'distillate...",2023-10-18T04:34:32Z,2025-09-07T01:53:13Z
...,...,...,...,...,...,...,...,...,...
575,Yarrawonga,NEM,VIC1,<p>Yarrawonga Power Station is adjacent to the...,"{'lat': -36.009466, 'lng': 145.999568}",YWNGAHYD,"[{'code': 'YWNGAHYD', 'fueltech_id': 'hydro', ...",2023-10-18T04:35:33Z,2024-10-29T22:19:53Z
576,Yarwun,NEM,QLD1,<p></p>,"{'lat': -23.8302, 'lng': 151.149692}",YARWUN,"[{'code': 'YARWUN_1', 'fueltech_id': 'gas_ccgt...",2023-10-18T04:35:33Z,2025-07-08T04:17:36Z
577,Yatpool,NEM,VIC1,<p>The 258-hectare Yatpool Solar Farm in north...,"{'lat': -34.38073, 'lng': 142.20534}",YATSF1,"[{'code': 'YATSF1', 'fueltech_id': 'solar_util...",2023-10-18T04:35:33Z,2025-07-08T05:20:08Z
578,Yawong,NEM,VIC1,<p>The Yawong Wind Farm was developed and cons...,"{'lat': -36.471022, 'lng': 143.361722}",YAWWF,"[{'code': 'YAWWF1', 'fueltech_id': 'wind', 'st...",2023-10-18T04:35:33Z,2024-10-30T23:59:54Z
579,Yendon,NEM,VIC1,<p></p>,"{'lat': -37.630952, 'lng': 144.022463}",YENDONWF,"[{'code': 'YENDWF1', 'fueltech_id': 'wind', 's...",2023-10-18T04:35:33Z,2025-07-08T04:27:18Z

In [62]:
# Step 1: Drop unwanted columns 
facilities_df_stage_1 = facilities_df.drop(columns=['description', 'created_at', 'updated_at'], errors='ignore')

# Step 2: Split 'location' dict into latitude and longitude
# If 'location' is a string, convert to dict first
facilities_df_stage_1['location'] = facilities_df_stage_1['location'].apply(
    lambda x: ast.literal_eval(x) if isinstance(x, str) else x
)
facilities_df_stage_1['latitude'] = facilities_df_stage_1['location'].apply(lambda x: x.get('lat') if isinstance(x, dict) else None)
facilities_df_stage_1['longitude'] = facilities_df_stage_1['location'].apply(lambda x: x.get('lng') if isinstance(x, dict) else None)
facilities_df_stage_1 = facilities_df_stage_1.drop(columns=['location'])

#  Clean 'network_region' (remove trailing '1') 
facilities_df_stage_1['network_region'] = facilities_df_stage_1['network_region'].str.replace(r'1$', '', regex=True)

# Step 4: Extract first 'fueltech_id' from 'units' list 
# Convert stringified lists to Python lists (if needed)
facilities_df_stage_1['units'] = facilities_df_stage_1['units'].apply(
    lambda x: ast.literal_eval(x) if isinstance(x, str) else x
)
facilities_df_stage_1['fuel_source'] = facilities_df_stage_1['units'].apply(
    lambda x: x[0]['fueltech_id'] if isinstance(x, list) and len(x) > 0 else None
)

# Optional: Drop original 'units' column if no longer needed
#facilities_df_stage_1 = facilities_df_stage_1.drop(columns=['units'])

# Final cleaned DataFrame
print(facilities_df_stage_1)

                      name network_id network_region      code  \
0    Adelaide Desalination        NEM             SA       ADP
1                   Albany        WEM            WEM    ALBANY
2                   Aldoga        NEM            QLD   ALDGASF
3              Amcor Glass        NEM             SA   AMCORGR
4                 Angaston        NEM             SA  ANGASTON
..                     ...        ...            ...       ...
575             Yarrawonga        NEM            VIC  YWNGAHYD
576                 Yarwun        NEM            QLD    YARWUN
577                Yatpool        NEM            VIC    YATSF1
578                 Yawong        NEM            VIC     YAWWF
579                 Yendon        NEM            VIC  YENDONWF

                                                 units   latitude   longitude  \
0    [{'code': 'ADPPV1', 'fueltech_id': 'solar_util... -35.096948  138.484061
1    [{'code': 'ALBANY_WF1', 'fueltech_id': 'wind',... -35.065835  117.797506
2    [{'code': 'ALDGASF1', 'fueltech_id': 'solar_ut... -23.839544  151.084900
3    [{'code': 'AMCORGR', 'fueltech_id': 'distillat... -34.882663  138.577975
4    [{'code': 'ANGAS1', 'fueltech_id': 'distillate... -34.503948  139.024296
..                                                 ...        ...         ...
575  [{'code': 'YWNGAHYD', 'fueltech_id': 'hydro', ... -36.009466  145.999568
576  [{'code': 'YARWUN_1', 'fueltech_id': 'gas_ccgt... -23.830200  151.149692
577  [{'code': 'YATSF1', 'fueltech_id': 'solar_util... -34.380730  142.205340
578  [{'code': 'YAWWF1', 'fueltech_id': 'wind', 'st... -36.471022  143.361722
579  [{'code': 'YENDWF1', 'fueltech_id': 'wind', 's... -37.630952  144.022463

       fuel_source
0    solar_utility
1             wind
2    solar_utility
3       distillate
4       distillate
..             ...
575          hydro
576       gas_ccgt
577  solar_utility
578           wind
579           wind

[580 rows x 8 columns]

## 2.3. Combine facilities and power-emission

Left-Join facility attributes (name, region, location etc.) onto the power-emissions data

In [63]:
power_emission_raw_stage_3 = pd.merge(
    power_emission_raw_stage_2,
    facilities_df_stage_1,
    how='left',
    left_on='facility_id',
    right_on='code'
)

In [64]:
power_emission_raw_stage_3

,facility_id,timestamp,emission,power_in_MW,name,network_id,network_region,code,units,latitude,longitude,fuel_source
0,0WAMBOWF,2025-10-01T00:00:00+10:00,0.000,65.230,Wambo,NEM,QLD,0WAMBOWF,"[{'code': '0WAMBOWF2', 'fueltech_id': 'wind', ...",-26.603045,151.246876,wind
1,ADP,2025-10-01T00:00:00+10:00,0.000,0.004,Adelaide Desalination,NEM,SA,ADP,"[{'code': 'ADPPV1', 'fueltech_id': 'solar_util...",-35.096948,138.484061,solar_utility
2,ARWF,2025-10-01T00:00:00+10:00,0.000,35.400,Ararat,NEM,VIC,ARWF,"[{'code': 'ARWF1', 'fueltech_id': 'wind', 'sta...",-37.263393,143.082116,wind
3,B2PS,2025-10-01T00:00:00+10:00,0.004,0.081,Braemar 2,NEM,QLD,B2PS,"[{'code': 'BRAEMAR7', 'fueltech_id': 'gas_ocgt...",-27.109873,150.907653,gas_ocgt
4,B2PS,2025-10-01T00:00:00+10:00,0.000,0.081,Braemar 2,NEM,QLD,B2PS,"[{'code': 'BRAEMAR7', 'fueltech_id': 'gas_ocgt...",-27.109873,150.907653,gas_ocgt
...,...,...,...,...,...,...,...,...,...,...,...,...
691514,YALLOURN,2025-10-07T23:55:00+10:00,39.058,360.562,Yallourn W,NEM,VIC,YALLOURN,"[{'code': 'YWPS1', 'fueltech_id': 'coal_brown'...",-38.177596,146.347508,coal_brown
691515,YAMBUK,2025-10-07T23:55:00+10:00,0.000,14.600,Yambuk,NEM,VIC,YAMBUK,"[{'code': 'YAMBUKWF', 'fueltech_id': 'wind', '...",-38.305278,142.018439,wind
691516,YARWUN,2025-10-07T23:55:00+10:00,7.102,138.990,Yarwun,NEM,QLD,YARWUN,"[{'code': 'YARWUN_1', 'fueltech_id': 'gas_ccgt...",-23.830200,151.149692,gas_ccgt
691517,YENDONWF,2025-10-07T23:55:00+10:00,0.000,89.870,Yendon,NEM,VIC,YENDONWF,"[{'code': 'YENDWF1', 'fueltech_id': 'wind', 's...",-37.630952,144.022463,wind
691518,YSWF,2025-10-07T23:55:00+10:00,0.000,11.600,Yaloak South,NEM,VIC,YSWF,"[{'code': 'YSWF1', 'fueltech_id': 'wind', 'sta...",-37.716474,144.241947,wind

In [65]:
power_emission_raw_stage_4 = power_emission_raw_stage_3.drop(columns=["network_id", "code"])
print(power_emission_raw_stage_4)

       facility_id                  timestamp emission power_in_MW  \
0         0WAMBOWF  2025-10-01T00:00:00+10:00    0.000      65.230
1              ADP  2025-10-01T00:00:00+10:00    0.000       0.004
2             ARWF  2025-10-01T00:00:00+10:00    0.000      35.400
3             B2PS  2025-10-01T00:00:00+10:00    0.004       0.081
4             B2PS  2025-10-01T00:00:00+10:00    0.000       0.081
...            ...                        ...      ...         ...
691514    YALLOURN  2025-10-07T23:55:00+10:00   39.058     360.562
691515      YAMBUK  2025-10-07T23:55:00+10:00    0.000      14.600
691516      YARWUN  2025-10-07T23:55:00+10:00    7.102     138.990
691517    YENDONWF  2025-10-07T23:55:00+10:00    0.000      89.870
691518        YSWF  2025-10-07T23:55:00+10:00    0.000      11.600

                         name network_region  \
0                       Wambo            QLD
1       Adelaide Desalination             SA
2                      Ararat            VIC
3                   Braemar 2            QLD
4                   Braemar 2            QLD
...                       ...            ...
691514             Yallourn W            VIC
691515                 Yambuk            VIC
691516                 Yarwun            QLD
691517                 Yendon            VIC
691518           Yaloak South            VIC

                                                    units   latitude  \
0       [{'code': '0WAMBOWF2', 'fueltech_id': 'wind', ... -26.603045
1       [{'code': 'ADPPV1', 'fueltech_id': 'solar_util... -35.096948
2       [{'code': 'ARWF1', 'fueltech_id': 'wind', 'sta... -37.263393
3       [{'code': 'BRAEMAR7', 'fueltech_id': 'gas_ocgt... -27.109873
4       [{'code': 'BRAEMAR7', 'fueltech_id': 'gas_ocgt... -27.109873
...                                                   ...        ...
691514  [{'code': 'YWPS1', 'fueltech_id': 'coal_brown'... -38.177596
691515  [{'code': 'YAMBUKWF', 'fueltech_id': 'wind', '... -38.305278
691516  [{'code': 'YARWUN_1', 'fueltech_id': 'gas_ccgt... -23.830200
691517  [{'code': 'YENDWF1', 'fueltech_id': 'wind', 's... -37.630952
691518  [{'code': 'YSWF1', 'fueltech_id': 'wind', 'sta... -37.716474

         longitude    fuel_source
0       151.246876           wind
1       138.484061  solar_utility
2       143.082116           wind
3       150.907653       gas_ocgt
4       150.907653       gas_ocgt
...            ...            ...
691514  146.347508     coal_brown
691515  142.018439           wind
691516  151.149692       gas_ccgt
691517  144.022463           wind
691518  144.241947           wind

[691519 rows x 10 columns]

For Final Cleanup, we drop duplicates

In [66]:

power_emission_final = power_emission_raw_stage_4.drop_duplicates(
    subset=['facility_id', 'timestamp'],
    keep='first'  # or 'last' if you want to keep the last occurrence
)

# Optional: reset index
power_emission_final.reset_index(drop=True, inplace=True)

## 2.4. Price and Demand Cleanup

Clean Up Per Market Price and Demand

In [70]:
market_raw_stage_1 =market_raw

In [71]:
# Remove the trailing '1' from region codes (e.g., 'NSW1' to 'NSW')
market_raw_stage_1['network_region'] = market_raw_stage_1['network_region'].str.replace(r'1$', '', regex=True)

In [72]:
# Remove duplicate timestamp rows to avoid double counting price/demand
market_raw_stage_1 = market_raw_stage_1.drop_duplicates(
    subset=["timestamp", "value_price", "value_demand"]
).reset_index(drop=True)


# Drop network column (not needed after region-level aggregation)
market_raw_stage_2 = market_raw_stage_1.drop(columns=["network"])

# Rename metric columns and drop unit columns since units are implied
market_raw_stage_2 = market_raw_stage_2.rename(
    columns={
        "value_price": "value_price_in_$/MWh",
        "value_demand": "value_demand_in_MW"
    }
).drop(columns=["unit_price", "unit_demand"])
# Force all price and demand values to positive (market data sometimes returns signed numbers)
market_raw_stage_2["value_price_in_$/MWh"] = market_raw_stage_2["value_price_in_$/MWh"].abs()
market_raw_stage_2["value_demand_in_MW"] = market_raw_stage_2["value_demand_in_MW"].abs()

In [73]:
# Sort market data chronologically and by region for consistent merging
market_raw_stage_3 = market_raw_stage_2.sort_values(
    by=["timestamp", "network_region"]
).reset_index(drop=True)

## 2.5. Merging Power and Market Datasets

In [75]:
# Merge facility time-series data with market price & demand based on timestamp and region
merged_df = pd.merge(
    power_emission_final,market_raw_stage_3
    [["timestamp", "network_region", "value_price_in_$/MWh", "value_demand_in_MW"]],
    on=["timestamp", "network_region"],
    how="left"
)

# Quick sanity check
print("Merged shape:", merged_df.shape)
merged_df.head(5)

Merged shape: (406845, 12)

,facility_id,timestamp,emission,power_in_MW,name,network_region,units,latitude,longitude,fuel_source,value_price_in_$/MWh,value_demand_in_MW
0,0WAMBOWF,2025-10-01T00:00:00+10:00,0.000,65.230,Wambo,QLD,"[{'code': '0WAMBOWF2', 'fueltech_id': 'wind', ...",-26.603045,151.246876,wind,54.82,5989.24
1,ADP,2025-10-01T00:00:00+10:00,0.000,0.004,Adelaide Desalination,SA,"[{'code': 'ADPPV1', 'fueltech_id': 'solar_util...",-35.096948,138.484061,solar_utility,8.11,1564.92
2,ARWF,2025-10-01T00:00:00+10:00,0.000,35.400,Ararat,VIC,"[{'code': 'ARWF1', 'fueltech_id': 'wind', 'sta...",-37.263393,143.082116,wind,8.95,4893.49
3,B2PS,2025-10-01T00:00:00+10:00,0.004,0.081,Braemar 2,QLD,"[{'code': 'BRAEMAR7', 'fueltech_id': 'gas_ocgt...",-27.109873,150.907653,gas_ocgt,54.82,5989.24
4,BANGOWF,2025-10-01T00:00:00+10:00,0.000,97.699,Bango,NSW,"[{'code': 'BANGOWF1', 'fueltech_id': 'wind', '...",-34.767208,148.921499,wind,56.98,7105.57

In [76]:
# Save to a new CSV for use in Stage 3
merged_df.to_csv("power_emission.csv", index=False)

# 3. Data Publishing via MQTT

## 3.1. MQTT configs and setup

In [2]:
MQTT_BROKER = "test.mosquitto.org"
MQTT_PORT   = 1883
TOPIC_POWER = "470461201/A2"  # topic for pub./sub
PUBLISH_DELAY = 0.1         # seconds between messages  
RELOAD_DELAY  = 0          # seconds to wait between rounds when REPEAT=True
END_WAIT_SECS = 60           # wait before replay restart
REPEAT = True                # keep publishing in a loop

## 3.2. Transforming Facilities Unit Data

Parsing and Extracting Unit Codes from Facility Metadata

In [3]:
def parse_units_codes(units_cell):
    """Return ONLY the 'code' values from the 'units' JSON."""
    if units_cell is None or (isinstance(units_cell, float) and pd.isna(units_cell)):
        return []
    obj = units_cell
    # If stored as a string (JSON or Python literal), try to parse it
    if isinstance(units_cell, str):
        s = units_cell.strip()
        if not s:
            return []
        try:
            obj = json.loads(s) #JSON
        except Exception:
            try:
                obj = ast.literal_eval(s) #Python
            except Exception:
                return []
    # Ensure we are working with a list of dicts
    if isinstance(obj, dict):
        obj = [obj]
    if not isinstance(obj, (list, tuple)):
        return []
    return [str(d.get("code")) for d in obj if isinstance(d, dict) and d.get("code")]

CSV_PATH = "power_emission.csv"
power_df = pd.read_csv(CSV_PATH)

# Extract clean list of codes and a display-friendly string
power_df["unit_codes"] = power_df["units"].apply(parse_units_codes)
power_df["unit_codes_str"] = power_df["unit_codes"].apply(lambda xs: ", ".join(xs) if xs else "—")

display(power_df[["facility_id","name","unit_codes","unit_codes_str"]].head(5))
# Ensure timestamps are datetime objects
power_df["timestamp"] = pd.to_datetime(power_df["timestamp"])

,facility_id,name,unit_codes,unit_codes_str
0,0WAMBOWF,Wambo,"[0WAMBOWF2, WAMBOWF1]","0WAMBOWF2, WAMBOWF1"
1,ADP,Adelaide Desalination,"[ADPPV1, ADPPV2, ADPPV3, ADPBA1G, ADPBA1L, ADP...","ADPPV1, ADPPV2, ADPPV3, ADPBA1G, ADPBA1L, ADPBA1"
2,ARWF,Ararat,[ARWF1],ARWF1
3,B2PS,Braemar 2,"[BRAEMAR7, BRAEMAR5, BRAEMAR6]","BRAEMAR7, BRAEMAR5, BRAEMAR6"
4,BANGOWF,Bango,"[BANGOWF1, BANGOWF2]","BANGOWF1, BANGOWF2"

Initializing MQTT Client and Publish Callback

In [4]:
client = mqtt.Client()
client.connect(MQTT_BROKER, MQTT_PORT, 60)
client.loop_start()

def on_publish(client, userdata, mid):
    print(f"MQTT message with mid={mid} successfully published.")

client.on_publish = on_publish

/var/folders/tv/ly87y_cd5vzcqrw28_rhj9t40000gn/T/ipykernel_37832/3426122455.py:1: DeprecationWarning: Callback API version 1 is deprecated, update to latest version
  client = mqtt.Client()

## 3.3. Publisher Setup (5. Continuous Execution)

Publishing Time-Series Power and Emissions Data as MQTT Stream. Duplicaton Avoided and Continuous Execution Executed

In [5]:
def publish_stream(power_df, delay_between_messages=PUBLISH_DELAY, delay_between_timestamps=RELOAD_DELAY):
    all_timestamps = sorted(power_df["timestamp"].unique())

    #remember last (power, emission) per facility for the current run
    last_seen = {}  # facility_id -> (power_val, emission_val)
    EPS = 1e-6      # small tolerance for float equality

    for ts in all_timestamps:
        print(f"\nPublishing data for timestamp: {ts}")

        # Pulling and Sending Data
        subset_power = power_df[power_df["timestamp"] == ts]
        for _, row in subset_power.iterrows():
            # Parse values
            power_val     = float(row.get("power_in_MW", 0) or 0)
            emission_val  = float(row.get("emission",   0) or 0)
            facility_id   = row.get("facility_id")

            # Skip rows with both zero
            if power_val == 0 and emission_val == 0:
                continue

            #skip if duplicate vs previous timestamp for the same facility
            prev = last_seen.get(facility_id)
            if prev is not None:
                p_prev, e_prev = prev
                if math.isclose(power_val, p_prev, rel_tol=0.0, abs_tol=EPS) and \
                   math.isclose(emission_val, e_prev, rel_tol=0.0, abs_tol=EPS):

                    continue

            # Message Data
            msg_power = {
                "facility_id": row["facility_id"],
                "name": row["name"],
                "timestamp": str(row["timestamp"]),
                "power_MW": power_val,
                "emissions_tCO2": emission_val,
                "network_region": row["network_region"],
                "fuel_source": row["fuel_source"],
                "latitude": float(row["latitude"]),
                "longitude": float(row["longitude"]),
                "value_price_in_$/MWh": float(row.get("value_price_in_$/MWh")),
                "value_demand_in_MW": float(row.get("value_demand_in_MW")),
                "unit_codes": row.get("unit_codes"),
                "unit_codes_str": row.get("unit_codes_str"),
            }

            client.publish(TOPIC_POWER, json.dumps(msg_power))
            print(f"  Power published: {msg_power['facility_id']} ({msg_power['power_MW']} MW)")

            #update last seen AFTER a publish
            last_seen[facility_id] = (power_val, emission_val)

            # Delay between messages is 0.1s
            time.sleep(delay_between_messages)

        # Delay between timestamp batches
        print(f"Finished timestamp {ts}. Waiting {delay_between_timestamps}s before next batch...")
        time.sleep(delay_between_timestamps)

    # Continuous Execution (replay)
    if REPEAT:
        print(f"End of data reached. Waiting {END_WAIT_SECS}s before restarting...")
        time.sleep(END_WAIT_SECS)
        #call the function again to simulate unbounded data
        publish_stream(power_df)
    return

## 3.4. Running Publisher

Publishing the Data

In [6]:
try:
    publish_stream(power_df)
except KeyboardInterrupt:
    print("\n Streaming stopped by user.")
finally:
    client.loop_stop()
    client.disconnect()
    print(" MQTT client disconnected")

Publishing data for timestamp: 2025-10-01 00:00:00+10:00
  Power published: 0WAMBOWF (65.23 MW)
MQTT message with mid=1 successfully published.
  Power published: ADP (0.004 MW)
MQTT message with mid=2 successfully published.
  Power published: ARWF (35.4 MW)
MQTT message with mid=3 successfully published.
  Power published: B2PS (0.081 MW)
MQTT message with mid=4 successfully published.
  Power published: BANGOWF (97.699 MW)
MQTT message with mid=5 successfully published.
  Power published: BARCSF (0.1 MW)MQTT message with mid=6 successfully published.

  Power published: BASTYAN (57.1 MW)MQTT message with mid=7 successfully published.

  Power published: BAYSW (558.395 MW)MQTT message with mid=8 successfully published.

  Power published: BBATTERY (0.015 MW)
MQTT message with mid=9 successfully published.
  Power published: BHB (2.194 MW)
MQTT message with mid=10 successfully published.
  Power published: BHWF (7.764 MW)MQTT message with mid=11 successfully published.

  Power published: BIALAWF (69.172 MW)
MQTT message with mid=12 successfully published.
  Power published: BLUEGSF (0.101 MW)MQTT message with mid=13 successfully published.

  Power published: BLUFF (46.5 MW)
MQTT message with mid=14 successfully published.
  Power published: BLYTHB (0.44 MW)MQTT message with mid=15 successfully published.

  Power published: BOCOROCK (54.23 MW)
MQTT message with mid=16 successfully published.
  Power published: BODWF (45.192 MW)
MQTT message with mid=17 successfully published.
  Power published: BRNDBES (0.137 MW)
MQTT message with mid=18 successfully published.
  Power published: BRYB1WF1 (126.879 MW)MQTT message with mid=19 successfully published.

  Power published: BULGANA (0.13 MW)
MQTT message with mid=20 successfully published.
  Power published: BUTLERSG (6.4 MW)MQTT message with mid=21 successfully published.

  Power published: BWTR1 (25.322 MW)
MQTT message with mid=22 successfully published.
  Power published: CALLIDEC1 (0.0 MW)
MQTT message with mid=23 successfully published.
  Power published: CALL_B (279.2 MW)
MQTT message with mid=24 successfully published.
  Power published: CANUNDA1 (26.931 MW)MQTT message with mid=25 successfully published.

  Power published: CAPBES (1.25 MW)
MQTT message with mid=26 successfully published.
  Power published: CAPTL_WF (114.295 MW)MQTT message with mid=27 successfully published.

  Power published: CATHROCK (40.0 MW)
MQTT message with mid=28 successfully published.
  Power published: CBWWBA (0.002 MW)MQTT message with mid=29 successfully published.

  Power published: CETHANA (47.47 MW)MQTT message with mid=30 successfully published.

  Power published: CHALLWF (26.7 MW)
MQTT message with mid=31 successfully published.
  Power published: CHBESS (0.039 MW)
MQTT message with mid=32 successfully published.
  Power published: CHYTWF (11.31 MW)
MQTT message with mid=33 successfully published.
  Power published: CLEMGPWF (50.641 MW)
MQTT message with mid=34 successfully published.
  Power published: CLRKCWF (296.108 MW)MQTT message with mid=35 successfully published.

  Power published: CLUNY (18.064 MW)MQTT message with mid=36 successfully published.

  Power published: COLWF01 (115.956 MW)
MQTT message with mid=37 successfully published.
  Power published: CONDONG1 (20.88 MW)MQTT message with mid=38 successfully published.

  Power published: COOPGWF (328.52 MW)
MQTT message with mid=39 successfully published.
  Power published: CROOKWF2 (76.613 MW)
MQTT message with mid=40 successfully published.
  Power published: CROOKWF3 (41.543 MW)
MQTT message with mid=41 successfully published.
  Power published: CROWLWF (58.264 MW)MQTT message with mid=42 successfully published.

  Power published: CRURWF1 (124.897 MW)MQTT message with mid=43 successfully published.

  Power published: CTHLWF (14.261 MW)
MQTT message with mid=44 successfully published.
  Power published: CULLERIN (24.09 MW)MQTT message with mid=45 successfully published.

  Power published: DALNTH (0.084 MW)
MQTT message with mid=46 successfully published.
  Power published: DARTM (109.8 MW)MQTT message with mid=47 successfully published.

  Power published: DEVILS_G (46.112 MW)
MQTT message with mid=48 successfully published.
  Power published: DIAPURWF (7.3 MW)MQTT message with mid=49 successfully published.

  Power published: DPNTB (0.049 MW)
MQTT message with mid=50 successfully published.
  Power published: DULAWF (172.8 MW)MQTT message with mid=51 successfully published.

  Power published: DUNDWF (77.28 MW)
MQTT message with mid=52 successfully published.
  Power published: EILDON (47.0 MW)MQTT message with mid=53 successfully published.

  Power published: ELAINEWF (38.66 MW)MQTT message with mid=54 successfully published.

  Power published: ERARING (463.862 MW)
MQTT message with mid=55 successfully published.
  Power published: ERB (1.086 MW)MQTT message with mid=56 successfully published.

  Power published: FISHER (44.87 MW)
MQTT message with mid=57 successfully published.
  Power published: FLYCRKWF (8.72 MW)
MQTT message with mid=58 successfully published.
  Power published: GANNBESS (0.29 MW)MQTT message with mid=59 successfully published.

  Power published: GERMCRK (16.488 MW)
MQTT message with mid=60 successfully published.
  Power published: GORDON (24.423 MW)
MQTT message with mid=61 successfully published.
  Power published: GPWFEST (148.88 MW)
MQTT message with mid=62 successfully published.
  Power published: GRANWF (31.22 MW)
MQTT message with mid=63 successfully published.
  Power published: GREENB (0.045 MW)
MQTT message with mid=64 successfully published.
  Power published: GSTONE (149.769 MW)
MQTT message with mid=65 successfully published.
  Power published: GSWF (200.66 MW)MQTT message with mid=66 successfully published.

  Power published: GULLRGWF (119.063 MW)
MQTT message with mid=67 successfully published.
  Power published: GUNNING (34.678 MW)MQTT message with mid=68 successfully published.

  Power published: HALLWF (74.15 MW)
MQTT message with mid=69 successfully published.
  Power published: HALLWF2 (56.52 MW)MQTT message with mid=70 successfully published.

  Power published: HBESS (0.3 MW)MQTT message with mid=71 successfully published.

  Power published: HD1WF (45.06 MW)
MQTT message with mid=72 successfully published.
  Power published: HORNSDAL (90.3 MW)
MQTT message with mid=73 successfully published.
  Power published: HORNSDAL2 (96.5 MW)
MQTT message with mid=74 successfully published.
  Power published: HORNSDAL3 (107.6 MW)MQTT message with mid=75 successfully published.

  Power published: HORNSDPR (8.2 MW)
MQTT message with mid=76 successfully published.
  Power published: HUMENSW (21.028 MW)
MQTT message with mid=77 successfully published.
  Power published: HVWW (0.009 MW)
MQTT message with mid=78 successfully published.
  Power published: JEERB (0.1 MW)MQTT message with mid=79 successfully published.

  Power published: KABANWF (110.789 MW)MQTT message with mid=80 successfully published.

  Power published: KAREEYA (21.445 MW)
MQTT message with mid=81 successfully published.
  Power published: KESS1 (2.23 MW)
MQTT message with mid=82 successfully published.
  Power published: KIATAWF (29.3 MW)MQTT message with mid=83 successfully published.

  Power published: KOGANCK (719.94 MW)
MQTT message with mid=84 successfully published.
  Power published: LADBROKE (0.01 MW)
MQTT message with mid=85 successfully published.
  Power published: LBBESS (0.15 MW)
MQTT message with mid=86 successfully published.
  Power published: LEM_WIL (86.928 MW)MQTT message with mid=87 successfully published.

  Power published: LGAPWF1 (49.33 MW)
MQTT message with mid=88 successfully published.
  Power published: LI_WY_CA (154.484 MW)MQTT message with mid=89 successfully published.

  Power published: LKBONNY1 (41.975 MW)
MQTT message with mid=90 successfully published.
  Power published: LKBONNY3 (16.747 MW)MQTT message with mid=91 successfully published.

  Power published: LKBONNY_2 (87.009 MW)MQTT message with mid=92 successfully published.

  Power published: LOYYANGA (415.0 MW)
MQTT message with mid=93 successfully published.
  Power published: LOYYB (451.5 MW)
MQTT message with mid=94 successfully published.

  Power published: MACARTH (126.2 MW)
MQTT message with mid=95 successfully published.
  Power published: MACKNTSH (51.81 MW)
MQTT message with mid=96 successfully published.
  Power published: MANNUMB (0.18 MW)
MQTT message with mid=97 successfully published.
  Power published: MBAHNTH (20.2 MW)
MQTT message with mid=98 successfully published.
  Power published: MCINTYR (139.076 MW)
MQTT message with mid=99 successfully published.
  Power published: MCKAY (0.02 MW)MQTT message with mid=100 successfully published.

  Power published: MEADOWBK (43.442 MW)MQTT message with mid=101 successfully published.

  Power published: MEWF (49.5 MW)
MQTT message with mid=102 successfully published.
  Power published: MILLMERN (0.0 MW)MQTT message with mid=103 successfully published.

  Power published: MINTARO (0.085 MW)
MQTT message with mid=104 successfully published.
  Power published: MLSP (0.013 MW)
MQTT message with mid=105 successfully published.
  Power published: MLWF (11.55 MW)
MQTT message with mid=106 successfully published.
  Power published: MOORAWF1 (248.89 MW)
MQTT message with mid=107 successfully published.
  Power published: MP (448.847 MW)MQTT message with mid=108 successfully published.

  Power published: MRTLSWF (89.57 MW)MQTT message with mid=109 successfully published.

  Power published: MTGELWF (59.523 MW)
MQTT message with mid=110 successfully published.
  Power published: MTMERCER (78.1 MW)MQTT message with mid=111 successfully published.

  Power published: MTMILLAR (34.0 MW)
MQTT message with mid=112 successfully published.
  Power published: MUSSELRO (46.0 MW)
MQTT message with mid=113 successfully published.
  Power published: MUWAWF (202.65 MW)MQTT message with mid=114 successfully published.

  Power published: NBHWF (106.2 MW)MQTT message with mid=115 successfully published.

  Power published: OAKLAND (34.4 MW)MQTT message with mid=116 successfully published.

  Power published: PALOONA (29.41 MW)MQTT message with mid=117 successfully published.

  Power published: PAREPW (48.43 MW)
MQTT message with mid=118 successfully published.
  Power published: PIONEER (43.2 MW)
MQTT message with mid=119 successfully published.
  Power published: PORTWF (59.0 MW)MQTT message with mid=120 successfully published.

  Power published: PTINA (3.31 MW)MQTT message with mid=121 successfully published.

  Power published: QBYNB (0.176 MW)
MQTT message with mid=122 successfully published.
  Power published: RANGEB (0.05 MW)MQTT message with mid=123 successfully published.

  Power published: REECE (118.87 MW)
MQTT message with mid=124 successfully published.
  Power published: REPULSE (32.886 MW)
MQTT message with mid=125 successfully published.
  Power published: RESS (0.68 MW)
MQTT message with mid=126 successfully published.
  Power published: RIVNB (0.115 MW)
MQTT message with mid=127 successfully published.
  Power published: ROWALLAN (0.005 MW)
MQTT message with mid=128 successfully published.
  Power published: ROYALLA (0.001 MW)
MQTT message with mid=129 successfully published.
  Power published: RPCG (13.8 MW)
MQTT message with mid=130 successfully published.
  Power published: RUBICON (0.585 MW)
MQTT message with mid=131 successfully published.
  Power published: RYANCWF (75.16 MW)MQTT message with mid=132 successfully published.

  Power published: RYEPARK (202.695 MW)MQTT message with mid=133 successfully published.

  Power published: SALTCRK (15.35 MW)
MQTT message with mid=134 successfully published.
  Power published: SAPHWF1 (233.248 MW)MQTT message with mid=135 successfully published.

  Power published: SHOAL (43.47 MW)
MQTT message with mid=136 successfully published.
  Power published: SMTHBES1 (0.046 MW)
MQTT message with mid=137 successfully published.
  Power published: SNOWNTH (126.7 MW)
MQTT message with mid=138 successfully published.
  Power published: SNOWSTH (114.5 MW)
MQTT message with mid=139 successfully published.
  Power published: SNOWTOWN (92.586 MW)MQTT message with mid=140 successfully published.

  Power published: SNOWY3 (61.8 MW)
MQTT message with mid=141 successfully published.
  Power published: SNOWY6 (52.6 MW)
MQTT message with mid=142 successfully published.
  Power published: STANWELL (245.23 MW)MQTT message with mid=143 successfully published.

  Power published: STARFHILL (6.698 MW)MQTT message with mid=144 successfully published.

  Power published: STOCKYD (337.78 MW)MQTT message with mid=145 successfully published.

  Power published: STWF (136.271 MW)MQTT message with mid=146 successfully published.

  Power published: SWAN_E (0.58 MW)
MQTT message with mid=147 successfully published.
  Power published: TARALGA (48.698 MW)MQTT message with mid=148 successfully published.

  Power published: TARONG (0.6 MW)
MQTT message with mid=149 successfully published.
  Power published: TARONGN (278.5 MW)MQTT message with mid=150 successfully published.

  Power published: TARRALEA (59.7 MW)
MQTT message with mid=151 successfully published.
  Power published: TB2SF (0.347 MW)
MQTT message with mid=152 successfully published.
  Power published: TIB (4.55 MW)MQTT message with mid=153 successfully published.

  Power published: TORRIS (0.0 MW)
MQTT message with mid=154 successfully published.
  Power published: TULLYSM (9.9 MW)
MQTT message with mid=155 successfully published.
  Power published: TUNGATIN (80.25 MW)MQTT message with mid=156 successfully published.

  Power published: ULBESS (0.6 MW)
MQTT message with mid=157 successfully published.
  Power published: VP (0.0 MW)
MQTT message with mid=158 successfully published.
  Power published: WALGRV (0.209 MW)
MQTT message with mid=159 successfully published.
  Power published: WANDBG (2.246 MW)
MQTT message with mid=160 successfully published.
  Power published: WATERLWF (103.5 MW)
MQTT message with mid=161 successfully published.
  Power published: WAUBRAWF (53.472 MW)
MQTT message with mid=162 successfully published.
  Power published: WDBESS (0.243 MW)
MQTT message with mid=163 successfully published.
  Power published: WDBESS2 (0.254 MW)
MQTT message with mid=164 successfully published.
  Power published: WGWF (106.9 MW)
MQTT message with mid=165 successfully published.
  Power published: WKIEWA (16.0 MW)
MQTT message with mid=166 successfully published.
  Power published: WOODLWN (13.997 MW)MQTT message with mid=167 successfully published.

  Power published: WOOLNTH1 (25.97 MW)
MQTT message with mid=168 successfully published.
  Power published: WPWF (44.05 MW)
MQTT message with mid=169 successfully published.
  Power published: WRWF1 (36.902 MW)
MQTT message with mid=170 successfully published.
  Power published: YALLOURN (250.75 MW)MQTT message with mid=171 successfully published.

  Power published: YAMBUK (4.9 MW)MQTT message with mid=172 successfully published.

  Power published: YARWUN (85.01 MW)
MQTT message with mid=173 successfully published.
  Power published: YENDONWF (94.95 MW)
MQTT message with mid=174 successfully published.
  Power published: YSWF (20.2 MW)MQTT message with mid=175 successfully published.

Finished timestamp 2025-10-01 00:00:00+10:00. Waiting 0s before next batch...

Publishing data for timestamp: 2025-10-01 00:05:00+10:00
  Power published: 0MREH (1.568 MW)MQTT message with mid=176 successfully published.

  Power published: 0WAMBOWF (64.647 MW)
MQTT message with mid=177 successfully published.
  Power published: ADP (0.046 MW)MQTT message with mid=178 successfully published.

  Power published: ANGASTON (0.1 MW)MQTT message with mid=179 successfully published.

  Power published: ARWF (33.3 MW)MQTT message with mid=180 successfully published.

  Power published: BANGOWF (95.399 MW)MQTT message with mid=181 successfully published.

  Power published: BASTYAN (62.41 MW)
MQTT message with mid=182 successfully published.
  Power published: BAYSW (555.807 MW)MQTT message with mid=183 successfully published.

  Power published: BBATTERY (0.368 MW)
MQTT message with mid=184 successfully published.
  Power published: BHB (2.178 MW)MQTT message with mid=185 successfully published.

  Power published: BHWF (4.476 MW)
MQTT message with mid=186 successfully published.
  Power published: BIALAWF (70.098 MW)MQTT message with mid=187 successfully published.

  Power published: BLYTHB (0.11 MW)
MQTT message with mid=188 successfully published.

  Power published: BOCOROCK (53.98 MW)MQTT message with mid=189 successfully published.

  Power published: BODWF (44.137 MW)
MQTT message with mid=190 successfully published.
  Power published: BOLIVAR (0.003 MW)
MQTT message with mid=191 successfully published.
  Power published: BRYB1WF1 (129.149 MW)
MQTT message with mid=192 successfully published.
  Power published: BULGANA (47.56 MW)MQTT message with mid=193 successfully published.

  Power published: BUTLERSG (6.5 MW)
MQTT message with mid=194 successfully published.
  Power published: BWTR1 (23.836 MW)MQTT message with mid=195 successfully published.

  Power published: CALLIDEC1 (0.0 MW)MQTT message with mid=196 successfully published.

  Power published: CANUNDA1 (34.74 MW)
MQTT message with mid=197 successfully published.
  Power published: CAPBES (0.94 MW)
MQTT message with mid=198 successfully published.
  Power published: CAPTL_WF (115.014 MW)MQTT message with mid=199 successfully published.

  Power published: CATHROCK (38.7 MW)MQTT message with mid=200 successfully published.

  Power published: CBWWBA (0.016 MW)MQTT message with mid=201 successfully published.

  Power published: CETHANA (44.477 MW)
MQTT message with mid=202 successfully published.
  Power published: CHBESS (0.213 MW)MQTT message with mid=203 successfully published.

  Power published: CHYTWF (13.33 MW)
MQTT message with mid=204 successfully published.
  Power published: CLEMGPWF (52.802 MW)MQTT message with mid=205 successfully published.

  Power published: CLRKCWF (288.522 MW)
MQTT message with mid=206 successfully published.
  Power published: CLUNY (18.069 MW)
MQTT message with mid=207 successfully published.
  Power published: COLWF01 (115.151 MW)MQTT message with mid=208 successfully published.

  Power published: CONDONG1 (20.91 MW)MQTT message with mid=209 successfully published.

  Power published: COOPGWF (328.94 MW)
MQTT message with mid=210 successfully published.
  Power published: CROOKWF2 (75.733 MW)
MQTT message with mid=211 successfully published.
  Power published: CROOKWF3 (36.667 MW)
MQTT message with mid=212 successfully published.
  Power published: CROWLWF (60.477 MW)MQTT message with mid=213 successfully published.

  Power published: CRURWF1 (126.397 MW)
MQTT message with mid=214 successfully published.
  Power published: CTHLWF (14.652 MW)
MQTT message with mid=215 successfully published.
  Power published: CULLERIN (24.86 MW)MQTT message with mid=216 successfully published.

  Power published: DALNTH (0.099 MW)MQTT message with mid=217 successfully published.

  Power published: DEVILS_G (34.986 MW)MQTT message with mid=218 successfully published.

  Power published: DPNTB (0.298 MW)
MQTT message with mid=219 successfully published.
  Power published: DULAWF (172.9 MW)MQTT message with mid=220 successfully published.

  Power published: DUNDWF (66.35 MW)MQTT message with mid=221 successfully published.

  Power published: EILDON (47.04 MW)MQTT message with mid=222 successfully published.

  Power published: ELAINEWF (38.49 MW)
MQTT message with mid=223 successfully published.
  Power published: ERARING (440.034 MW)MQTT message with mid=224 successfully published.

  Power published: FISHER (44.94 MW)MQTT message with mid=225 successfully published.

  Power published: FLYCRKWF (9.88 MW)MQTT message with mid=226 successfully published.

  Power published: GANNBESS (0.364 MW)MQTT message with mid=227 successfully published.

  Power published: GERMCRK (16.882 MW)
MQTT message with mid=228 successfully published.
  Power published: GORDON (23.837 MW)
MQTT message with mid=229 successfully published.
  Power published: GPWFEST (162.74 MW)
MQTT message with mid=230 successfully published.
  Power published: GRANWF (30.47 MW)
MQTT message with mid=231 successfully published.
  Power published: GREENB (1.187 MW)
MQTT message with mid=232 successfully published.
  Power published: GRIFSF (0.002 MW)
MQTT message with mid=233 successfully published.
  Power published: GSTONE (150.254 MW)
MQTT message with mid=234 successfully published.
  Power published: GSWF (199.88 MW)MQTT message with mid=235 successfully published.

  Power published: GULLRGWF (122.293 MW)
MQTT message with mid=236 successfully published.
  Power published: GUNNING (32.444 MW)MQTT message with mid=237 successfully published.

  Power published: HALLWF (74.35 MW)MQTT message with mid=238 successfully published.

  Power published: HALLWF2 (56.47 MW)MQTT message with mid=239 successfully published.

  Power published: HBESS (0.2 MW)MQTT message with mid=240 successfully published.

  Power published: HD1WF (43.67 MW)MQTT message with mid=241 successfully published.

  Power published: HORNSDAL (88.1 MW)
MQTT message with mid=242 successfully published.
  Power published: HORNSDAL2 (95.7 MW)
MQTT message with mid=243 successfully published.
  Power published: HORNSDAL3 (101.4 MW)MQTT message with mid=244 successfully published.

  Power published: HORNSDPR (9.0 MW)MQTT message with mid=245 successfully published.

  Power published: HUMENSW (20.997 MW)
MQTT message with mid=246 successfully published.
  Power published: HVWW (0.048 MW)
MQTT message with mid=247 successfully published.
  Power published: KABANWF (120.224 MW)MQTT message with mid=248 successfully published.

  Power published: KAREEYA (21.545 MW)
MQTT message with mid=249 successfully published.
  Power published: KESS1 (1.98 MW)MQTT message with mid=250 successfully published.

  Power published: KIATAWF (29.8 MW)
MQTT message with mid=251 successfully published.
  Power published: KOGANCK (723.23 MW)MQTT message with mid=252 successfully published.

  Power published: LBBESS (5.55 MW)
MQTT message with mid=253 successfully published.
  Power published: LEM_WIL (87.178 MW)
MQTT message with mid=254 successfully published.
  Power published: LGAPWF1 (48.24 MW)MQTT message with mid=255 successfully published.

  Power published: LI_WY_CA (154.715 MW)MQTT message with mid=256 successfully published.

  Power published: LKBONNY1 (45.458 MW)
MQTT message with mid=257 successfully published.
  Power published: LKBONNY3 (17.416 MW)
MQTT message with mid=258 successfully published.
  Power published: LKBONNY_2 (119.535 MW)
MQTT message with mid=259 successfully published.
  Power published: LOYYANGA (407.0 MW)
MQTT message with mid=260 successfully published.
  Power published: LOYYB (452.25 MW)
MQTT message with mid=261 successfully published.
  Power published: MACARTH (121.7 MW)
MQTT message with mid=262 successfully published.
  Power published: MACKNTSH (64.98 MW)
MQTT message with mid=263 successfully published.
  Power published: MBAHNTH (20.5 MW)MQTT message with mid=264 successfully published.

  Power published: MCINTYR (138.961 MW)MQTT message with mid=265 successfully published.

  Power published: MEADOWBK (43.527 MW)
MQTT message with mid=266 successfully published.
  Power published: MEWF (50.393 MW)
MQTT message with mid=267 successfully published.
  Power published: MILLMERN (0.0 MW)MQTT message with mid=268 successfully published.

  Power published: MLWF (11.955 MW)
MQTT message with mid=269 successfully published.
  Power published: MOORAWF1 (231.6 MW)MQTT message with mid=270 successfully published.

  Power published: MP (447.675 MW)
MQTT message with mid=271 successfully published.
  Power published: MRTLSWF (78.69 MW)MQTT message with mid=272 successfully published.

  Power published: MTGELWF (65.781 MW)
MQTT message with mid=273 successfully published.
  Power published: MTMERCER (82.3 MW)
MQTT message with mid=274 successfully published.
  Power published: MTMILLAR (27.8 MW)
MQTT message with mid=275 successfully published.
  Power published: MUSSELRO (41.4 MW)
MQTT message with mid=276 successfully published.
  Power published: MUWAWF (198.16 MW)
MQTT message with mid=277 successfully published.
  Power published: NBHWF (105.7 MW)
MQTT message with mid=278 successfully published.
  Power published: OAKLAND (33.2 MW)MQTT message with mid=279 successfully published.

  Power published: PALOONA (29.97 MW)
MQTT message with mid=280 successfully published.
  Power published: PAREPW (37.06 MW)
MQTT message with mid=281 successfully published.
  Power published: PIBESS (0.038 MW)
MQTT message with mid=282 successfully published.

  Power published: PIONEER (42.7 MW)
MQTT message with mid=283 successfully published.
  Power published: PORTWF (55.9 MW)
MQTT message with mid=284 successfully published.
  Power published: PTINA (3.32 MW)
MQTT message with mid=285 successfully published.
  Power published: RANGEB (0.57 MW)MQTT message with mid=286 successfully published.

  Power published: REECE (118.764 MW)
MQTT message with mid=287 successfully published.
  Power published: REPULSE (33.013 MW)MQTT message with mid=288 successfully published.

  Power published: RESS (0.695 MW)MQTT message with mid=289 successfully published.

  Power published: RIVNB (0.869 MW)
MQTT message with mid=290 successfully published.
  Power published: RYANCWF (74.32 MW)
MQTT message with mid=291 successfully published.
  Power published: RYEPARK (184.803 MW)
MQTT message with mid=292 successfully published.
  Power published: SALTCRK (14.06 MW)
MQTT message with mid=293 successfully published.
  Power published: SAPHWF1 (232.882 MW)MQTT message with mid=294 successfully published.

  Power published: SHOAL (43.76 MW)
MQTT message with mid=295 successfully published.
  Power published: SMTHBES1 (0.061 MW)
MQTT message with mid=296 successfully published.
  Power published: SNOWNTH (125.6 MW)
MQTT message with mid=297 successfully published.
  Power published: SNOWSTH (115.2 MW)
MQTT message with mid=298 successfully published.
  Power published: SNOWTOWN (92.189 MW)MQTT message with mid=299 successfully published.

  Power published: SNOWY6 (52.4 MW)
MQTT message with mid=300 successfully published.
  Power published: STANWELL (228.964 MW)
MQTT message with mid=301 successfully published.
  Power published: STARFHILL (6.298 MW)
MQTT message with mid=302 successfully published.
  Power published: STOCKYD (338.22 MW)
MQTT message with mid=303 successfully published.
  Power published: STWF (139.424 MW)
MQTT message with mid=304 successfully published.
  Power published: TARALGA (47.943 MW)
MQTT message with mid=305 successfully published.
  Power published: TARONGN (279.438 MW)MQTT message with mid=306 successfully published.

  Power published: TARRALEA (59.6 MW)
MQTT message with mid=307 successfully published.
  Power published: TB2SF (0.284 MW)MQTT message with mid=308 successfully published.

  Power published: TIB (3.67 MW)
MQTT message with mid=309 successfully published.
  Power published: TULLYSM (10.0 MW)MQTT message with mid=310 successfully published.

  Power published: TUNGATIN (81.3 MW)
MQTT message with mid=311 successfully published.
  Power published: ULBESS (1.352 MW)
MQTT message with mid=312 successfully published.
  Power published: VBB (1.7 MW)MQTT message with mid=313 successfully published.

  Power published: VP (0.0 MW)
MQTT message with mid=314 successfully published.
  Power published: WALGRV (0.314 MW)
MQTT message with mid=315 successfully published.
  Power published: WANDBG (4.383 MW)MQTT message with mid=316 successfully published.

  Power published: WATERLWF (103.1 MW)
MQTT message with mid=317 successfully published.
  Power published: WAUBRAWF (53.227 MW)MQTT message with mid=318 successfully published.

  Power published: WDBESS (1.21 MW)
MQTT message with mid=319 successfully published.
  Power published: WGWF (99.1 MW)
MQTT message with mid=320 successfully published.
  Power published: WOODLWN (14.322 MW)MQTT message with mid=321 successfully published.

  Power published: WOOLNTH1 (26.38 MW)
MQTT message with mid=322 successfully published.
  Power published: WPWF (44.29 MW)
MQTT message with mid=323 successfully published.
  Power published: WRWF1 (38.826 MW)
MQTT message with mid=324 successfully published.
  Power published: WTAHB (2.789 MW)
MQTT message with mid=325 successfully published.
  Power published: YALLOURN (250.25 MW)MQTT message with mid=326 successfully published.

  Power published: YAMBUK (5.2 MW)MQTT message with mid=327 successfully published.

  Power published: YARWUN (85.77 MW)MQTT message with mid=328 successfully published.

  Power published: YENDONWF (101.02 MW)
MQTT message with mid=329 successfully published.
  Power published: YSWF (19.8 MW)
MQTT message with mid=330 successfully published.
Finished timestamp 2025-10-01 00:05:00+10:00. Waiting 0s before next batch...

Publishing data for timestamp: 2025-10-01 00:10:00+10:00
  Power published: 0WAMBOWF (61.929 MW)
MQTT message with mid=331 successfully published.
  Power published: ARWF (37.5 MW)
MQTT message with mid=332 successfully published.
  Power published: BANGOWF (88.397 MW)
MQTT message with mid=333 successfully published.
  Power published: BASTYAN (69.8 MW)
MQTT message with mid=334 successfully published.
  Power published: BAYSW (547.97 MW)MQTT message with mid=335 successfully published.

  Power published: BBATTERY (0.147 MW)MQTT message with mid=336 successfully published.

  Power published: BHB (2.043 MW)
MQTT message with mid=337 successfully published.
  Power published: BHWF (6.958 MW)MQTT message with mid=338 successfully published.

  Power published: BIALAWF (77.589 MW)
MQTT message with mid=339 successfully published.
  Power published: BLYTHB (22.98 MW)MQTT message with mid=340 successfully published.

  Power published: BOCOROCK (53.57 MW)MQTT message with mid=341 successfully published.

  Power published: BODWF (42.58 MW)MQTT message with mid=342 successfully published.

  Power published: BOLIVAR (0.001 MW)
MQTT message with mid=343 successfully published.
  Power published: BRYB1WF1 (130.016 MW)
MQTT message with mid=344 successfully published.
  Power published: BULGANA (47.89 MW)
MQTT message with mid=345 successfully published.
  Power published: BWTR1 (19.892 MW)
MQTT message with mid=346 successfully published.
  Power published: CALLIDEC1 (0.0 MW)
MQTT message with mid=347 successfully published.
  Power published: CALL_B (279.7 MW)
MQTT message with mid=348 successfully published.
  Power published: CANUNDA1 (28.934 MW)
MQTT message with mid=349 successfully published.
  Power published: CAPBES (6.68 MW)MQTT message with mid=350 successfully published.

  Power published: CAPTL_WF (114.49 MW)
MQTT message with mid=351 successfully published.
  Power published: CATHROCK (42.9 MW)
MQTT message with mid=352 successfully published.
  Power published: CETHANA (31.364 MW)
MQTT message with mid=353 successfully published.
  Power published: CHBESS (0.033 MW)
MQTT message with mid=354 successfully published.
  Power published: CHYTWF (13.15 MW)
MQTT message with mid=355 successfully published.
  Power published: CLEMGPWF (50.496 MW)
MQTT message with mid=356 successfully published.
  Power published: CLRKCWF (277.299 MW)
MQTT message with mid=357 successfully published.
  Power published: CLUNY (18.278 MW)
MQTT message with mid=358 successfully published.
  Power published: COLWF01 (118.903 MW)
MQTT message with mid=359 successfully published.
  Power published: CONDONG1 (21.58 MW)
MQTT message with mid=360 successfully published.
  Power published: COOPGWF (325.34 MW)
MQTT message with mid=361 successfully published.
  Power published: CROOKWF2 (73.384 MW)MQTT message with mid=362 successfully published.

  Power published: CROOKWF3 (38.233 MW)
MQTT message with mid=363 successfully published.
  Power published: CROWLWF (63.924 MW)
MQTT message with mid=364 successfully published.
  Power published: CRURWF1 (130.198 MW)
MQTT message with mid=365 successfully published.
  Power published: CTHLWF (12.497 MW)
MQTT message with mid=366 successfully published.
  Power published: CULLERIN (24.34 MW)
MQTT message with mid=367 successfully published.
  Power published: DALNTH (0.102 MW)MQTT message with mid=368 successfully published.

  Power published: DARTM (110.1 MW)MQTT message with mid=369 successfully published.

  Power published: DEVILS_G (32.55 MW)
MQTT message with mid=370 successfully published.
  Power published: DPNTB (0.014 MW)
MQTT message with mid=371 successfully published.
  Power published: DULAWF (172.4 MW)MQTT message with mid=372 successfully published.

  Power published: DUNDWF (58.4 MW)
MQTT message with mid=373 successfully published.
  Power published: EILDON (47.12 MW)
MQTT message with mid=374 successfully published.

  Power published: ELAINEWF (45.19 MW)MQTT message with mid=375 successfully published.

  Power published: ERARING (455.293 MW)
MQTT message with mid=376 successfully published.
  Power published: ERB (1.111 MW)
MQTT message with mid=377 successfully published.
  Power published: FISHER (44.77 MW)MQTT message with mid=378 successfully published.

  Power published: FLYCRKWF (9.95 MW)
MQTT message with mid=379 successfully published.
  Power published: GANNBESS (0.206 MW)
MQTT message with mid=380 successfully published.
  Power published: GERMCRK (17.189 MW)MQTT message with mid=381 successfully published.

  Power published: GORDON (24.24 MW)
MQTT message with mid=382 successfully published.
  Power published: GPWFEST (175.14 MW)MQTT message with mid=383 successfully published.

  Power published: GRANWF (29.67 MW)
MQTT message with mid=384 successfully published.
  Power published: GREENB (0.243 MW)MQTT message with mid=385 successfully published.

  Power published: GSTONE (150.199 MW)
MQTT message with mid=386 successfully published.
  Power published: GSWF (198.1 MW)
MQTT message with mid=387 successfully published.
  Power published: GULLRGWF (118.013 MW)
MQTT message with mid=388 successfully published.
  Power published: GUNNING (34.019 MW)
MQTT message with mid=389 successfully published.
  Power published: HALLWF (74.26 MW)
MQTT message with mid=390 successfully published.
  Power published: HALLWF2 (56.52 MW)
MQTT message with mid=391 successfully published.
  Power published: HBESS (0.9 MW)MQTT message with mid=392 successfully published.

  Power published: HD1WF (47.01 MW)
MQTT message with mid=393 successfully published.
  Power published: HORNSDAL (88.6 MW)
MQTT message with mid=394 successfully published.
  Power published: HORNSDAL2 (97.7 MW)MQTT message with mid=395 successfully published.

  Power published: HORNSDAL3 (98.6 MW)
MQTT message with mid=396 successfully published.
  Power published: HORNSDPR (14.9 MW)MQTT message with mid=397 successfully published.

  Power published: HUMENSW (21.292 MW)MQTT message with mid=398 successfully published.

  Power published: HVWW (0.029 MW)
MQTT message with mid=399 successfully published.
  Power published: KABANWF (123.022 MW)
MQTT message with mid=400 successfully published.
  Power published: KAREEYA (21.555 MW)MQTT message with mid=401 successfully published.

  Power published: KESS1 (1.94 MW)MQTT message with mid=402 successfully published.

  Power published: KIATAWF (30.5 MW)MQTT message with mid=403 successfully published.

  Power published: KOGANCK (724.556 MW)
MQTT message with mid=404 successfully published.
  Power published: LBBESS (0.6 MW)
MQTT message with mid=405 successfully published.
  Power published: LEM_WIL (87.006 MW)MQTT message with mid=406 successfully published.

  Power published: LGAPWF1 (46.22 MW)
MQTT message with mid=407 successfully published.
  Power published: LI_WY_CA (154.912 MW)MQTT message with mid=408 successfully published.

  Power published: LKBONNY1 (43.94 MW)
MQTT message with mid=409 successfully published.
  Power published: LKBONNY3 (24.729 MW)
MQTT message with mid=410 successfully published.
  Power published: LKBONNY_2 (99.149 MW)MQTT message with mid=411 successfully published.

  Power published: LOYYANGA (388.0 MW)
MQTT message with mid=412 successfully published.
  Power published: LOYYB (456.375 MW)
MQTT message with mid=413 successfully published.
  Power published: MACARTH (116.0 MW)MQTT message with mid=414 successfully published.

  Power published: MACKNTSH (68.79 MW)MQTT message with mid=415 successfully published.

  Power published: MCINTYR (140.059 MW)
MQTT message with mid=416 successfully published.
  Power published: MEADOWBK (43.956 MW)
MQTT message with mid=417 successfully published.
  Power published: MEWF (53.561 MW)MQTT message with mid=418 successfully published.

  Power published: MILLMERN (0.0 MW)
MQTT message with mid=419 successfully published.
  Power published: MLWF (11.235 MW)MQTT message with mid=420 successfully published.

  Power published: MOORAWF1 (220.38 MW)
MQTT message with mid=421 successfully published.
  Power published: MP (419.94 MW)
MQTT message with mid=422 successfully published.
  Power published: MRTLSWF (72.25 MW)
MQTT message with mid=423 successfully published.
  Power published: MTGELWF (74.548 MW)
MQTT message with mid=424 successfully published.
  Power published: MTMERCER (84.8 MW)
MQTT message with mid=425 successfully published.
  Power published: MTMILLAR (28.8 MW)
MQTT message with mid=426 successfully published.
  Power published: MUSSELRO (36.0 MW)MQTT message with mid=427 successfully published.

  Power published: MUWAWF (196.81 MW)
MQTT message with mid=428 successfully published.
  Power published: NBHWF (106.8 MW)
MQTT message with mid=429 successfully published.
  Power published: OAKLAND (34.4 MW)
MQTT message with mid=430 successfully published.
  Power published: PALOONA (29.69 MW)
MQTT message with mid=431 successfully published.
  Power published: PAREPW (36.08 MW)
MQTT message with mid=432 successfully published.
  Power published: PIONEER (41.8 MW)MQTT message with mid=433 successfully published.

  Power published: PORTWF (53.8 MW)
MQTT message with mid=434 successfully published.
  Power published: PTINA (3.42 MW)
MQTT message with mid=435 successfully published.
  Power published: QBYNB (0.138 MW)MQTT message with mid=436 successfully published.

  Power published: REECE (118.963 MW)
MQTT message with mid=437 successfully published.
  Power published: REPULSE (33.032 MW)
MQTT message with mid=438 successfully published.
  Power published: RIVNB (0.022 MW)MQTT message with mid=439 successfully published.

  Power published: ROWALLAN (0.008 MW)MQTT message with mid=440 successfully published.

  Power published: RPCG (12.6 MW)MQTT message with mid=441 successfully published.

  Power published: RYANCWF (75.56 MW)
MQTT message with mid=442 successfully published.
  Power published: RYEPARK (174.778 MW)MQTT message with mid=443 successfully published.

  Power published: SALTCRK (13.56 MW)
MQTT message with mid=444 successfully published.
  Power published: SAPHWF1 (231.746 MW)MQTT message with mid=445 successfully published.

  Power published: SHOAL (44.0 MW)
MQTT message with mid=446 successfully published.
  Power published: SMTHBES1 (0.054 MW)
MQTT message with mid=447 successfully published.
  Power published: SNOWNTH (121.2 MW)
MQTT message with mid=448 successfully published.
  Power published: SNOWSTH (114.9 MW)
MQTT message with mid=449 successfully published.
  Power published: SNOWTOWN (90.588 MW)
MQTT message with mid=450 successfully published.
  Power published: SNOWY3 (62.0 MW)
MQTT message with mid=451 successfully published.
  Power published: STANWELL (247.268 MW)MQTT message with mid=452 successfully published.

  Power published: STARFHILL (6.498 MW)
MQTT message with mid=453 successfully published.
  Power published: STOCKYD (332.23 MW)MQTT message with mid=454 successfully published.

  Power published: STWF (131.745 MW)
MQTT message with mid=455 successfully published.
  Power published: TARALGA (46.998 MW)
MQTT message with mid=456 successfully published.
  Power published: TARONGN (279.625 MW)
MQTT message with mid=457 successfully published.
  Power published: TARRALEA (59.7 MW)MQTT message with mid=458 successfully published.

  Power published: TB2SF (0.27 MW)MQTT message with mid=459 successfully published.

  Power published: TIB (3.08 MW)
MQTT message with mid=460 successfully published.
  Power published: TULLYSM (8.8 MW)MQTT message with mid=461 successfully published.

  Power published: TUMUT3 (17.26 MW)
MQTT message with mid=462 successfully published.
  Power published: TUNGATIN (90.09 MW)
MQTT message with mid=463 successfully published.
  Power published: ULBESS (0.018 MW)
MQTT message with mid=464 successfully published.
  Power published: VP (0.0 MW)MQTT message with mid=465 successfully published.

  Power published: WALGRV (0.068 MW)MQTT message with mid=466 successfully published.

  Power published: WANDBG (6.705 MW)
MQTT message with mid=467 successfully published.
  Power published: WATERLWF (101.0 MW)MQTT message with mid=468 successfully published.

  Power published: WAUBRAWF (59.846 MW)
MQTT message with mid=469 successfully published.
  Power published: WDBESS (0.548 MW)
MQTT message with mid=470 successfully published.
  Power published: WGWF (104.5 MW)
MQTT message with mid=471 successfully published.
  Power published: WKIEWA (17.0 MW)
MQTT message with mid=472 successfully published.
  Power published: WOODLWN (13.452 MW)
MQTT message with mid=473 successfully published.
  Power published: WOOLNTH1 (25.48 MW)MQTT message with mid=474 successfully published.

  Power published: WPWF (45.74 MW)
MQTT message with mid=475 successfully published.
  Power published: WRWF1 (42.274 MW)
MQTT message with mid=476 successfully published.
  Power published: WTAHB (1.777 MW)
MQTT message with mid=477 successfully published.
  Power published: YALLOURN (246.25 MW)MQTT message with mid=478 successfully published.

  Power published: YAMBUK (5.3 MW)
MQTT message with mid=479 successfully published.
  Power published: YARWUN (85.01 MW)MQTT message with mid=480 successfully published.

  Power published: YENDONWF (98.12 MW)
MQTT message with mid=481 successfully published.
  Power published: YSWF (19.7 MW)
MQTT message with mid=482 successfully published.
Finished timestamp 2025-10-01 00:10:00+10:00. Waiting 0s before next batch...

Publishing data for timestamp: 2025-10-01 00:15:00+10:00
  Power published: 0MREH (0.856 MW)
MQTT message with mid=483 successfully published.
  Power published: 0WAMBOWF (60.274 MW)
MQTT message with mid=484 successfully published.
  Power published: ADP (0.003 MW)MQTT message with mid=485 successfully published.

  Power published: ARWF (43.5 MW)
MQTT message with mid=486 successfully published.
  Power published: BANGOWF (86.195 MW)
MQTT message with mid=487 successfully published.
  Power published: BASTYAN (69.95 MW)
MQTT message with mid=488 successfully published.
  Power published: BAYSW (550.607 MW)MQTT message with mid=489 successfully published.

  Power published: BHB (1.935 MW)
MQTT message with mid=490 successfully published.
  Power published: BHWF (9.61 MW)MQTT message with mid=491 successfully published.

  Power published: BIALAWF (89.452 MW)
MQTT message with mid=492 successfully published.
  Power published: BLUFF (46.6 MW)
MQTT message with mid=493 successfully published.
  Power published: BLYTHB (1.0 MW)
MQTT message with mid=494 successfully published.
  Power published: BOCOROCK (57.65 MW)
MQTT message with mid=495 successfully published.
  Power published: BODWF (56.614 MW)MQTT message with mid=496 successfully published.

  Power published: BRYB1WF1 (123.656 MW)MQTT message with mid=497 successfully published.

  Power published: BULGANA (46.42 MW)MQTT message with mid=498 successfully published.

  Power published: BWTR1 (17.148 MW)MQTT message with mid=499 successfully published.

  Power published: CALLIDEC1 (0.0 MW)MQTT message with mid=500 successfully published.

  Power published: CALL_B (279.6 MW)
MQTT message with mid=501 successfully published.
  Power published: CANUNDA1 (23.828 MW)
MQTT message with mid=502 successfully published.
  Power published: CAPBES (0.19 MW)
MQTT message with mid=503 successfully published.
  Power published: CAPTL_WF (114.556 MW)MQTT message with mid=504 successfully published.

  Power published: CATHROCK (41.7 MW)
MQTT message with mid=505 successfully published.
  Power published: CBWWBA (0.001 MW)
MQTT message with mid=506 successfully published.
  Power published: CETHANA (44.596 MW)
MQTT message with mid=507 successfully published.
  Power published: CHBESS (0.024 MW)MQTT message with mid=508 successfully published.

  Power published: CHYTWF (13.1 MW)
MQTT message with mid=509 successfully published.
  Power published: CLEMGPWF (49.272 MW)MQTT message with mid=510 successfully published.

  Power published: CLRKCWF (272.613 MW)MQTT message with mid=511 successfully published.

  Power published: CLUNY (18.173 MW)MQTT message with mid=512 successfully published.

  Power published: COLWF01 (132.702 MW)
MQTT message with mid=513 successfully published.
  Power published: CONDONG1 (22.26 MW)
MQTT message with mid=514 successfully published.
  Power published: COOPGWF (328.0 MW)
MQTT message with mid=515 successfully published.
  Power published: CROOKWF2 (74.715 MW)
MQTT message with mid=516 successfully published.
  Power published: CROOKWF3 (38.369 MW)
MQTT message with mid=517 successfully published.
  Power published: CROWLWF (61.45 MW)
MQTT message with mid=518 successfully published.
  Power published: CRURWF1 (119.396 MW)
MQTT message with mid=519 successfully published.
  Power published: CTHLWF (10.471 MW)
MQTT message with mid=520 successfully published.
  Power published: CULLERIN (23.89 MW)
MQTT message with mid=521 successfully published.
  Power published: DALNTH (0.087 MW)
MQTT message with mid=522 successfully published.
  Power published: DARTM (110.2 MW)MQTT message with mid=523 successfully published.

  Power published: DEVILS_G (26.402 MW)
MQTT message with mid=524 successfully published.
  Power published: DPNTB (0.082 MW)
MQTT message with mid=525 successfully published.
  Power published: DULAWF (172.8 MW)
MQTT message with mid=526 successfully published.
  Power published: DUNDWF (51.51 MW)
MQTT message with mid=527 successfully published.
  Power published: EILDON (47.08 MW)
MQTT message with mid=528 successfully published.
  Power published: ELAINEWF (46.76 MW)
MQTT message with mid=529 successfully published.
  Power published: ERARING (478.071 MW)MQTT message with mid=530 successfully published.

  Power published: ERB (1.062 MW)
MQTT message with mid=531 successfully published.
  Power published: FISHER (44.86 MW)
MQTT message with mid=532 successfully published.
  Power published: FLYCRKWF (8.07 MW)MQTT message with mid=533 successfully published.

  Power published: GANNBESS (0.14 MW)
MQTT message with mid=534 successfully published.
  Power published: GERMCRK (16.076 MW)
MQTT message with mid=535 successfully published.
  Power published: GORDON (24.445 MW)
MQTT message with mid=536 successfully published.
  Power published: GPWFEST (194.47 MW)
MQTT message with mid=537 successfully published.
  Power published: GRANWF (29.77 MW)
MQTT message with mid=538 successfully published.
  Power published: GREENB (0.384 MW)
MQTT message with mid=539 successfully published.
  Power published: GSTONE (129.972 MW)
MQTT message with mid=540 successfully published.
  Power published: GSWF (193.79 MW)
MQTT message with mid=541 successfully published.
  Power published: GULLRGWF (114.153 MW)
MQTT message with mid=542 successfully published.
  Power published: GUNNING (35.656 MW)
MQTT message with mid=543 successfully published.
  Power published: HALLWF (74.27 MW)
MQTT message with mid=544 successfully published.
  Power published: HALLWF2 (56.82 MW)
MQTT message with mid=545 successfully published.
  Power published: HD1WF (44.26 MW)
MQTT message with mid=546 successfully published.
  Power published: HORNSDAL (83.6 MW)MQTT message with mid=547 successfully published.

  Power published: HORNSDAL2 (94.9 MW)MQTT message with mid=548 successfully published.

  Power published: HORNSDAL3 (96.3 MW)MQTT message with mid=549 successfully published.

  Power published: HORNSDPR (16.1 MW)
MQTT message with mid=550 successfully published.
  Power published: HUMENSW (21.612 MW)
MQTT message with mid=551 successfully published.
  Power published: KABANWF (118.053 MW)MQTT message with mid=552 successfully published.

  Power published: KAREEYA (21.558 MW)
MQTT message with mid=553 successfully published.
  Power published: KIATAWF (29.1 MW)MQTT message with mid=554 successfully published.

  Power published: KOGANCK (722.894 MW)
MQTT message with mid=555 successfully published.
  Power published: LBBESS (0.15 MW)
MQTT message with mid=556 successfully published.
  Power published: LEM_WIL (86.953 MW)
MQTT message with mid=557 successfully published.
  Power published: LGAPWF1 (46.84 MW)
MQTT message with mid=558 successfully published.
  Power published: LI_WY_CA (154.708 MW)MQTT message with mid=559 successfully published.

  Power published: LKBONNY1 (30.722 MW)MQTT message with mid=560 successfully published.

  Power published: LKBONNY3 (25.734 MW)
MQTT message with mid=561 successfully published.
  Power published: LKBONNY_2 (79.501 MW)
MQTT message with mid=562 successfully published.
  Power published: LOYYANGA (372.0 MW)
MQTT message with mid=563 successfully published.
  Power published: LOYYB (454.125 MW)
MQTT message with mid=564 successfully published.
  Power published: MACARTH (100.6 MW)
MQTT message with mid=565 successfully published.
  Power published: MACKNTSH (69.15 MW)MQTT message with mid=566 successfully published.

  Power published: MANNUMB (4.77 MW)
MQTT message with mid=567 successfully published.
  Power published: MCINTYR (139.575 MW)MQTT message with mid=568 successfully published.

  Power published: MEADOWBK (43.442 MW)MQTT message with mid=569 successfully published.

  Power published: MEWF (48.29 MW)
MQTT message with mid=570 successfully published.
  Power published: MILLMERN (0.0 MW)
MQTT message with mid=571 successfully published.
  Power published: MLWF (13.995 MW)
MQTT message with mid=572 successfully published.
  Power published: MOORAWF1 (222.13 MW)
MQTT message with mid=573 successfully published.
  Power published: MP (393.646 MW)
MQTT message with mid=574 successfully published.
  Power published: MRTLSWF (63.89 MW)MQTT message with mid=575 successfully published.

  Power published: MTGELWF (88.874 MW)
MQTT message with mid=576 successfully published.
  Power published: MTMERCER (81.1 MW)
MQTT message with mid=577 successfully published.
  Power published: MTMILLAR (30.2 MW)
MQTT message with mid=578 successfully published.
  Power published: MUSSELRO (31.2 MW)
MQTT message with mid=579 successfully published.
  Power published: MUWAWF (192.68 MW)MQTT message with mid=580 successfully published.

  Power published: NBHWF (104.1 MW)MQTT message with mid=581 successfully published.

  Power published: OAKLAND (35.2 MW)MQTT message with mid=582 successfully published.

  Power published: PALOONA (29.5 MW)
MQTT message with mid=583 successfully published.
  Power published: PAREPW (36.01 MW)MQTT message with mid=584 successfully published.

  Power published: PIONEER (42.0 MW)
MQTT message with mid=585 successfully published.
  Power published: PORTWF (62.6 MW)
MQTT message with mid=586 successfully published.
  Power published: PTINA (3.52 MW)
MQTT message with mid=587 successfully published.
  Power published: QBYNB (0.004 MW)MQTT message with mid=588 successfully published.

  Power published: RANGEB (0.45 MW)
MQTT message with mid=589 successfully published.
  Power published: REECE (118.415 MW)
MQTT message with mid=590 successfully published.
  Power published: REPULSE (32.709 MW)
MQTT message with mid=591 successfully published.
  Power published: RESS (0.492 MW)
MQTT message with mid=592 successfully published.
  Power published: RIVNB (0.046 MW)MQTT message with mid=593 successfully published.

  Power published: RPCG (13.7 MW)
MQTT message with mid=594 successfully published.
  Power published: RUBICON (0.72 MW)
MQTT message with mid=595 successfully published.
  Power published: RYANCWF (77.87 MW)
MQTT message with mid=596 successfully published.
  Power published: RYEPARK (174.416 MW)MQTT message with mid=597 successfully published.

  Power published: SALTCRK (15.04 MW)
MQTT message with mid=598 successfully published.
  Power published: SAPHWF1 (233.284 MW)
MQTT message with mid=599 successfully published.
  Power published: SHOAL (43.78 MW)
MQTT message with mid=600 successfully published.
  Power published: SMTHBES1 (0.06 MW)MQTT message with mid=601 successfully published.

  Power published: SNOWNTH (121.6 MW)
MQTT message with mid=602 successfully published.
  Power published: SNOWSTH (113.9 MW)
MQTT message with mid=603 successfully published.
  Power published: SNOWTOWN (91.48 MW)
MQTT message with mid=604 successfully published.
  Power published: STANWELL (259.06 MW)
MQTT message with mid=605 successfully published.
  Power published: STARFHILL (6.398 MW)
MQTT message with mid=606 successfully published.
  Power published: STOCKYD (332.55 MW)MQTT message with mid=607 successfully published.

  Power published: STWF (142.38 MW)MQTT message with mid=608 successfully published.

  Power published: TARALGA (47.398 MW)MQTT message with mid=609 successfully published.

  Power published: TB2SF (0.263 MW)
MQTT message with mid=610 successfully published.
  Power published: TIB (2.77 MW)MQTT message with mid=611 successfully published.

  Power published: TULLYSM (7.9 MW)
MQTT message with mid=612 successfully published.
  Power published: TUMUT3 (121.73 MW)
MQTT message with mid=613 successfully published.
  Power published: TUNGATIN (90.69 MW)
MQTT message with mid=614 successfully published.
  Power published: VP (0.0 MW)
MQTT message with mid=615 successfully published.
  Power published: WALGRV (0.124 MW)MQTT message with mid=616 successfully published.

  Power published: WANDBG (1.788 MW)MQTT message with mid=617 successfully published.

  Power published: WATERLWF (102.3 MW)
MQTT message with mid=618 successfully published.
  Power published: WAUBRAWF (65.686 MW)MQTT message with mid=619 successfully published.

  Power published: WDBESS (0.171 MW)
MQTT message with mid=620 successfully published.
  Power published: WGWF (98.0 MW)
MQTT message with mid=621 successfully published.
  Power published: WOODLWN (15.438 MW)MQTT message with mid=622 successfully published.

  Power published: WOOLNTH1 (22.92 MW)
MQTT message with mid=623 successfully published.
  Power published: WPWF (47.29 MW)
MQTT message with mid=624 successfully published.
  Power published: WRWF1 (38.424 MW)MQTT message with mid=625 successfully published.

  Power published: YALLOURN (249.0 MW)MQTT message with mid=626 successfully published.

  Power published: YAMBUK (6.1 MW)MQTT message with mid=627 successfully published.

  Power published: YARWUN (84.91 MW)
MQTT message with mid=628 successfully published.
  Power published: YENDONWF (95.68 MW)MQTT message with mid=629 successfully published.

  Power published: YSWF (18.3 MW)
MQTT message with mid=630 successfully published.
Finished timestamp 2025-10-01 00:15:00+10:00. Waiting 0s before next batch...

Publishing data for timestamp: 2025-10-01 00:20:00+10:00
  Power published: 0MREH (0.984 MW)
MQTT message with mid=631 successfully published.
  Power published: 0WAMBOWF (62.89 MW)MQTT message with mid=632 successfully published.

  Power published: ADP (0.018 MW)MQTT message with mid=633 successfully published.

  Power published: ARWF (46.0 MW)MQTT message with mid=634 successfully published.

  Power published: BANGOWF (87.098 MW)MQTT message with mid=635 successfully published.

  Power published: BASTYAN (69.92 MW)
MQTT message with mid=636 successfully published.
  Power published: BAYSW (550.021 MW)MQTT message with mid=637 successfully published.

  Power published: BBATTERY (0.179 MW)
MQTT message with mid=638 successfully published.
  Power published: BHB (2.096 MW)MQTT message with mid=639 successfully published.

  Power published: BHWF (11.549 MW)
MQTT message with mid=640 successfully published.
  Power published: BIALAWF (89.097 MW)
MQTT message with mid=641 successfully published.
  Power published: BLUFF (46.4 MW)
MQTT message with mid=642 successfully published.
  Power published: BLYTHB (0.07 MW)
MQTT message with mid=643 successfully published.
  Power published: BOCOROCK (63.07 MW)
MQTT message with mid=644 successfully published.
  Power published: BODWF (47.546 MW)
MQTT message with mid=645 successfully published.
  Power published: BRYB1WF1 (120.616 MW)
MQTT message with mid=646 successfully published.
  Power published: BULGANA (0.03 MW)
MQTT message with mid=647 successfully published.
  Power published: CALLIDEC1 (0.0 MW)MQTT message with mid=648 successfully published.

  Power published: CALL_B (280.3 MW)
MQTT message with mid=649 successfully published.
  Power published: CANUNDA1 (18.221 MW)
MQTT message with mid=650 successfully published.
  Power published: CAPBES (1.14 MW)MQTT message with mid=651 successfully published.

  Power published: CAPTL_WF (113.572 MW)MQTT message with mid=652 successfully published.

  Power published: CATHROCK (41.5 MW)
MQTT message with mid=653 successfully published.
  Power published: CBWWBA (0.005 MW)
MQTT message with mid=654 successfully published.

  Power published: CETHANA (67.469 MW)
MQTT message with mid=655 successfully published.
  Power published: CHBESS (0.135 MW)MQTT message with mid=656 successfully published.

  Power published: CHYTWF (14.55 MW)
MQTT message with mid=657 successfully published.
  Power published: CLEMGPWF (48.48 MW)
MQTT message with mid=658 successfully published.
  Power published: CLRKCWF (265.011 MW)MQTT message with mid=659 successfully published.

  Power published: CLUNY (18.24 MW)
MQTT message with mid=660 successfully published.
  Power published: COLWF01 (135.491 MW)
MQTT message with mid=661 successfully published.
  Power published: CONDONG1 (19.69 MW)
MQTT message with mid=662 successfully published.
  Power published: COOPGWF (327.54 MW)MQTT message with mid=663 successfully published.

  Power published: CROOKWF2 (75.964 MW)
MQTT message with mid=664 successfully published.
  Power published: CROOKWF3 (33.43 MW)
MQTT message with mid=665 successfully published.
  Power published: CROWLWF (62.472 MW)MQTT message with mid=666 successfully published.

  Power published: CRURWF1 (103.196 MW)
MQTT message with mid=667 successfully published.
  Power published: CTHLWF (9.049 MW)MQTT message with mid=668 successfully published.

  Power published: CULLERIN (24.84 MW)MQTT message with mid=669 successfully published.

  Power published: DALNTH (0.063 MW)MQTT message with mid=670 successfully published.

  Power published: DARTM (109.7 MW)MQTT message with mid=671 successfully published.

  Power published: DEVILS_G (22.02 MW)
MQTT message with mid=672 successfully published.
  Power published: DPNTB (0.148 MW)
MQTT message with mid=673 successfully published.
  Power published: DUNDWF (47.06 MW)
MQTT message with mid=674 successfully published.
  Power published: EILDON (46.96 MW)MQTT message with mid=675 successfully published.

  Power published: ELAINEWF (48.98 MW)
MQTT message with mid=676 successfully published.
  Power published: ERARING (496.358 MW)MQTT message with mid=677 successfully published.

  Power published: ERB (1.038 MW)
MQTT message with mid=678 successfully published.
  Power published: FISHER (44.67 MW)MQTT message with mid=679 successfully published.

  Power published: FLYCRKWF (7.79 MW)
MQTT message with mid=680 successfully published.
  Power published: GANNBESS (0.277 MW)MQTT message with mid=681 successfully published.

  Power published: GERMCRK (16.344 MW)
MQTT message with mid=682 successfully published.
  Power published: GORDON (23.412 MW)
MQTT message with mid=683 successfully published.
  Power published: GPWFEST (206.02 MW)MQTT message with mid=684 successfully published.

  Power published: GRANWF (29.85 MW)
MQTT message with mid=685 successfully published.
  Power published: GREENB (0.531 MW)
MQTT message with mid=686 successfully published.
  Power published: GSTONE (109.737 MW)MQTT message with mid=687 successfully published.

  Power published: GSWF (202.38 MW)MQTT message with mid=688 successfully published.

  Power published: GULLRGWF (117.583 MW)
MQTT message with mid=689 successfully published.
  Power published: GUNNING (33.916 MW)
MQTT message with mid=690 successfully published.
  Power published: HALLWF (73.8 MW)
MQTT message with mid=691 successfully published.
  Power published: HALLWF2 (55.55 MW)
MQTT message with mid=692 successfully published.
  Power published: HBESS (0.3 MW)
MQTT message with mid=693 successfully published.
  Power published: HD1WF (47.09 MW)MQTT message with mid=694 successfully published.

  Power published: HORNSDAL (82.9 MW)MQTT message with mid=695 successfully published.

  Power published: HORNSDAL2 (91.3 MW)MQTT message with mid=696 successfully published.

  Power published: HORNSDAL3 (93.8 MW)MQTT message with mid=697 successfully published.

  Power published: HORNSDPR (0.6 MW)MQTT message with mid=698 successfully published.

  Power published: HUMENSW (21.35 MW)MQTT message with mid=699 successfully published.

  Power published: KABANWF (117.075 MW)
MQTT message with mid=700 successfully published.
  Power published: KAREEYA (21.565 MW)MQTT message with mid=701 successfully published.

  Power published: KESS1 (1.96 MW)MQTT message with mid=702 successfully published.

  Power published: KIATAWF (27.8 MW)
MQTT message with mid=703 successfully published.
  Power published: KOGANCK (721.584 MW)
MQTT message with mid=704 successfully published.
  Power published: LEM_WIL (87.03 MW)MQTT message with mid=705 successfully published.

  Power published: LGAPWF1 (44.93 MW)
MQTT message with mid=706 successfully published.
  Power published: LI_WY_CA (154.524 MW)MQTT message with mid=707 successfully published.

  Power published: LKBONNY1 (26.972 MW)
MQTT message with mid=708 successfully published.
  Power published: LKBONNY3 (20.933 MW)MQTT message with mid=709 successfully published.

  Power published: LKBONNY_2 (67.796 MW)
MQTT message with mid=710 successfully published.
  Power published: LOYYANGA (360.0 MW)MQTT message with mid=711 successfully published.

  Power published: LOYYB (448.125 MW)MQTT message with mid=712 successfully published.

  Power published: MACARTH (95.6 MW)MQTT message with mid=713 successfully published.

  Power published: MACKNTSH (67.87 MW)
MQTT message with mid=714 successfully published.
  Power published: MCINTYR (139.125 MW)MQTT message with mid=715 successfully published.

  Power published: MEADOWBK (43.384 MW)
MQTT message with mid=716 successfully published.
  Power published: MEWF (49.236 MW)
MQTT message with mid=717 successfully published.
  Power published: MILLMERN (0.0 MW)
MQTT message with mid=718 successfully published.
  Power published: MLWF (15.66 MW)MQTT message with mid=719 successfully published.

  Power published: MOORAWF1 (229.55 MW)
MQTT message with mid=720 successfully published.
  Power published: MP (364.129 MW)
MQTT message with mid=721 successfully published.
  Power published: MRTLSWF (55.9 MW)
MQTT message with mid=722 successfully published.
  Power published: MTGELWF (97.864 MW)MQTT message with mid=723 successfully published.

  Power published: MTMERCER (82.6 MW)
MQTT message with mid=724 successfully published.
  Power published: MTMILLAR (31.2 MW)MQTT message with mid=725 successfully published.

  Power published: MUSSELRO (26.5 MW)
MQTT message with mid=726 successfully published.
  Power published: MUWAWF (191.61 MW)
MQTT message with mid=727 successfully published.
  Power published: NBHWF (104.7 MW)
MQTT message with mid=728 successfully published.
  Power published: OAKLAND (35.9 MW)
MQTT message with mid=729 successfully published.
  Power published: PALOONA (29.31 MW)MQTT message with mid=730 successfully published.

  Power published: PAREPW (34.49 MW)MQTT message with mid=731 successfully published.

  Power published: PIBESS (0.022 MW)
MQTT message with mid=732 successfully published.
  Power published: PIONEER (42.8 MW)MQTT message with mid=733 successfully published.

  Power published: PORTWF (70.1 MW)MQTT message with mid=734 successfully published.

  Power published: PTINA (3.33 MW)MQTT message with mid=735 successfully published.

  Power published: QBYNB (0.036 MW)
MQTT message with mid=736 successfully published.
  Power published: REECE (118.957 MW)MQTT message with mid=737 successfully published.

  Power published: REPULSE (32.994 MW)
MQTT message with mid=738 successfully published.
  Power published: RESS (0.755 MW)MQTT message with mid=739 successfully published.

  Power published: RIVNB (0.692 MW)
MQTT message with mid=740 successfully published.
  Power published: ROWALLAN (0.004 MW)MQTT message with mid=741 successfully published.

  Power published: RPCG (12.6 MW)MQTT message with mid=742 successfully published.

  Power published: RUBICON (0.585 MW)
MQTT message with mid=743 successfully published.
  Power published: RYANCWF (78.21 MW)MQTT message with mid=744 successfully published.

  Power published: RYEPARK (179.582 MW)MQTT message with mid=745 successfully published.

  Power published: SALTCRK (15.75 MW)
MQTT message with mid=746 successfully published.
  Power published: SAPHWF1 (235.216 MW)MQTT message with mid=747 successfully published.

  Power published: SHOAL (43.21 MW)MQTT message with mid=748 successfully published.

  Power published: SMTHBES1 (0.066 MW)MQTT message with mid=749 successfully published.

  Power published: SNOWNTH (122.2 MW)
MQTT message with mid=750 successfully published.
  Power published: SNOWSTH (111.9 MW)
MQTT message with mid=751 successfully published.
  Power published: SNOWTOWN (91.663 MW)
MQTT message with mid=752 successfully published.
  Power published: SNOWY3 (61.4 MW)
MQTT message with mid=753 successfully published.
  Power published: STANWELL (265.38 MW)
MQTT message with mid=754 successfully published.
  Power published: STARFHILL (6.298 MW)MQTT message with mid=755 successfully published.

  Power published: STOCKYD (331.52 MW)
MQTT message with mid=756 successfully published.
  Power published: STWF (147.433 MW)
MQTT message with mid=757 successfully published.
  Power published: TARALGA (46.024 MW)MQTT message with mid=758 successfully published.

  Power published: TARONGN (277.938 MW)
MQTT message with mid=759 successfully published.
  Power published: TARRALEA (59.9 MW)
MQTT message with mid=760 successfully published.
  Power published: TB2SF (0.354 MW)MQTT message with mid=761 successfully published.

  Power published: TIB (4.75 MW)
MQTT message with mid=762 successfully published.
  Power published: TULLYSM (7.3 MW)MQTT message with mid=763 successfully published.

  Power published: TUMUT3 (130.19 MW)
MQTT message with mid=764 successfully published.
  Power published: TUNGATIN (78.29 MW)
MQTT message with mid=765 successfully published.
  Power published: ULBESS (0.523 MW)
MQTT message with mid=766 successfully published.
  Power published: VBB (0.2 MW)MQTT message with mid=767 successfully published.

  Power published: VP (0.0 MW)
MQTT message with mid=768 successfully published.
  Power published: WALGRV (0.064 MW)MQTT message with mid=769 successfully published.

  Power published: WANDBG (0.43 MW)MQTT message with mid=770 successfully published.

  Power published: WATERLWF (103.7 MW)
MQTT message with mid=771 successfully published.
  Power published: WAUBRAWF (66.536 MW)
MQTT message with mid=772 successfully published.
  Power published: WDBESS (0.513 MW)
MQTT message with mid=773 successfully published.
  Power published: WGWF (105.6 MW)MQTT message with mid=774 successfully published.

MQTT message with mid=775 successfully published.  Power published: WKIEWA (16.0 MW)

  Power published: WOODLWN (14.999 MW)MQTT message with mid=776 successfully published.

  Power published: WOOLNTH1 (20.55 MW)
MQTT message with mid=777 successfully published.
  Power published: WPWF (49.68 MW)MQTT message with mid=778 successfully published.

  Power published: WRWF1 (39.247 MW)MQTT message with mid=779 successfully published.

  Power published: WTAHB (2.01 MW)
MQTT message with mid=780 successfully published.
  Power published: YALLOURN (252.0 MW)
MQTT message with mid=781 successfully published.
  Power published: YAMBUK (6.3 MW)MQTT message with mid=782 successfully published.

  Power published: YARWUN (85.31 MW)MQTT message with mid=783 successfully published.

  Power published: YENDONWF (93.64 MW)MQTT message with mid=784 successfully published.

  Power published: YSWF (22.1 MW)MQTT message with mid=785 successfully published.

Finished timestamp 2025-10-01 00:20:00+10:00. Waiting 0s before next batch...

Publishing data for timestamp: 2025-10-01 00:25:00+10:00
  Power published: 0MREH (0.776 MW)
MQTT message with mid=786 successfully published.
  Power published: 0WAMBOWF (64.965 MW)MQTT message with mid=787 successfully published.

MQTT message with mid=788 successfully published.  Power published: ADP (0.004 MW)

  Power published: ARWF (50.6 MW)
MQTT message with mid=789 successfully published.
  Power published: BANGOWF (88.695 MW)
MQTT message with mid=790 successfully published.
  Power published: BASTYAN (68.97 MW)
MQTT message with mid=791 successfully published.
  Power published: BAYSW (552.218 MW)
MQTT message with mid=792 successfully published.
  Power published: BHB (2.034 MW)
MQTT message with mid=793 successfully published.
  Power published: BHWF (10.345 MW)MQTT message with mid=794 successfully published.

  Power published: BIALAWF (91.35 MW)
MQTT message with mid=795 successfully published.
  Power published: BLYTHB (0.35 MW)
MQTT message with mid=796 successfully published.
  Power published: BOCOROCK (71.45 MW)
MQTT message with mid=797 successfully published.
  Power published: BODWF (65.651 MW)
MQTT message with mid=798 successfully published.
  Power published: BOLIVAR (0.003 MW)MQTT message with mid=799 successfully published.

  Power published: BRYB1WF1 (113.585 MW)
MQTT message with mid=800 successfully published.
  Power published: BULGANA (46.16 MW)MQTT message with mid=801 successfully published.

  Power published: BWTR1 (17.662 MW)MQTT message with mid=802 successfully published.

  Power published: CALLIDEC1 (0.0 MW)
MQTT message with mid=803 successfully published.
  Power published: CALL_B (280.2 MW)MQTT message with mid=804 successfully published.

  Power published: CANUNDA1 (14.917 MW)MQTT message with mid=805 successfully published.

  Power published: CAPBES (0.67 MW)
MQTT message with mid=806 successfully published.
  Power published: CAPTL_WF (115.666 MW)MQTT message with mid=807 successfully published.

  Power published: CATHROCK (41.8 MW)
MQTT message with mid=808 successfully published.
  Power published: CBWWBA (0.001 MW)
MQTT message with mid=809 successfully published.
  Power published: CETHANA (59.864 MW)
MQTT message with mid=810 successfully published.
  Power published: CHALLWF (30.1 MW)MQTT message with mid=811 successfully published.

  Power published: CHBESS (0.014 MW)MQTT message with mid=812 successfully published.

  Power published: CHYTWF (16.29 MW)MQTT message with mid=813 successfully published.

  Power published: CLEMGPWF (48.047 MW)
MQTT message with mid=814 successfully published.
  Power published: CLRKCWF (271.974 MW)MQTT message with mid=815 successfully published.

  Power published: CLUNY (18.307 MW)MQTT message with mid=816 successfully published.

  Power published: COLWF01 (142.289 MW)MQTT message with mid=817 successfully published.

  Power published: CONDONG1 (21.46 MW)
MQTT message with mid=818 successfully published.
  Power published: COOPGWF (323.47 MW)MQTT message with mid=819 successfully published.

  Power published: CROOKWF2 (74.363 MW)MQTT message with mid=820 successfully published.

  Power published: CROOKWF3 (29.842 MW)MQTT message with mid=821 successfully published.

  Power published: CROWLWF (64.0 MW)
MQTT message with mid=822 successfully published.
  Power published: CRURWF1 (91.899 MW)MQTT message with mid=823 successfully published.

  Power published: CTHLWF (10.666 MW)
MQTT message with mid=824 successfully published.
  Power published: CULLERIN (24.79 MW)MQTT message with mid=825 successfully published.

  Power published: DALNTH (0.056 MW)MQTT message with mid=826 successfully published.

  Power published: DARTM (110.0 MW)
MQTT message with mid=827 successfully published.
  Power published: DEVILS_G (21.588 MW)
MQTT message with mid=828 successfully published.
  Power published: DPNTB (0.002 MW)MQTT message with mid=829 successfully published.

  Power published: DULAWF (173.2 MW)MQTT message with mid=830 successfully published.

  Power published: DUNDWF (46.96 MW)MQTT message with mid=831 successfully published.

  Power published: EILDON (47.08 MW)MQTT message with mid=832 successfully published.

  Power published: ELAINEWF (51.34 MW)MQTT message with mid=833 successfully published.

  Power published: ERARING (517.818 MW)
MQTT message with mid=834 successfully published.
  Power published: ERB (1.062 MW)MQTT message with mid=835 successfully published.

  Power published: FISHER (44.78 MW)
MQTT message with mid=836 successfully published.
  Power published: FLYCRKWF (8.96 MW)
MQTT message with mid=837 successfully published.
  Power published: GANNBESS (0.136 MW)MQTT message with mid=838 successfully published.

  Power published: GERMCRK (16.884 MW)MQTT message with mid=839 successfully published.

  Power published: GORDON (21.72 MW)
MQTT message with mid=840 successfully published.
  Power published: GPWFEST (198.61 MW)
MQTT message with mid=841 successfully published.
  Power published: GRANWF (32.2 MW)
MQTT message with mid=842 successfully published.

  Power published: GREENB (0.054 MW)MQTT message with mid=843 successfully published.

  Power published: GSTONE (110.086 MW)MQTT message with mid=844 successfully published.

  Power published: GSWF (201.11 MW)
MQTT message with mid=845 successfully published.
  Power published: GULLRGWF (119.113 MW)
MQTT message with mid=846 successfully published.
  Power published: GUNNING (35.138 MW)MQTT message with mid=847 successfully published.

  Power published: HALLWF (74.07 MW)
MQTT message with mid=848 successfully published.
  Power published: HALLWF2 (56.19 MW)MQTT message with mid=849 successfully published.

  Power published: HD1WF (46.56 MW)MQTT message with mid=850 successfully published.

  Power published: HORNSDAL (76.7 MW)MQTT message with mid=851 successfully published.

  Power published: HORNSDAL2 (93.9 MW)
MQTT message with mid=852 successfully published.
  Power published: HORNSDAL3 (91.9 MW)
MQTT message with mid=853 successfully published.
  Power published: HORNSDPR (6.9 MW)
MQTT message with mid=854 successfully published.
  Power published: HUMENSW (21.643 MW)
MQTT message with mid=855 successfully published.
  Power published: KABANWF (118.013 MW)MQTT message with mid=856 successfully published.

  Power published: KAREEYA (21.532 MW)
MQTT message with mid=857 successfully published.
  Power published: KESS1 (2.33 MW)
MQTT message with mid=858 successfully published.
  Power published: KIATAWF (27.1 MW)MQTT message with mid=859 successfully published.

  Power published: KOGANCK (724.002 MW)
MQTT message with mid=860 successfully published.

 Streaming stopped by user.
 MQTT client disconnected

# Validation

Chicking unique facilities and how many have a singular type of fuel type in units

In [3]:
df = pd.read_csv("power_emission.csv")

#Fuel Groups
fuel_groups = {
    'battery': 'battery',
    'battery_charging': 'battery',
    'battery_discharging': 'battery',
    'bidirectional': 'battery',
    
    'solar_utility': 'solar',
    'solar_rooftop': 'solar',
    'solar': 'solar',

    'wind': 'wind',
    'wind_offshore': 'wind',

    'coal_black': 'coal',
    'coal_brown': 'coal',

    'gas_ocgt': 'gas',
    'gas_ccgt': 'gas',
    'gas': 'gas',
}

# Convert the 'units' column from a string representation of a list-of-dicts
# into an actual Python list-of-dicts so we can inspect fields inside it.
df['units_parsed'] = df['units'].apply(lambda x: ast.literal_eval(x) if pd.notnull(x) else [])

# Function to check if all units inside a facility share the *same fuel group*
def unified_fueltech(units_list):
    ft = [fuel_groups.get(u.get('fueltech_id'), u.get('fueltech_id')) 
          for u in units_list if isinstance(u, dict)]
    return len(set(ft)) == 1

# Apply the uniformity check to each facility row.
df['all_same_grouped'] = df['units_parsed'].apply(unified_fueltech)

# Collapse dataset to one record per facility (avoid duplicated facility rows).
result_grouped = df[['name', 'all_same_grouped']].drop_duplicates()

# Count how many facilities are uniform vs how many total.
num_same_grouped = result_grouped['all_same_grouped'].sum()
num_total = result_grouped.shape[0]

print(f"Facilities uniform after grouping: {num_same_grouped} out of {num_total}")

Facilities uniform after grouping: 287 out of 304